/**
 * Shorts Builder Frameworks — structural scene-beat templates with camera directions.
 * 12 universal + 60 niche-specific (3 per niche x 20 niches) = 72 total.
 *
 * Each framework defines: scene beats, camera directions, duration target, and category.
 * Camera directions are baked in — no separate camera control UI needed.
 *
 * niches: null = universal (shown for all niches)
 * niches: ['niche_id'] = only shown when that niche is selected
 */

export const BUILDER_FRAMEWORKS = [
  // ════════════════════════════════════════════════════════════════════
  // UNIVERSAL FRAMEWORKS (shown for all niches)
  // ════════════════════════════════════════════════════════════════════
  { id: 'personal_journey', name: 'Personal Journey', category: 'story', niches: null,
    description: 'First-person narrative arc — transformative experience with emotional beats.',
    duration: '30-35s', sceneCount: '5-6 scenes',
    scenes: [
      { label: 'Setup', camera: 'Medium close-up at 50mm f/2.0, eye level, slow push in, warm key light 3200K from camera-left' },
      { label: 'Inciting Moment', camera: 'Close-up at 85mm f/1.4, slight low angle, steady tripod, dramatic single source 4000K' },
      { label: 'Struggle', camera: 'Handheld drift at 35mm f/2.8, medium shot, desaturated grade, cold 5500K overhead' },
      { label: 'Turning Point', camera: 'Wide to close-up rack focus at 50mm, warm-to-bright temperature shift 3500K to 5000K' },
      { label: 'Resolution', camera: 'Slow dolly out at 35mm f/2.0, warm golden grade 3200K, soft focus background' },
    ],
  },
  { id: 'origin_story', name: 'Origin Story', category: 'story', niches: null,
    description: 'Humble beginnings and rise of a brand, person, or idea.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Humble Beginning', camera: 'Wide establishing at 24mm f/2.8, muted desaturated tones, flat 4500K overhead' },
      { label: 'The Spark', camera: 'Close-up detail at 85mm f/1.8, sharp focus on symbolic object, warm 3500K side light' },
      { label: 'First Attempt', camera: 'Medium at 50mm f/2.0, handheld energy, mixed 4500K ambient' },
      { label: 'Breakthrough', camera: 'Dynamic low angle at 35mm f/2.0, push in, building warm 3800K with rim light' },
      { label: 'Where They Are Now', camera: 'Wide cinematic at 24mm f/2.0, warm golden grade 3200K, slow crane out' },
    ],
  },
  { id: 'mini_documentary', name: 'Mini Documentary', category: 'story', niches: null,
    description: 'Authoritative deep-dive with cold open hook and measured pacing.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Cold Open', camera: 'Tight close-up at 85mm f/1.4, dramatic single key at 4000K from sharp angle, dark background' },
      { label: 'Context', camera: 'Medium shot at 50mm f/2.0, documentary three-point lighting 5000K, steady tripod' },
      { label: 'Deep Dive', camera: 'Slow pan at 35mm f/2.8, warm 4500K, tracking across details and evidence' },
      { label: 'Key Insight', camera: 'Close-up at 65mm f/2.0, direct to camera, warm 3800K key from 45 degrees' },
      { label: 'Resolution', camera: 'Wide pull-back at 24mm f/2.8, reflective mood, balanced 4500K fill' },
    ],
  },
  { id: 'explainer', name: 'Explainer', category: 'educational', niches: null,
    description: 'Clear teacher-like walkthrough of a mechanism or process.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'Hook Question', camera: 'Close-up at 85mm f/1.8, curious slight tilt, warm 4000K, direct eye contact' },
      { label: 'Simple Explanation', camera: 'Medium at 50mm f/2.0, clean background, bright 5000K balanced fill' },
      { label: 'Visual Example', camera: 'Top-down or diagram view at 24mm f/4, even 5500K panel lighting, flat composition' },
      { label: 'Takeaway', camera: 'Direct to camera at 50mm f/2.0, steady tripod, confident warm 4200K three-point setup' },
    ],
  },
  { id: 'myth_busting', name: 'Myth Busting', category: 'educational', niches: null,
    description: 'Debunk popular misconceptions with confident energy.',
    duration: '25-30s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Myth', camera: 'Medium at 50mm f/2.0, warm trustworthy 4000K, straight-on framing' },
      { label: 'Why People Believe It', camera: 'Close-up details at 85mm f/1.8, soft focus background, warm 3800K' },
      { label: 'The Truth', camera: 'Direct to camera at 50mm f/2.0, sharp focus, higher contrast 5000K' },
      { label: 'Proof', camera: 'Close-up evidence shots at 85mm f/2.8, clinical 5500K, precise focus' },
      { label: 'Mind Blown', camera: 'Wide dramatic reveal at 24mm f/2.0, bold low angle, bright 5000K' },
    ],
  },
  { id: 'top_countdown', name: 'Top X Countdown', category: 'listicle', niches: null,
    description: 'Ranked list building anticipation toward #1.',
    duration: '30-35s', sceneCount: '6 scenes',
    scenes: [
      { label: 'Tease #1', camera: 'Quick cuts at 35mm f/2.8, mystery angle, partial reveal, dramatic 4000K' },
      { label: 'Entry 5', camera: 'Medium at 50mm f/2.0, steady clean 5000K, standard framing' },
      { label: 'Entry 4', camera: 'Slightly tighter at 65mm f/2.0, building intensity, warmer 4500K' },
      { label: 'Entry 3', camera: 'Close-up at 85mm f/1.8, tension building, dramatic side light 4000K' },
      { label: 'Entry 2', camera: 'Dynamic low angle at 35mm f/2.0, energy building, warm 3800K' },
      { label: '#1 Reveal', camera: 'Epic wide or dramatic close-up at 24mm f/2.0, hero lighting 5000K, maximum impact' },
    ],
  },
  { id: 'before_after', name: 'Before & After', category: 'story', niches: null,
    description: 'Transformation story — the journey from A to B.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Before', camera: 'Flat lighting at 50mm f/2.8, desaturated, steady tripod, cold 5500K overhead' },
      { label: 'The Catalyst', camera: 'Close-up moment at 85mm f/1.4, sharp focus, warm 3800K side light' },
      { label: 'The Process', camera: 'Time-lapse style at 35mm f/2.8, medium shots, shifting light 4000K to 5000K' },
      { label: 'The After', camera: 'Bright warm wide at 24mm f/2.0, triumphant golden 3200K, hero composition' },
    ],
  },
  { id: 'hot_take', name: 'Hot Take', category: 'opinion', niches: null,
    description: 'Bold opinion delivered with confidence — drives comments and shares.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Statement', camera: 'Tight close-up at 85mm f/1.4, direct eye contact, warm 3800K key from 45 degrees' },
      { label: 'Why I Believe This', camera: 'Medium at 50mm f/2.0, confident posture, balanced 4500K three-point' },
      { label: 'The Evidence', camera: 'Cut-away evidence shots at 35mm f/2.8, mixed angles, clinical 5500K' },
      { label: 'The Challenge', camera: 'Return to close-up at 85mm f/1.4, lean in, warm 3500K, confrontational energy' },
    ],
  },
  { id: 'did_you_know', name: 'Did You Know?', category: 'educational', niches: null,
    description: 'Curiosity-driven explanation that subverts common assumptions.',
    duration: '20-25s', sceneCount: '3 scenes',
    scenes: [
      { label: 'The Question', camera: 'Close-up at 85mm f/1.8, intrigued expression, warm 4000K, slight push in' },
      { label: 'The Surprising Answer', camera: 'Wide reveal at 24mm f/2.0, bright 5000K, visual proof composition' },
      { label: 'Why It Matters', camera: 'Medium at 50mm f/2.0, direct delivery, confident 4200K balanced fill' },
    ],
  },
  { id: 'avatar_narrator', name: 'Avatar Narrator', category: 'avatar', niches: null,
    description: 'AI avatar presents to camera — talking head with B-roll cutaways.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Avatar Hook', camera: 'Medium close-up at 50mm f/2.0, avatar centered, eye level, 4500K balanced key' },
      { label: 'Main Point', camera: 'Same framing, slight push in to 65mm, warm 4000K building intimacy' },
      { label: 'B-Roll Cutaway', camera: 'Full-screen cinematic visual at 24mm f/2.0, dramatic 3500K or 5500K per mood' },
      { label: 'Supporting Detail', camera: 'Return to avatar at 50mm f/2.0, medium shot, steady 4500K' },
      { label: 'Avatar Close', camera: 'Close-up at 85mm f/1.8, direct CTA delivery, warm 3800K, confident lean' },
    ],
  },
  { id: 'avatar_split_screen', name: 'Avatar Split Screen', category: 'avatar', niches: null,
    description: 'Avatar on one side, visuals on the other — presentation style.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Avatar Intro', camera: 'Split composition: avatar left at 50mm f/2.0, title card right, balanced 4500K' },
      { label: 'Visual + Commentary', camera: 'Split: avatar left, visual content right, warm 4000K on avatar side' },
      { label: 'Key Point', camera: 'Full-screen visual emphasis at 24mm f/2.0, cinematic 5000K' },
      { label: 'Visual + Commentary', camera: 'Split: avatar left, data/charts right, balanced 4500K' },
      { label: 'Avatar CTA', camera: 'Full avatar at 85mm f/1.8, close-up, direct CTA, warm 3800K' },
    ],
  },
  { id: 'comparison', name: 'Comparison / Versus', category: 'educational', niches: null,
    description: 'Side-by-side comparison — clear winner at the end.',
    duration: '25-30s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Introduce Both', camera: 'Symmetrical wide at 28mm f/2.8, split composition, balanced 5000K' },
      { label: 'Criteria 1', camera: 'Medium at 50mm f/2.0, warm 4500K, left-biased framing for option A' },
      { label: 'Criteria 2', camera: 'Medium at 50mm f/2.0, cool 5500K, right-biased framing for option B' },
      { label: 'Criteria 3', camera: 'Close-up detail at 85mm f/1.8, dramatic comparison, mixed lighting' },
      { label: 'Verdict', camera: 'Direct to camera at 65mm f/2.0, confident 4200K, winner highlighted' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // AI / TECH NEWS
  // ════════════════════════════════════════════════════════════════════
  { id: 'ai_tool_speed_test', name: 'AI Tool Speed Test', category: 'review', niches: ['ai_tech_news'],
    description: 'Head-to-head benchmark of an AI tool against a manual workflow with timed split-screen energy.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Challenge', camera: 'Wide 24mm f/2.8 overhead bird\'s-eye of dual monitors, cool 6500K LED panel wash from above' },
      { label: 'Manual Method', camera: 'Medium close-up at 50mm f/1.8, handheld with slight shake conveying effort, warm 4000K desk lamp from camera-right' },
      { label: 'AI Method', camera: 'Tight 85mm f/1.4 on screen output, rack focus from fingers to screen, neon blue backlight 7000K silhouetting operator' },
      { label: 'Results Reveal', camera: 'Low-angle 35mm f/2.0 hero shot looking up at presenter, dual rim lights at 5500K from both sides, locked tripod' },
    ],
  },
  { id: 'ai_one_prompt_wonder', name: 'One Prompt Wonder', category: 'story', niches: ['ai_tech_news'],
    description: 'Single prompt fed into an AI tool with escalating reveals of what it generates.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Prompt', camera: 'Extreme close-up at 100mm macro f/2.8 on keyboard and screen text, cool monitor glow 6000K' },
      { label: 'Processing', camera: 'Wide 24mm f/4 showing full workstation, overhead fluorescent 5000K mixed with screen blue, static tripod' },
      { label: 'First Output', camera: 'Medium 50mm f/2.0 over-the-shoulder framing screen, warm 4500K fill from left, subtle push-in' },
      { label: 'Enhanced Output', camera: 'Tight 85mm f/1.4 product-shot framing of polished output, bokeh background, rim light 5500K' },
      { label: 'Mind Blown', camera: 'Dutch angle 35mm f/2.0 snap to presenter reaction, dramatic single key at 3500K from below-left' },
    ],
  },
  { id: 'ai_versus_battle', name: 'AI Versus Battle', category: 'review', niches: ['ai_tech_news'],
    description: 'Two competing AI tools tested on the same task with a decisive winner.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Matchup', camera: 'Symmetrical wide 28mm f/2.8 split composition with both tools, flat broadcast 5500K, locked tripod' },
      { label: 'Contender A', camera: 'Medium close-up 50mm f/2.0 biased left-frame, warm-toned 4500K key from camera-left' },
      { label: 'Contender B', camera: 'Medium close-up 50mm f/2.0 biased right-frame, cool-toned 6000K key from camera-right' },
      { label: 'Side by Side', camera: 'Overhead 24mm f/4 comparing both outputs on adjacent screens, even 5000K panel lighting' },
      { label: 'The Verdict', camera: 'Straight-on 85mm f/1.8 tight portrait, single dramatic key at 4000K from 45 degrees, dark background' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // FINANCE / MONEY
  // ════════════════════════════════════════════════════════════════════
  { id: 'finance_rule_breaker', name: 'Money Rule Breaker', category: 'opinion', niches: ['finance_money'],
    description: 'Challenges a widely-accepted financial rule with data-backed contrarian reasoning.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Sacred Rule', camera: 'Medium 50mm f/2.0 straight-on with textbook prop in foreground bokeh, warm tungsten 3500K, authoritative low angle' },
      { label: 'Why It\'s Wrong', camera: 'Dynamic 35mm f/2.8 handheld push-in toward data, overhead 5000K daylight balanced, urgency movement' },
      { label: 'The Real Math', camera: 'Extreme close-up 100mm f/2.8 on calculator or spreadsheet numbers, green accent light from display, tripod-locked' },
      { label: 'The Better Rule', camera: 'Wide 24mm f/2.0 environmental hero shot, golden hour 3200K backlight, warm confident energy' },
    ],
  },
  { id: 'finance_hidden_fee', name: 'Hidden Fee Expose', category: 'investigation', niches: ['finance_money'],
    description: 'Forensic breakdown of fees buried in a common financial product.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Innocent Product', camera: 'Clean 50mm f/2.0 product-shot framing, bright 5500K even lighting, commercial cleanliness' },
      { label: 'First Hidden Fee', camera: 'Slow zoom 85mm f/1.8 into fine print, magnifying glass in foreground, warm desk lamp 3500K from camera-right' },
      { label: 'The Compound Effect', camera: 'Medium wide 35mm f/2.8 with projected growth chart, dramatic 4000K key from above, slight low angle' },
      { label: 'Total Cost Revealed', camera: 'Straight-on 50mm f/2.0 tight on screen showing shocking number, red accent spill, dark environment 2800K' },
      { label: 'The Alternative', camera: 'Wide 28mm f/2.0 pulling back to full environmental shot, bright airy 5500K natural light, optimistic' },
    ],
  },
  { id: 'finance_paycheck_autopsy', name: 'Paycheck Autopsy', category: 'educational', niches: ['finance_money'],
    description: 'Visual dissection of where a typical paycheck actually goes.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Gross Number', camera: 'Overhead 24mm f/4 flat-lay of paycheck stub on desk, even 5000K panel lighting, documentary framing' },
      { label: 'Tax Bite', camera: 'Tight 85mm f/2.0 on tax deduction line, rack focus from gross to net, cold 6500K fluorescent' },
      { label: 'Silent Deductions', camera: 'Medium 50mm f/1.8 over-the-shoulder with pen circling line items, warm 3500K desk light from left' },
      { label: 'What\'s Actually Yours', camera: 'Close-up 100mm f/2.8 macro on net pay figure, dramatic single spot 4000K from above, black negative space' },
      { label: 'Optimization Play', camera: 'Wide 35mm f/2.0 in bright modern space, natural 5500K window light with soft fill, confident forward lean' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // MOTIVATION / SELF-HELP
  // ════════════════════════════════════════════════════════════════════
  { id: 'motivation_one_habit', name: 'One Habit Shift', category: 'strategy', niches: ['motivation_self_help'],
    description: 'Isolates a single daily habit change with before-and-after impact framing.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Struggle', camera: 'Medium 50mm f/2.0 handheld with fatigue-shake, desaturated flat 4500K overhead, defeated posture' },
      { label: 'The One Change', camera: 'Tight 85mm f/1.4 close-up on symbolic action, warm golden 3200K key from window, sharp focus' },
      { label: 'The Compound Effect', camera: 'Wide 28mm f/2.8 time-lapse style, bright airy 5500K daylight, slow dolly revealing progress' },
      { label: 'Your Move', camera: 'Direct 50mm f/2.0 to camera, single warm key 3800K at 45 degrees, dark clean background, intimate' },
    ],
  },
  { id: 'motivation_quit_today', name: 'Quit This Today', category: 'cautionary', niches: ['motivation_self_help'],
    description: 'Identifies one self-sabotaging behavior with visceral impact and a replacement strategy.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Behavior', camera: 'Close-up 85mm f/1.8 on hands performing bad habit, cold 6000K blue-white overhead, clinical' },
      { label: 'The Hidden Cost', camera: 'Medium 50mm f/2.0 slow dolly-in on face, single tungsten key 3200K from sharp camera-left, deep shadows' },
      { label: 'The Science', camera: 'Wide 35mm f/2.8 showing diagram, clean bright 5500K educational lighting, slight low angle' },
      { label: 'The Replacement', camera: 'Tight 85mm f/1.4 on positive action, warm natural 4000K, optimistic soft background' },
      { label: 'The Challenge', camera: 'Direct 50mm f/2.0 eye-level, warm 3500K key with orange fill, dark background, handheld raw energy' },
    ],
  },
  { id: 'motivation_inner_monologue', name: 'Inner Monologue Flip', category: 'motivation', niches: ['motivation_self_help'],
    description: 'Dramatizes the toxic inner voice then rewrites it with an empowering version.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Negative Voice', camera: 'Tight 85mm f/1.4 face in shadow, harsh overhead 6500K creating under-eye shadows, oppressive stillness' },
      { label: 'The Spiral', camera: 'Slow zoom 50mm f/2.0 pulling back to isolated figure, cold 5000K spill from one direction, growing void' },
      { label: 'The Interrupt', camera: 'Snap cut to 35mm f/2.8 with sudden warm 3500K flooding from camera-right, handheld energy, low angle rising' },
      { label: 'The Rewrite', camera: 'Medium close-up 50mm f/1.8, warm 3800K key replacing cold, face half-lit in transition, smooth dolly-in' },
      { label: 'The New Voice', camera: 'Wide 28mm f/2.0 bright full-body hero shot, high-key 5500K from multiple sources, slight crane-up, expansive' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // SCARY / HORROR
  // ════════════════════════════════════════════════════════════════════
  { id: 'horror_found_footage', name: 'Found Footage', category: 'story', niches: ['scary_horror'],
    description: 'Recovered security or phone footage with degrading quality and an unexplainable final frame.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Footage Found', camera: 'Static wide 16mm security cam POV with fisheye distortion, grainy, harsh 5000K overhead, timestamp overlay' },
      { label: 'Normal Activity', camera: 'Medium 28mm f/4 phone-footage style, auto-exposure hunting 4000-5500K, hand tremor, vertical feel' },
      { label: 'First Anomaly', camera: 'Same security angle with digital artifacts, frame stutter, exposure flicker 3500-6000K, static noise' },
      { label: 'Escalation', camera: 'Tight shaky 35mm f/2.8 phone cam with flashlight sole illumination 5500K, violent shake, motion blur' },
      { label: 'Final Frame', camera: 'Freeze frame at 50mm, single camera flash 5500K against pitch black, maximum grain, then static' },
    ],
  },
  { id: 'horror_sleep_paralysis', name: 'Sleep Paralysis Report', category: 'story', niches: ['scary_horror'],
    description: 'First-person sleep paralysis episode with escalating sensory detail.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Falling Asleep', camera: 'Overhead 24mm f/2.0 looking down at figure in bed, cool moonlight 7000K from window, peaceful blue shadows' },
      { label: 'Eyes Open', camera: 'Extreme close-up 100mm f/2.0 macro on open eye reflecting ceiling, cold moonbeam 6500K, razor-thin DOF' },
      { label: 'The Presence', camera: 'Ultra-wide 16mm f/2.8 bed-level POV distorting room geometry, 4000K hallway light under door' },
      { label: 'It Approaches', camera: 'Slow 50mm f/1.4 subject in deep shadow approaching, backlit 3200K amber from doorway, face never revealed' },
      { label: 'Release', camera: 'Snap to 35mm f/2.8 sitting up gasping, 6500K pre-dawn light, handheld panic, then stillness with shadow at frame edge' },
    ],
  },
  { id: 'horror_wrong_turn', name: 'Wrong Turn', category: 'story', niches: ['scary_horror'],
    description: 'Road trip gone wrong with increasingly disturbing roadside details.',
    duration: '30-35s', sceneCount: '6 scenes',
    scenes: [
      { label: 'Open Road', camera: 'Wide 24mm f/2.8 through windshield, golden hour 3200K streaming, dashboard reflections, smooth glide' },
      { label: 'Wrong Turn', camera: 'Medium 50mm f/2.0 GPS losing signal, phone glow 5000K only, shadows darkening outside' },
      { label: 'First Sign', camera: 'Close-up 85mm f/1.8 through passenger window at strange marker, single headlight beam 4500K through fog' },
      { label: 'Dead End', camera: 'Wide 16mm f/2.8 headlights illuminating barrier, dual beams 5000K cutting through dust, harsh shadows' },
      { label: 'The Discovery', camera: 'Tight 85mm f/1.4 flashlight-lit on the ground, handheld tremor, harsh 5500K beam, shallow depth' },
      { label: 'The Rearview', camera: 'Close-up 50mm f/2.0 on rearview mirror, red brake-light glow 2800K behind car, freeze frame' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // HISTORY / DID YOU KNOW
  // ════════════════════════════════════════════════════════════════════
  { id: 'history_artifact', name: 'Artifact Decoded', category: 'educational', niches: ['history_did_you_know'],
    description: 'A mysterious historical artifact progressively decoded to reveal its civilization.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Object', camera: 'Tight 100mm f/2.8 macro with museum-style overhead spot 4000K, dark velvet background, turntable rotation' },
      { label: 'Where Found', camera: 'Wide 24mm f/4 sweeping archaeological landscape, golden hour 3200K, slow pan across ruins' },
      { label: 'First Clue', camera: 'Extreme close-up 100mm macro f/4 on inscriptions, raking side light 4500K revealing texture depth' },
      { label: 'The Breakthrough', camera: 'Medium 50mm f/2.0 hands examining with tool, warm 3500K lamp from below, scholarly atmosphere' },
      { label: 'What It Means', camera: 'Wide 35mm f/2.8 artifact in civilization context, mixed warm 3800K and cool 5500K, contemplative' },
    ],
  },
  { id: 'history_day_changed', name: 'The Day That Changed Everything', category: 'story', niches: ['history_did_you_know'],
    description: 'Minute-by-minute reconstruction of a single pivotal day in history.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Dawn of the Day', camera: 'Wide 28mm f/2.8 early morning light 4000K, mist and period atmosphere, slow crane-up, timestamped' },
      { label: 'The Morning Before', camera: 'Medium 50mm f/2.0 ordinary activity, warm natural 5000K daylight, handheld documentary, people unaware' },
      { label: 'The Moment', camera: 'Tight 85mm f/1.4 freeze-frame on pivotal action, dramatic spot 5500K isolating subject, time-stopped' },
      { label: 'Immediate Aftermath', camera: 'Wide 24mm f/2.0 chaotic handheld, harsh mixed 5500K with smoke diffusion, urgent disoriented angles' },
      { label: 'The Ripple', camera: 'Slow 50mm f/2.8 modern-day same location, cool 6000K contemporary light, locked tripod, permanent change' },
    ],
  },
  { id: 'history_map_redrawn', name: 'When the Map Was Redrawn', category: 'educational', niches: ['history_did_you_know'],
    description: 'How a single treaty, war, or discovery permanently redrew borders and power.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Old Map', camera: 'Overhead 24mm f/4 bird\'s-eye on aged parchment, warm candlelight 2800K paper glow, slow zoom into region' },
      { label: 'The Trigger', camera: 'Medium 50mm f/2.0 dramatic reenactment, single strong key 3500K from window-right, period shadows' },
      { label: 'Lines Redrawn', camera: 'Tight 85mm f/2.0 on pen drawing new borders, warm 3200K oil lamp light, ink glistening, macro intimacy' },
      { label: 'The Consequences', camera: 'Wide 35mm f/2.8 split before-and-after, cool 5000K balanced, documentary objectivity, slow pan' },
      { label: 'The Echo Today', camera: 'Modern 50mm f/2.0 current-day border, natural overcast 6000K, handheld subtle movement, contemporary reality' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // TRUE CRIME
  // ════════════════════════════════════════════════════════════════════
  { id: 'crime_last_seen', name: 'Last Seen', category: 'investigation', niches: ['true_crime'],
    description: 'Reconstructs the final confirmed movements of a missing person.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Last Known Photo', camera: 'Tight 85mm f/1.8 slow push-in on photograph, single warm 3500K desk lamp, dust particles in light' },
      { label: 'The Route', camera: 'Wide 24mm f/2.8 aerial-style of path taken, cold overcast 6500K, desaturated, slow tracking' },
      { label: 'The Last Sighting', camera: 'Medium 50mm f/2.0 security-cam aesthetic, harsh 5000K overhead, green-tinted, timestamp' },
      { label: 'The Gap', camera: 'Extreme close-up 100mm f/2.8 on clock/timeline, single spot 4000K from above in darkness, stillness' },
      { label: 'Still Missing', camera: 'Wide 35mm f/2.8 empty location today, blue-hour 7500K twilight, handheld slow drift, absence as presence' },
    ],
  },
  { id: 'crime_one_clue', name: 'The One Clue', category: 'investigation', niches: ['true_crime'],
    description: 'A single piece of overlooked evidence that cracked or could crack an entire case.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Cold Case', camera: 'Medium 50mm f/2.0 thick case file opening, warm 3500K desk lamp, dust motes, slow reveal' },
      { label: 'Mountains of Evidence', camera: 'Wide 28mm f/4 evidence board with strings and photos, flat 5000K institutional, handheld pan' },
      { label: 'The Overlooked Detail', camera: 'Extreme close-up 100mm f/2.8 macro on the clue, rack focus pulling sharp from blur, dramatic 4000K spot' },
      { label: 'The Connection', camera: 'Tight 85mm f/1.4 hands connecting strings on board, warm 3800K from desk level, building urgency' },
      { label: 'Case Status', camera: 'Static 50mm f/2.0 case file with stamp, single cold overhead 5500K, institutional stillness' },
    ],
  },
  { id: 'crime_72_hours', name: '72-Hour Window', category: 'story', niches: ['true_crime'],
    description: 'The critical first 72 hours of an investigation when evidence is freshest.',
    duration: '30-35s', sceneCount: '6 scenes',
    scenes: [
      { label: 'Hour Zero', camera: 'Wide 24mm f/2.8 crime scene at night, red and blue police flashes mixed with 3000K sodium, chaotic handheld' },
      { label: 'First Responders', camera: 'Medium 50mm f/2.0 documentary-style, harsh 5500K work lights cutting darkness, steam from breath' },
      { label: 'Hour 24 — Canvas', camera: 'Tight 85mm f/1.8 door-to-door interview, warm interior 3500K from behind, face half-lit from porch' },
      { label: 'Hour 48 — Lab', camera: 'Close-up 100mm f/2.8 macro on forensic analysis, cold blue 6500K laboratory, clinical precision' },
      { label: 'Hour 72 — Breakthrough', camera: 'Medium 50mm f/1.4 detective reacting to phone/screen, single warm 4000K key, background blurred' },
      { label: 'The Clock Runs Out', camera: 'Wide 35mm f/2.8 empty interrogation room, flat 5000K overhead, single chair, oppressive stillness' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // SCIENCE / NATURE
  // ════════════════════════════════════════════════════════════════════
  { id: 'science_scale_shift', name: 'Scale Shift', category: 'educational', niches: ['science_nature'],
    description: 'Zooms through orders of magnitude from cosmic to subatomic.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Cosmic Scale', camera: 'Ultra-wide 14mm f/2.8 deep space vastness, cool 8000K starlight, imperceptibly slow zoom-in' },
      { label: 'Planetary Scale', camera: 'Wide 24mm f/4 orbital perspective, golden sunlight 5500K illuminating curved horizon' },
      { label: 'Human Scale', camera: 'Medium 50mm f/2.0 eye level person interacting, natural 5000K daylight, handheld groundedness' },
      { label: 'Microscopic Scale', camera: 'Extreme close-up 100mm f/2.8 macro microscope view, cool blue-white 6500K, razor-thin DOF' },
      { label: 'Mind-Blow Reframe', camera: 'Snap wide 24mm f/2.0 to original cosmic view, warm philosophical 4000K glow, full journey in one frame' },
    ],
  },
  { id: 'science_hidden_clock', name: 'Nature\'s Hidden Clock', category: 'story', niches: ['science_nature'],
    description: 'Reveals a natural process invisible to human perception by compressing time.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'What You See', camera: 'Static 50mm f/4 seemingly still natural scene, bright 5500K natural daylight, everything motionless, locked tripod' },
      { label: 'Time Compressed', camera: 'Same 50mm f/4 framing but timelapse, light shifting 5500K through 3200K golden to 7000K blue hour' },
      { label: 'The Mechanism', camera: 'Tight 85mm f/2.0 isolating biological process, warm 4500K diffused, slow-motion revealing hidden movement' },
      { label: 'Full Perspective', camera: 'Wide 24mm f/2.8 pulling back to ecosystem, golden hour 3200K backlight rim glow, slow contemplative pan' },
    ],
  },
  { id: 'science_impossible_animal', name: 'Impossible Animal', category: 'educational', niches: ['science_nature'],
    description: 'A creature with an ability that seems to violate physics — then the elegant science behind it.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Impossible Feat', camera: 'Wide 24mm f/2.8 animal performing extraordinary ability, bright 5500K daylight, slow-motion frozen spectacle' },
      { label: 'Why It Shouldn\'t Work', camera: 'Medium 50mm f/2.0 diagram comparison, clean 5000K educational, presenter gesturing at inconsistency' },
      { label: 'The Anatomy', camera: 'Extreme close-up 100mm f/2.8 macro on body part enabling ability, warm 4500K specimen lighting, cross-section detail' },
      { label: 'The Science', camera: 'Medium 50mm f/2.0 mechanism in action, bright 5500K balanced, smooth dolly following process' },
      { label: 'Evolution\'s Genius', camera: 'Wide 35mm f/2.0 animal thriving in habitat, golden hour 3200K warmth, slow reverential movement, hero framing' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // RELATIONSHIPS / DATING
  // ════════════════════════════════════════════════════════════════════
  { id: 'relationships_text_decoded', name: 'Text Message Decoded', category: 'educational', niches: ['relationships_dating'],
    description: 'Unpacks what an ambiguous text message actually signals using attachment theory.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Text', camera: 'Extreme close-up 85mm f/1.8 on phone screen, cool 6000K screen glow as sole light, face partially reflected' },
      { label: 'Surface Reading', camera: 'Medium 50mm f/2.0 staring at phone hopeful, warm 4000K lamp from camera-left, shallow depth' },
      { label: 'The Subtext', camera: 'Tight 85mm f/1.4 same screen with analytical overlay, split: cool 6500K screen, warm 3500K room' },
      { label: 'What To Do', camera: 'Direct 50mm f/2.0 to camera, single confident key 4000K at 45 degrees, dark background, honest lean-in' },
    ],
  },
  { id: 'relationships_green_flag', name: 'Green Flag Test', category: 'listicle', niches: ['relationships_dating'],
    description: 'Rapid-fire identification of subtle positive relationship signals most people overlook.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Overlooked Signs', camera: 'Wide 35mm f/2.8 cafe scene with couple in background, warm 4500K ambient, observational documentary angle' },
      { label: 'Green Flag #1', camera: 'Medium close-up 85mm f/1.8 isolating subtle positive gesture, warm 3800K golden hour key, tender' },
      { label: 'Green Flag #2', camera: 'Tight 50mm f/2.0 from different angle capturing another signal, overhead 5000K soft daylight, unposed' },
      { label: 'Green Flag #3', camera: 'Close-up 85mm f/1.4 on hands or body language showing security, warm 3500K backlight halo, intimate detail' },
      { label: 'The Pattern', camera: 'Medium wide 35mm f/2.0 pulling back to full picture, bright 5500K natural light, relaxed genuine interaction' },
    ],
  },
  { id: 'relationships_argument', name: 'Argument Autopsy', category: 'educational', niches: ['relationships_dating'],
    description: 'Dissects the anatomy of a common argument to find the real unspoken need.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Fight', camera: 'Wide 28mm f/2.8 two-shot with distance between subjects, cold 6000K overhead, static tripod capturing gap' },
      { label: 'What Was Said', camera: 'Tight 85mm f/1.4 alternating close-ups, harsh direct 5500K key, unflattering clarity, raw emotion' },
      { label: 'What Was Meant', camera: 'Same 85mm f/1.4 but lighting shifts to warm 3500K side key, softer shadows revealing vulnerability' },
      { label: 'The Real Need', camera: 'Medium 50mm f/2.0 emotional core, single warm 3800K pool of light in dark frame, intimate and bare' },
      { label: 'The Repair', camera: 'Wide 35mm f/2.0 two-shot closer, warm golden 3200K backlight from window, physical reconnection visible' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // HEALTH / FITNESS
  // ════════════════════════════════════════════════════════════════════
  { id: 'health_exercise_myth', name: 'Exercise Myth Kill', category: 'educational', niches: ['health_fitness'],
    description: 'Debunks a widely-believed exercise myth with biomechanics evidence.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Myth', camera: 'Medium 50mm f/2.0 person performing mythical exercise, bright gym 5500K fluorescent, straight-on believable' },
      { label: 'The Science Says No', camera: 'Tight 85mm f/1.8 on joint/muscle under stress, raking 4500K side light, slow-motion, anatomical precision' },
      { label: 'The Correct Form', camera: 'Same 50mm f/2.0 angle but warm 4000K key from camera-left, green tint suggesting approval, smooth tracking' },
      { label: 'Feel The Difference', camera: 'Close-up 85mm f/1.4 on muscle activation, warm 3500K practical light, shallow depth, powerful detail' },
    ],
  },
  { id: 'health_ingredient_expose', name: 'Ingredient Expose', category: 'investigation', niches: ['health_fitness'],
    description: 'Flips a "healthy" product to read the ingredient label and reveals what each chemical does.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Health Halo', camera: 'Clean 50mm f/2.0 commercial-style hero shot, bright 5500K beauty lighting, aspirational packaging' },
      { label: 'Flip the Label', camera: 'Close-up 85mm f/2.0 hand rotating product to show ingredients, transition warm 4500K to cold 6000K' },
      { label: 'Ingredient #1', camera: 'Extreme close-up 100mm f/2.8 macro on specific ingredient text, single sharp 5000K spot, forensic isolation' },
      { label: 'What It Does', camera: 'Medium 50mm f/2.0 showing biological diagram, clean 5500K educational, presenter explaining mechanism' },
      { label: 'The Alternative', camera: 'Wide 35mm f/2.0 whole food alternative in natural kitchen, warm 3500K morning light through window, optimistic' },
    ],
  },
  { id: 'health_30_day', name: '30-Day Snapshot', category: 'story', niches: ['health_fitness'],
    description: 'Compressed 30-day transformation journal hitting the key inflection points.',
    duration: '30-35s', sceneCount: '6 scenes',
    scenes: [
      { label: 'Day 1', camera: 'Static 50mm f/2.8 before baseline, flat 5500K overhead, no flattering angles, honest clinical, locked tripod' },
      { label: 'Day 7 — First Wall', camera: 'Handheld 35mm f/2.8 vlog-style showing struggle, cool 5000K morning, tired eyes, unpolished' },
      { label: 'Day 14 — First Sign', camera: 'Medium 50mm f/2.0 first measurable change, warm 4000K encouraging side light, genuine surprise' },
      { label: 'Day 21 — Momentum', camera: 'Wide 28mm f/2.8 training montage energy, bright 5500K gym, dynamic handheld tracking, building confidence' },
      { label: 'Day 30 — Result', camera: 'Same 50mm f/2.8 locked tripod matching Day 1 framing, same 5500K, visible transformation, comparison space' },
      { label: 'What Changed Inside', camera: 'Tight 85mm f/1.4 direct-to-camera, warm 3500K single key, dark background, honest personal statement' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // GAMING / POP CULTURE
  // ════════════════════════════════════════════════════════════════════
  { id: 'gaming_lore_iceberg', name: 'Lore Iceberg', category: 'educational', niches: ['gaming_popculture'],
    description: 'Descends through layers of a game\'s lore from common knowledge to hidden theories.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Surface Level', camera: 'Bright wide 28mm f/2.8 recognizable game imagery, saturated 5500K, commercial polish, smooth pan' },
      { label: 'Below the Surface', camera: 'Medium 50mm f/2.0 dimming to cooler 5000K, vignette creeping in, focus tightening, slight descent feel' },
      { label: 'Deep Lore', camera: 'Tight 85mm f/1.8 near-darkness, single 3500K warm screen glow, conspiratorial intimacy, extreme shallow depth' },
      { label: 'The Abyss', camera: 'Extreme close-up 100mm f/2.0 barely lit 2800K amber, almost monochrome, grain visible, hidden text emerging' },
      { label: 'Mind Blown', camera: 'Snap wide 24mm f/2.0 sudden full brightness 5500K, revealing full iceberg with all layers visible, overwhelming scale' },
    ],
  },
  { id: 'gaming_dev_secret', name: 'Dev Room Secret', category: 'investigation', niches: ['gaming_popculture'],
    description: 'Reveals a hidden developer room or cut content buried in a game\'s code.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Normal Game', camera: 'Wide 28mm f/2.8 standard gameplay, bright 5500K screen-lit face, casual gaming setup, establishing normalcy' },
      { label: 'The Glitch Path', camera: 'Medium 50mm f/2.0 showing exploit sequence, screen glow shifting colors, excited handheld, curiosity building' },
      { label: 'Through the Wall', camera: 'Tight 85mm f/1.8 on screen showing boundary break, cold 6500K monitor glow only, eerie emptiness, hushed' },
      { label: 'The Discovery', camera: 'Close-up 50mm f/1.4 on screen revealing hidden content, mixed warm 4000K and cool 6000K from monitors' },
      { label: 'Developer Intent', camera: 'Medium 50mm f/2.0 pulling back to full context, warm 4500K ambient, analytical framing, secret understood' },
    ],
  },
  { id: 'gaming_character_psych', name: 'Character Psychology', category: 'educational', niches: ['gaming_popculture'],
    description: 'Applies real psychological frameworks to a beloved character to reveal why they resonate.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Character', camera: 'Wide 35mm f/2.8 hero-shot iconic pose, vibrant 5000K stylized lighting, reverent framing matching source' },
      { label: 'Surface Behavior', camera: 'Medium 50mm f/2.0 recognizable moments, warm 4500K, documentary-style compilation, accessible' },
      { label: 'The Framework', camera: 'Clean 50mm f/2.8 educational framing of psychological model, bright 5500K, split between theory and example' },
      { label: 'The Deep Read', camera: 'Tight 85mm f/1.4 close-up on character\'s eyes/defining feature, warm 3500K dramatic shadow, emotionally penetrating' },
      { label: 'Why We Connect', camera: 'Medium wide 35mm f/2.0 character in most vulnerable moment, warm 3800K golden, universal truth revealed' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // CONSPIRACY / MYSTERY
  // ════════════════════════════════════════════════════════════════════
  { id: 'conspiracy_timeline_glitch', name: 'Timeline Glitch', category: 'investigation', niches: ['conspiracy_mystery'],
    description: 'Exposing contradictions in the official timeline of a suspicious event.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Official Record', camera: 'Locked-off 35mm at eye level, cold fluorescent 5500K overhead, sterile archive framing' },
      { label: 'First Discrepancy', camera: 'Slow push-in 50mm to 65mm, amber desk lamp 3000K from camera-left, Dutch angle 5 degrees' },
      { label: 'The Missing Minutes', camera: 'Tight 85mm close-up on clock/timestamp, strobe flicker 4000K, rack focus from text to redaction marks' },
      { label: 'Cross-Reference', camera: 'Split-diopter 35mm showing two documents in simultaneous focus, green monitor glow 6500K from below' },
      { label: 'The Gap Nobody Explains', camera: 'Ultra-tight 100mm macro on single damning detail, pulsing red accent 2800K from below, everything else black' },
    ],
  },
  { id: 'conspiracy_whistleblower', name: 'The Whistleblower', category: 'story', niches: ['conspiracy_mystery'],
    description: 'One insider breaks silence — their testimony, the risks, and what they revealed.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Insider', camera: 'Silhouette at 50mm f/1.4, single backlight 4500K through venetian blinds creating stripe patterns' },
      { label: 'What They Saw', camera: 'Handheld 35mm POV with motion blur, harsh institutional 5000K overhead, surveillance grain' },
      { label: 'The Decision to Talk', camera: 'Extreme close-up 100mm on hands fidgeting, warm tungsten 3200K desk lamp from camera-right' },
      { label: 'The Testimony', camera: 'Medium close-up 65mm slight low angle, dual rim lights 4000K left and right, face partially shadowed center' },
      { label: 'The Aftermath', camera: 'Wide 24mm pulling back from empty chair, cold blue-shift 7000K wash, slow zoom-out leaving negative space' },
    ],
  },
  { id: 'conspiracy_pattern_decode', name: 'Pattern Decode', category: 'investigation', niches: ['conspiracy_mystery'],
    description: 'Connecting dots across seemingly unrelated events to reveal a hidden pattern.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Coincidences', camera: 'Overhead bird\'s-eye 24mm on scattered documents, warm 3500K desk lamp, flat compositional layout' },
      { label: 'The Thread', camera: 'Tracking dolly at 50mm following red thread across corkboard, pin-spot 4000K lighting each connection' },
      { label: 'The Pattern Emerges', camera: 'Slow zoom-out 85mm to 35mm revealing full conspiracy board, green-tinted 5500K overhead' },
      { label: 'What It Means', camera: 'Direct-to-camera 50mm eye level, single harsh key from above 4500K, interrogation-room intimacy' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // BUSINESS / ENTREPRENEUR
  // ════════════════════════════════════════════════════════════════════
  { id: 'business_cash_machine', name: 'Cash Machine', category: 'strategy', niches: ['business_entrepreneur'],
    description: 'Reverse-engineering a company\'s revenue engine to expose how the money flows.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Revenue Number', camera: 'Clean 50mm locked-off on bold typography showing revenue, crisp 5000K key, corporate-clean negative space' },
      { label: 'Revenue Stream #1', camera: 'Smooth slider left-to-right at 35mm, warm boardroom 4000K, product in foreground with context behind' },
      { label: 'Revenue Stream #2', camera: 'Overhead 24mm workflow visualization, cool tech-blue 5500K, geometric composition' },
      { label: 'The Flywheel', camera: 'Orbital 50mm circling central concept, dynamic 4500K with blue accent rim, interconnected motion' },
      { label: 'The Takeaway', camera: 'Medium close-up 65mm slight low angle, confident warm 3800K key from camera-left, upward trajectory background' },
    ],
  },
  { id: 'business_failure_autopsy', name: 'Failure Autopsy', category: 'cautionary', niches: ['business_entrepreneur'],
    description: 'Dissecting why a promising company died — the mistakes and the lesson.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Promise', camera: 'Bright optimistic 35mm wide, warm golden 3800K flooding frame, polished and aspirational' },
      { label: 'The Warning Signs', camera: 'Medium 50mm subtle Dutch angle 3 degrees, flickering 4500K starting clinical, single shadow creeping' },
      { label: 'The Fatal Mistake', camera: 'Tight 85mm close-up on decision moment, harsh single-source 5000K directly above, deep eye shadows' },
      { label: 'The Collapse', camera: 'Wide 24mm rapidly pulling back, lights dimming to 2800K, empty desks entering frame, desaturation' },
      { label: 'The Lesson', camera: 'Clean 50mm eye level, balanced soft 4200K fill, neutral background, composed reflective, clarity after chaos' },
    ],
  },
  { id: 'business_unfair_advantage', name: 'Unfair Advantage', category: 'strategy', niches: ['business_entrepreneur'],
    description: 'Revealing the hidden competitive moat that makes one business nearly impossible to beat.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Dominant Player', camera: 'Low angle 35mm looking up at imposing architecture, cool steel-blue 5500K, wide establishing scale' },
      { label: 'What Competitors See', camera: 'Medium 50mm from outside looking through glass, warm interior 3800K visible but separated, voyeuristic' },
      { label: 'The Hidden Moat', camera: 'Macro 100mm detail of competitive advantage, dramatic side-light 4000K from camera-right, shallow DOF' },
      { label: 'Why Nobody Can Copy It', camera: 'Steady 65mm medium shot, confident warm 4200K three-point, direct composition suggesting inevitability' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // FOOD / COOKING
  // ════════════════════════════════════════════════════════════════════
  { id: 'food_flavor_bomb', name: 'Flavor Bomb', category: 'educational', niches: ['food_cooking'],
    description: 'Breaking down the science of why one specific dish tastes incredible.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The First Bite', camera: 'Extreme close-up 100mm macro food being bitten, warm 3200K tungsten from camera-left, steam and texture, f/2.8' },
      { label: 'The Chemistry', camera: 'Overhead flat-lay 35mm ingredients separated on marble, bright 5000K diffused top-light, food-magazine composition' },
      { label: 'The Technique', camera: 'Side-profile 50mm cooking action at stovetop, dramatic rim light from flame 2500K, motion blur, smoke and sizzle' },
      { label: 'The Result', camera: 'Hero 85mm beauty shot finished dish on dark slate, golden back-light 3500K creating halo, restaurant precision' },
    ],
  },
  { id: 'food_one_ingredient', name: 'One Ingredient', category: 'educational', niches: ['food_cooking'],
    description: 'Deep dive into a single ingredient — its origin, science, and transformative potential.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Ingredient', camera: 'Rotating 85mm beauty shot on seamless background, soft 4500K diffused light, ingredient on turntable' },
      { label: 'Where It Comes From', camera: 'Wide 24mm establishing origin landscape, golden-hour 3200K natural light, atmospheric depth haze' },
      { label: 'The Science Inside', camera: 'Macro 100mm cross-section detail, clinical 5500K ring light, scientific-illustration framing' },
      { label: 'The Transformation', camera: 'Dynamic 50mm tracking cooking process, warm fire-glow 2800K mixed with 4500K overhead, sizzle and steam' },
      { label: 'The Finished Dish', camera: 'Slow push-in 85mm to 100mm on plated dish, warm candlelight 2700K with diffused fill, fork breaking in' },
    ],
  },
  { id: 'food_chef_secret', name: 'Chef\'s Secret', category: 'educational', niches: ['food_cooking'],
    description: 'One professional cooking technique that transforms home cooking forever.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Amateur Way', camera: 'Overhead 35mm home-kitchen attempt, flat unflattering 5000K ceiling light, messy casual composition' },
      { label: 'What Pros Know', camera: 'Medium 50mm side angle professional technique, warm directional 3800K from window-left, clean workspace' },
      { label: 'The Technique', camera: 'Tight 85mm close-up tracking hands, dramatic side-light 3500K highlighting motion, slow-motion feel, tactile' },
      { label: 'The Difference', camera: 'Split composition 65mm comparing results side-by-side, balanced 4200K neutral, stark visual contrast' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // TRAVEL / ADVENTURE
  // ════════════════════════════════════════════════════════════════════
  { id: 'travel_before_gone', name: 'Before It\'s Gone', category: 'cautionary', niches: ['travel_adventure'],
    description: 'A disappearing destination — climate change or overtourism threatening a place.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Beauty', camera: 'Epic wide 16mm establishing, golden-hour 3200K flooding landscape, sweeping panoramic, maximum grandeur' },
      { label: 'The Threat', camera: 'Slow zoom-in 50mm revealing damage detail, overcast flat 6000K draining warmth, beauty and decay in one frame' },
      { label: 'Then vs Now', camera: 'Locked-off 35mm matched framing for temporal comparison, neutral 5000K daylight, identical composition' },
      { label: 'What\'s Being Lost', camera: 'Intimate 85mm close-up local person or cultural detail, warm 3500K with amber fill, emotional connection' },
      { label: 'The Window Closing', camera: 'Drone-perspective wide 24mm slowly ascending, sunset 2800K fading, destination shrinking, bittersweet' },
    ],
  },
  { id: 'travel_budget_breakdown', name: 'Budget Breakdown', category: 'strategy', niches: ['travel_adventure'],
    description: 'Exactly how much a trip costs — flights, stays, food, transport — with real numbers.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Total Cost', camera: 'Clean 50mm graphic composition with cost figure, bright 5000K modern-tech lighting, bold typographic framing' },
      { label: 'Getting There', camera: 'Wide 24mm window seat POV, cool 6000K ambient with warm cabin accent 3500K, travel-in-motion energy' },
      { label: 'Staying & Eating', camera: 'Montage-style 35mm warm 3800K restaurant/hotel, handheld slight movement, lifestyle authenticity' },
      { label: 'The Verdict', camera: 'Medium 65mm direct framing, balanced warm 4200K, clean background, authoritative value summary' },
    ],
  },
  { id: 'travel_local_knows', name: 'What Locals Know', category: 'story', niches: ['travel_adventure'],
    description: 'Insider spots and secrets that only residents know — skip the tourist traps.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Tourist Version', camera: 'Wide 24mm crowded tourist hotspot, harsh midday 5500K, deliberately unflattering packed composition' },
      { label: 'The Local Spot', camera: 'Intimate 50mm handheld entering hidden alley, warm golden 3200K interior light spilling out, discovery framing' },
      { label: 'The Secret Food', camera: 'Close-up 85mm local dish being prepared, fire-glow 2800K mixed with warm ambient, steam rising, authentic' },
      { label: 'The Real Experience', camera: 'Medium 35mm genuine local interaction, soft natural 4000K window light, candid documentary, unhurried' },
      { label: 'Why It\'s Better', camera: 'Golden-hour 24mm wide of local destination, warm 3000K natural light, empty and serene vs earlier chaos' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PSYCHOLOGY / MIND-BLOWN
  // ════════════════════════════════════════════════════════════════════
  { id: 'psych_dark_pattern', name: 'Dark Pattern', category: 'investigation', niches: ['psychology_mindblown'],
    description: 'Exposing a manipulation technique used on you daily — in ads, apps, or social situations.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'You\'ve Been Manipulated', camera: 'Direct-to-camera 50mm eye level, cold clinical 5500K, confrontational framing breaking fourth wall' },
      { label: 'The Setup', camera: 'Over-shoulder 35mm POV of phone screen, cool blue 6500K screen glow on face, intimate tech-interaction' },
      { label: 'How It Works', camera: 'Diagram-style overhead 24mm flat-lay of mechanism, bright neutral 5000K, technical explainer composition' },
      { label: 'The Psychology Behind It', camera: 'Medium 65mm slow push-in, warm amber 3800K key from camera-left, cerebral depth-of-field' },
      { label: 'How to See Through It', camera: 'Wide 35mm pulling back to reveal full pattern, balanced 4500K, everything visible, empowerment framing' },
    ],
  },
  { id: 'psych_decision_trap', name: 'Decision Trap', category: 'educational', niches: ['psychology_mindblown'],
    description: 'A cognitive bias that hijacks your decisions — how it works and why you fall for it.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Choice', camera: 'Clean 50mm symmetric composition showing two options, balanced 4500K neutral, deliberate equilibrium' },
      { label: 'What Your Brain Does', camera: 'Tight 85mm suggesting internal process, temperature shift from warm 3500K to cool 5500K mid-shot, rack focus' },
      { label: 'The Trap Mechanism', camera: 'Overhead 24mm revealing hidden third element, dramatic single-source 4000K from camera-right, full picture' },
      { label: 'Now You Know', camera: 'Medium 65mm confident level framing, clean warm 4200K fill, direct composition suggesting mastery' },
    ],
  },
  { id: 'psych_body_language', name: 'Body Language Read', category: 'educational', niches: ['psychology_mindblown'],
    description: 'Decoding one specific body language signal — what it really means.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Signal', camera: 'Medium close-up 85mm isolating the gesture, warm 3800K key from 45 degrees camera-left, shallow DOF' },
      { label: 'When People Do It', camera: 'Wide 35mm showing social context, natural 4500K ambient, documentary candid, gesture visible in context' },
      { label: 'What It Really Means', camera: 'Slow push-in 50mm to 65mm, warm cerebral 3500K with blue accent rim, analytical framing' },
      { label: 'The Science', camera: 'Clean 50mm graphic composition with research context, bright clinical 5500K, precise academic framing' },
      { label: 'How to Use It', camera: 'Medium 65mm slight low angle suggesting empowerment, warm confident 4000K three-point, practical framing' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // SPACE / COSMOS
  // ════════════════════════════════════════════════════════════════════
  { id: 'space_cosmic_what_if', name: 'Cosmic What-If', category: 'educational', niches: ['space_cosmos'],
    description: 'A mind-bending hypothetical — what if Earth had two moons, or the sun disappeared?',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Question', camera: 'Wide 16mm night sky establishing, deep blue 7000K ambient with pinpoint star highlights, vast negative space' },
      { label: 'How Things Are Now', camera: 'Grounded 50mm familiar celestial body, warm natural 4500K sunlight, stable composed normalcy' },
      { label: 'The Moment It Changes', camera: 'Dynamic zoom-in 35mm to 50mm with slight shake, rapid temperature shift warm 4000K to alien 6500K' },
      { label: 'The Cascade', camera: 'Wide 24mm chain-reaction consequences, strobing 3000K-7000K, multiple elements collapsing' },
      { label: 'The Final State', camera: 'Slow contemplative 85mm of transformed world, eerie stillness, single dominant color wash, maximum void' },
    ],
  },
  { id: 'space_dark_object', name: 'Dark Object', category: 'investigation', niches: ['space_cosmos'],
    description: 'Profiling one terrifying object in space — black holes, rogue planets, magnetars.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Something\'s Out There', camera: 'Ultra-wide 14mm deep space field, almost entirely black with faint stars, single ominous glow 6000K' },
      { label: 'What We Know', camera: 'Medium 50mm scientific visualization, cold clinical 5500K, data-overlay framing, measured and factual' },
      { label: 'What It Can Do', camera: 'Dynamic 35mm showing power/effect, dramatic rim light 4000K amber against deep blue void, scale comparison' },
      { label: 'How Close It Is', camera: 'Slow zoom-out 85mm to 24mm placing object relative to Earth, warm 4500K Earth-light contrasting cold 7000K' },
      { label: 'Why It Matters', camera: 'Intimate 65mm returning to human scale, warm 3800K grounding light, contemplative, smallness implied' },
    ],
  },
  { id: 'space_time_warp', name: 'Time Warp', category: 'educational', niches: ['space_cosmos'],
    description: 'How time behaves differently across the universe — near black holes, at light speed.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'Time on Earth', camera: 'Grounded 50mm ticking clock, warm familiar 4500K daylight, stable locked-off, comforting normalcy' },
      { label: 'Time Near a Black Hole', camera: 'Wide 24mm gravitational lens distortion, deep amber-red 2500K stretching toward blue-shift 8000K, warped' },
      { label: 'Time at Light Speed', camera: 'Streaking 35mm motion blur tunnel, cold blue-white 6500K with star trails, dynamic forward-rushing' },
      { label: 'What This Means for You', camera: 'Clean 65mm returning to human scale, warm 4000K balanced fill, contemplative, implications settling' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // ANIMALS / WILDLIFE
  // ════════════════════════════════════════════════════════════════════
  { id: 'animals_evolution_hack', name: 'Evolution Hack', category: 'educational', niches: ['animals_wildlife'],
    description: 'How one animal evolved an absurd solution to a survival problem.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Problem', camera: 'Wide 24mm hostile environment, harsh midday 5500K survival pressure, landscape dominating with tiny animal' },
      { label: 'The Failed Approach', camera: 'Medium 50mm predator/competitor failing, neutral 4500K documentary, wildlife photography patience' },
      { label: 'The Weird Solution', camera: 'Close-up 100mm macro bizarre adaptation, dramatic side-light 4000K revealing texture, f/4 detail' },
      { label: 'How It Works', camera: 'Medium 65mm adaptation in action, warm golden-hour 3500K, slow tracking following animal, BBC quality' },
      { label: 'Why It\'s Genius', camera: 'Wide 35mm animal thriving in niche, beautiful 3200K golden light, nature-wins hero framing' },
    ],
  },
  { id: 'animals_size_showdown', name: 'Size Showdown', category: 'educational', niches: ['animals_wildlife'],
    description: 'Comparing insane size differences between animals — smallest to most massive.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Tiny One', camera: 'Extreme macro 100mm making small creature fill frame, bright ring-light 5000K, white seamless, specimen framing' },
      { label: 'Scaling Up', camera: 'Medium 50mm with size reference object, neutral 4500K balanced, clear scale cues' },
      { label: 'The Giant', camera: 'Ultra-wide 14mm low angle looking up, dramatic rim light 3500K from behind, hero-scale framing emphasizing enormity' },
      { label: 'Side by Side', camera: 'Wide 24mm composite-style all sizes simultaneously, clean 5000K neutral, infographic composition, clear scale bars' },
    ],
  },
  { id: 'animals_unlikely_partners', name: 'Unlikely Partners', category: 'story', niches: ['animals_wildlife'],
    description: 'Two species that depend on each other in impossible-seeming ways.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'Species A', camera: 'Portrait-style 85mm first animal in habitat, warm 3800K dappled natural light, individual character' },
      { label: 'Species B', camera: 'Portrait-style 85mm second animal, contrasting cool 5500K habitat, matched composition for visual pairing' },
      { label: 'The Meeting', camera: 'Wide 35mm both species together, golden 3500K natural light, documentary patience, interaction visible' },
      { label: 'How They Help Each Other', camera: 'Close-up 100mm macro symbiotic interaction point, warm 4000K side-light, intimate biological detail' },
      { label: 'Why It Works', camera: 'Wide 24mm pulling back to ecosystem context, beautiful 3200K golden-hour, both thriving, circle-of-life' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // SPORTS / ATHLETES
  // ════════════════════════════════════════════════════════════════════
  { id: 'sports_clutch_moment', name: 'Clutch Moment', category: 'story', niches: ['sports_athletes'],
    description: 'The single play that defined a career — pressure, execution, legacy.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Stakes', camera: 'Wide 24mm establishing arena, dramatic mixed 4500K stadium lighting with crowd atmosphere, epic scale' },
      { label: 'The Pressure', camera: 'Tight 85mm athlete\'s face pre-moment, shallow DOF f/1.8, warm sweat-glistening 3500K, tension in every pixel' },
      { label: 'The Moment', camera: 'Dynamic 35mm tracking action, fast shutter freeze-frame, harsh direct 5000K flash-style, peak-action' },
      { label: 'The Reaction', camera: 'Medium 50mm celebration/emotion, warm golden 3800K with lens flare from stadium lights, raw energy' },
      { label: 'The Legacy', camera: 'Slow contemplative 65mm, warm 4000K retrospective, clean composed, the moment crystallized in memory' },
    ],
  },
  { id: 'sports_training_secret', name: 'Training Secret', category: 'strategy', niches: ['sports_athletes'],
    description: 'The unconventional training method behind an elite athlete\'s dominance.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'The Dominance', camera: 'Wide 24mm competition footage, bright 5000K stadium, athlete clearly ahead, establishing superiority' },
      { label: 'What Nobody Sees', camera: 'Intimate 50mm gym/training facility, warm 3500K tungsten practicals, raw documentary feel, behind-the-scenes' },
      { label: 'The Method', camera: 'Close-up 85mm specific technique or drill, dramatic single-source 4000K from camera-right, isolating detail' },
      { label: 'Why It Works', camera: 'Medium 65mm showing results on field, golden-hour 3200K warm, training-to-performance connection visible' },
    ],
  },
  { id: 'sports_rivalry', name: 'Rivalry Decoded', category: 'story', niches: ['sports_athletes'],
    description: 'What makes a legendary rivalry tick — the psychology, matchups, and moments.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Two Forces', camera: 'Split-frame 35mm both athletes, cool neutral 5000K, balanced symmetrical, equal power' },
      { label: 'Athlete A\'s Edge', camera: 'Medium 50mm favoring first athlete, warm 3800K aggressive, slight low angle conveying strength' },
      { label: 'Athlete B\'s Edge', camera: 'Medium 50mm favoring second athlete, cool 5500K contrasting temperature, matched opposite direction' },
      { label: 'The Defining Clash', camera: 'Dynamic 35mm action, harsh strobe-freeze 5000K, both athletes in frame simultaneously, peak-conflict' },
      { label: 'The Verdict', camera: 'Wide 24mm pulling back for perspective, warm contemplative 4000K, both small in frame, legacy-scale' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // EDUCATION / LEARNING
  // ════════════════════════════════════════════════════════════════════
  { id: 'edu_common_mistake', name: 'Common Mistake', category: 'educational', niches: ['education_learning'],
    description: 'Correcting one widespread misconception that most people believe is true.',
    duration: '25-30s', sceneCount: '4 scenes',
    scenes: [
      { label: 'What Everyone Thinks', camera: 'Clean 50mm warm inviting 4000K, comfortable familiar framing, visual representation of common belief' },
      { label: 'Why It\'s Wrong', camera: 'Slow push-in 50mm to 65mm, light shifting warm 4000K to cooler 5500K, composition subtly destabilizing' },
      { label: 'The Real Answer', camera: 'Bright 35mm wide revealing full picture, crisp 5000K balanced daylight, clean educational framing' },
      { label: 'Why It Matters', camera: 'Medium 65mm direct framing, warm 4200K confident, slightly wider suggesting expanded understanding' },
    ],
  },
  { id: 'edu_in_60_seconds', name: 'Explained in 60 Seconds', category: 'educational', niches: ['education_learning'],
    description: 'One complex concept broken into four crystal-clear steps anyone can follow.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Big Idea', camera: 'Wide 24mm bold visual hook, bright 5000K clean modern, graphic composition with concept space' },
      { label: 'Step One', camera: 'Medium 50mm first-principle framing, warm 4200K with single color accent, clean labeled composition' },
      { label: 'Step Two', camera: 'Medium 50mm matched framing building on previous, slightly different accent color, progressive layering' },
      { label: 'Step Three', camera: 'Medium 50mm completing framework, all layers visible, 4500K balanced, satisfying completeness' },
      { label: 'Now You Get It', camera: 'Clean 65mm pulling all pieces together, bright confident 5000K, slightly wider, mastery-framing' },
    ],
  },
  { id: 'edu_origin_of', name: 'Origin Of', category: 'story', niches: ['education_learning'],
    description: 'The surprising history behind an everyday thing — who invented it and how it changed everything.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Everyday Thing', camera: 'Macro 100mm close-up of familiar object, clean 5000K product-photography, we see it but don\'t think about it' },
      { label: 'Before It Existed', camera: 'Wide 35mm period-appropriate scene, warm 3200K candlelight era feel, historical reconstruction' },
      { label: 'The Inventor', camera: 'Medium 50mm portrait-style in workshop, warm practical 3500K, intimate creative-process framing' },
      { label: 'The Breakthrough', camera: 'Dynamic 35mm moment of invention, dramatic single-source 4000K eureka lighting, energy and discovery' },
      { label: 'How It Changed Everything', camera: 'Wide 24mm modern context with invention everywhere, bright 5000K contemporary, mundane now extraordinary' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════
  // PARANORMAL / UFO
  // ════════════════════════════════════════════════════════════════════
  { id: 'paranormal_government_file', name: 'Government File', category: 'investigation', niches: ['paranormal_ufo'],
    description: 'Walking through a real declassified document about an unexplained encounter.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Document', camera: 'Overhead macro 100mm on aged/stamped paper, warm desk lamp 3000K from camera-left, redaction mark shadows' },
      { label: 'The Incident', camera: 'Wide 24mm recreation of reported event, cold blue-shift 7000K night, distant lights, handheld unsteady' },
      { label: 'The Official Response', camera: 'Medium 50mm institutional framing, harsh fluorescent 5500K, sterile government-office, clinical distance' },
      { label: 'What Was Redacted', camera: 'Extreme close-up 100mm redacted text with fragments visible, green night-vision 5000K undertone' },
      { label: 'Still Unexplained', camera: 'Slow pull-back 35mm to 24mm from document to dark room, fading 3500K desk light, unanswered-question' },
    ],
  },
  { id: 'paranormal_signal', name: 'The Signal', category: 'story', niches: ['paranormal_ufo'],
    description: 'A mysterious signal, transmission, or recording that defies explanation.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Detection', camera: 'Medium 50mm monitoring equipment, cold blue-green 5500K tech glow, late-night skeleton-crew, routine interrupted' },
      { label: 'The Signal', camera: 'Tight 85mm close-up waveform/readout, pulsing amber 3000K from display, rhythmic light suggesting pattern' },
      { label: 'The Analysis', camera: 'Overhead 35mm workspace with printouts, mixed warm desk lamp 3500K and cool monitor 6000K, investigator framing' },
      { label: 'What It Can\'t Be', camera: 'Medium 50mm systematic elimination, clean 5000K neutral, each rejected explanation dismissed' },
      { label: 'What\'s Left', camera: 'Wide 24mm ending on signal source direction, dark sky with single point of origin, cold 7000K void, maximum unsettling' },
    ],
  },
  { id: 'paranormal_mass_sighting', name: 'Mass Sighting', category: 'story', niches: ['paranormal_ufo'],
    description: 'When hundreds of people in the same place at the same time reported seeing the same thing.',
    duration: '30-35s', sceneCount: '5 scenes',
    scenes: [
      { label: 'The Night', camera: 'Wide 16mm establishing location at night, deep blue 7000K ambient, recognizable landmarks, calm before' },
      { label: 'The Sighting', camera: 'Low angle 24mm looking up at sky, warm streetlight 3000K from below contrasting cold void, silhouettes looking up' },
      { label: 'The Witnesses', camera: 'Medium 50mm documentary-style witness framing, warm practical 3500K interior, credibility in numbers' },
      { label: 'The Explanations', camera: 'Clean 35mm neutral composition, balanced 5000K, systematic visual layout of proposed explanations' },
      { label: 'What Remains', camera: 'Return to wide 16mm same location, same night framing, cold 7000K, the sky now feels different' },
    ],
  },
];
