// Shared style presets used by Storyboard, Imagineer, and Turnaround modals
//
// Each style has:
//   value     – API key (matches Imagineer STYLE_ENHANCERS, used as state value)
//   label     – human-readable display name
//   thumb     – thumbnail URL
//   promptText – descriptive text injected into prompts (Storyboard & Turnaround)

// Thumbnail URLs (generated via Seedream v4)
export const T = {
  cinematic: 'https://v3b.fal.media/files/b/0a928438/3YmB8mqvPYXjLkVcJu5_C_7e184560008c472ca9b8779f641c909b.png',
  anime: 'https://v3b.fal.media/files/b/0a928439/4DYodY5XDUMZFlwPDjTAp_91ceab72c33a4a13980e1f32da25fd95.png',
  '3d_animation': 'https://v3b.fal.media/files/b/0a92843a/zNOOlG6yv3o14LJMiq1gR_1d710032d61a429d81ae3f062320c083.png',
  realistic: 'https://v3b.fal.media/files/b/0a92843b/sokoJe-Z5sBzj6R0Xbcci_cb99387fbddb43e498fcb1bbdcc6274e.png',
  noir: 'https://v3b.fal.media/files/b/0a92843c/AsbEaRIhkVOkwgpUN7LjR_bb8957ec20e14abcbbb60223967f9dd3.png',
  watercolor: 'https://v3b.fal.media/files/b/0a92843d/06p5thnNZXJV8PulOdcMx_2b168931d7b7411faa0bed68735ebbbf.png',
  cyberpunk: 'https://v3b.fal.media/files/b/0a92843d/BGZq8m5MkQa_B-bCqk-yB_77404753663a4c3db5712405039e9337.png',
  fantasy: 'https://v3b.fal.media/files/b/0a92843e/tYCcnoZvup8i7oI03Oh2w_de384dd1f94f44d887da737949cbaa4f.png',
  stop_motion: 'https://v3b.fal.media/files/b/0a928443/EK22qFgeprmc7Z_FW6fx9_e273324adb3b4664a560934dbc352a0a.png',
  pixel_art: 'https://v3b.fal.media/files/b/0a928444/e2rvrwLA3ZBUdYISs9eQi_cc566ac0e51f478680a6949952ba8527.png',
  ghibli: 'https://v3b.fal.media/files/b/0a928445/rmzPbRr_VDDrosSAjCFRf_a30a20bb6b204c7fac0a22126049abe4.png',
  oil_painting: 'https://v3b.fal.media/files/b/0a928446/-q1oMZax5mm4VbHm8qRRW_efb561ff83794291a123cd62fa18a5ca.png',
  steampunk: 'https://v3b.fal.media/files/b/0a928447/8eUWStccbwz6a04WVKksC_ee170e46a1cb42fea8957e15c186432c.png',
  vaporwave: 'https://v3b.fal.media/files/b/0a928448/KePW6j40_CMuiu8IYN-04_22ddfd4be24f433d81ce74172775b3b6.png',
  vintage: 'https://v3b.fal.media/files/b/0a928449/RIYKsEPgvqx5Jlc9v1770_260a9b58c0144311babb3818437dc3b9.png',
  comic: 'https://v3b.fal.media/files/b/0a92844a/qazFLaQYdvhv9Os33VQRB_4f9fd64f503944ef8e4b99cb4641c684.png',
  gothic: 'https://v3b.fal.media/files/b/0a92844b/LcyqV5FImljARPnCcJ-YS_edc8019fd35b49c281eab0da97daf68c.png',
  impressionist: 'https://v3b.fal.media/files/b/0a92844c/nORbLMVZAm4fXs79XMHnB_fd9b85ff8e994ea4933c957261832da6.png',
  pop_art: 'https://v3b.fal.media/files/b/0a92844e/pO-wO633aX9zjIex4b_8f_9a5f31c9c34b4dda9443f79818a983f0.png',
  minimalist: 'https://v3b.fal.media/files/b/0a92844e/T2w643BVfV2tH1ciHBIYb_66c3b346bd064731827684357d9dd9a7.png',
  sci_fi: 'https://v3b.fal.media/files/b/0a928450/J11ZEP9YumVVx3p1rbZcK_0f57e510b7c7401497d1cb688ff09d1f.png',
  horror: 'https://v3b.fal.media/files/b/0a928451/vgn1H3EQl73p9VwV7nH_k_d4e8f4a2823a46b88561ce1554d6099f.png',
  neon: 'https://v3b.fal.media/files/b/0a928452/MphHaGCNpHGX7RPNfS5rm_2579fee652dd41dd85ad9da58eab761c.png',
  manga: 'https://v3b.fal.media/files/b/0a928453/RJ4gRxOgZu6swcYCjMGsF_219ef0a8edc049c1af56a577613f1db6.png',
  charcoal: 'https://v3b.fal.media/files/b/0a92845b/l8Ud9mSQlmh9va4Kxzy_s_080cc79165be476d9567fe62dab96180.png',
  art_deco: 'https://v3b.fal.media/files/b/0a92845c/MfwyuQWkKsfi1hTBW8sfr_06411bf6999643eda8c6fefbaca370cd.png',
  surrealist: 'https://v3b.fal.media/files/b/0a92845d/F0cufWrYYVmTBbrWnq6nW_411fa7e6309f4574ae08de92a10e1e2f.png',
  ukiyo_e: 'https://v3b.fal.media/files/b/0a92845f/V5vE1u5tz9JV6Ln1EQLbT_a5032a9062504fc191fbffc742e8584d.png',
  synthwave: 'https://v3b.fal.media/files/b/0a92845f/BQpwMgqtcEJ09j8IBwQMK_e73d86e815eb40c081459b14d6d58727.png',
  cottagecore: 'https://v3b.fal.media/files/b/0a928460/GVEh1hgghm1RlCNppYaXx_44ce9ad0302d4deabc54a1700930e4b2.png',
  tilt_shift: 'https://v3b.fal.media/files/b/0a928461/KlUp2yqcIzZSfsuI-1MLb_7892b1f22baf4d3fbb65a53ec8e44204.png',
  glitch: 'https://v3b.fal.media/files/b/0a928463/VsDPro3E6bYt99VTc_Y0K_1e476cb7b5b64cce97d04764ff7ee6a3.png',
  western: 'https://v3b.fal.media/files/b/0a928467/fPFb_kAs_JSio9wRSKmsa_5cbc69338dd448d9af0b6e89676dbdbc.png',
  golden_hour: 'https://v3b.fal.media/files/b/0a928467/Wb9FY71CF85b3cdZnnxk3_8ad097fb3ef64bc394028d47cc8920d8.png',
  storybook: 'https://v3b.fal.media/files/b/0a928468/JagKbZnYj0sJXkVEINhpk_34a53f9d5f1d4900bf3d26764bea3b90.png',
  drone: 'https://v3b.fal.media/files/b/0a928469/1sPw-Jqv4i9KTCVFJyMOO_e12f137dda274027924320186bbf5493.png',
  dark_academia: 'https://v3b.fal.media/files/b/0a92846b/qlhdh9pHKuSN6BY5X61pk_0dc0438c7816453d880ff40030cb6e94.png',
  solarpunk: 'https://v3b.fal.media/files/b/0a92846c/qb9e1noRXHPyEKeNKKF-M_f92e9c3ceea34d64b73a88db787980db.png',
  fairy_tale: 'https://v3b.fal.media/files/b/0a92846d/Q3ulCHaePSizsulbwO2uw_2921d7025c3c40b29bff562159c18d3d.png',
  lo_fi: 'https://v3b.fal.media/files/b/0a92846d/i1VOXdQHVAeEEbYhAudwJ_551e6896f3d84983a20c88f6e9eb190e.png',
  '2d_animation': 'https://v3b.fal.media/files/b/0a928470/DsFoYkOitNGyEv9OZFqGt_1a1fa5860dfa47198c0881be7a1413f0.png',
  claymation: 'https://v3b.fal.media/files/b/0a928470/8kHaQHQ2qlHNZ1YH1jWdc_b4657450edc041b0a433a766a8f298fb.png',
  pencil: 'https://v3b.fal.media/files/b/0a928471/6mi5OCTTANf3JSyuTMCjP_19fe0968c61c4c3ab3eb4296ab57e275.png',
  stained_glass: 'https://v3b.fal.media/files/b/0a928472/SOy4ICI7j0Y2oSntwUUdl_9b65dacc6303401cacaa00eb2337a3e6.png',
  vhs: 'https://v3b.fal.media/files/b/0a928474/fVVkWqt4iNzplL3UjXLK5_e5232b6b8bd94f238758e0f72d3a4848.png',
  dreamcore: 'https://v3b.fal.media/files/b/0a928475/NkcdrNQFormwSq9qVUAvl_5cc8d778132c43469fb38fb3bc033b1e.png',
  space_opera: 'https://v3b.fal.media/files/b/0a928476/32Sd90me_LyAVh8PicAKi_1c57ce6d1e6b419b93a3c8c9082aaed4.png',
  fashion: 'https://v3b.fal.media/files/b/0a928477/cjpXmPuXgkvJYR120msMW_b383b32b948a488880cd9961df40c4bf.png',
  kids_educational: 'https://v3b.fal.media/files/b/0a929018/ZArkWRP0IyTCSVkAUo9jH_94e598bc38e34fc4a43ae6d6670836b9.png',
  flat_vector_kids: 'https://v3b.fal.media/files/b/0a929019/XKUeY0F_asadSw7wMm7lq_b5cff714fe274b4a9a9cd3437b262cef.png',
  puppet_show: 'https://v3b.fal.media/files/b/0a92901a/F8bC9ZGuqw-yBJcHdRPJS_c262cc51ae86430b9283381d51b8de34.png',
  whiteboard: 'https://v3b.fal.media/files/b/0a92901b/ubTRBU1HaMVBTLUjUJo-n_cfd13a3c79574eeb98ce1cd2f2e8f2a2.png',
  preschool_cartoon: 'https://v3b.fal.media/files/b/0a92901d/KAP0PAAJwcr6_rkQwsBVG_9f42dc5333a04de6bfc78357aacf450d.png',
  paper_craft: 'https://v3b.fal.media/files/b/0a92901e/Oc-ZCsF0lqnSp41qUDU8D_06abc59a57964188b366cc5c106075ba.png',
  kawaii: 'https://v3b.fal.media/files/b/0a92901f/h_4paBuko6GNU-aQld2pp_16345c8f85844c54a43c059d1bfe21f2.png',
  kids_action: 'https://v3b.fal.media/files/b/0a929020/ZauLYSoSezyq6RS4jw1FV_5c3957fee62a45068895c1f56e7c1950.png',
  kids_bluey: 'https://v3b.fal.media/files/b/0a929058/zZzIIkWi60ifFxyZuniMu_05d462f9061e48759f60de46cd343dbb.png',
  kids_family: 'https://v3b.fal.media/files/b/0a929059/YwvxcCNyKNG3WCchSKMWy_d2dee87e54114f8ca9a3852ec60a8983.png',
  kids_city: 'https://v3b.fal.media/files/b/0a929059/2Tkm_Fb_FbXBBUZPThVjt_60a0b1e616664076a8d7c528c13d7f25.png',
  kids_school: 'https://v3b.fal.media/files/b/0a92905a/F9Uj1Ky7Z14whoMRSc5VT_3ad4e307e872402c9fc3d33353b72f4b.png',
  kids_garden: 'https://v3b.fal.media/files/b/0a92905c/Y9uEjZEi1JToXDUR3UU-S_0dde2753a7fb405da3f8027d2d5dade6.png',
  kids_tea_party: 'https://v3b.fal.media/files/b/0a92905d/D5g2lhOFT4-hoP_o3Zfr3_87aa54698f544eb688bcf694cc81ca42.png',
  kids_maker: 'https://v3b.fal.media/files/b/0a92905d/1XtzR43bVpx82g4_gVOZL_3edfaafd9acf48b8a9074b7110955ae4.png',
  kids_space: 'https://v3b.fal.media/files/b/0a92905e/nmKmls__ismQketK_Vca7_41d50d339b21482090bc5d19ca81ae48.png',
  puffin_island: 'https://v3b.fal.media/files/b/0a929076/dFPveIpLLDrkNYYXile3q_a183311198cd4f379b17a1c5083057bb.png',
  woodland_nature: 'https://v3b.fal.media/files/b/0a929077/p5HFcjwpI6Mppw5azC5qo_cb295f7ba9454ea3a26ab1028a4cce74.png',
  meadow_gentle: 'https://v3b.fal.media/files/b/0a929078/0Wn5__4-QkMJteUNBhJx8_c8dd34b108434d529434319d22ac8db7.png',
  ocean_gentle: 'https://v3b.fal.media/files/b/0a929079/jTd9vpR21wpz_aNqRrbdP_aedc025c4db44453a71aeac5a8f0a90e.png',
  kids_3d_pixar: 'https://v3b.fal.media/files/b/0a9290c4/w2WmoFGOgZYx5kbMgr8vA_c2a30d742bcc48a093321bb26c67826c.png',
  simpsons: 'https://v3b.fal.media/files/b/0a9290c5/ZBcLaNjaM6VXzzq3qQuI8_b053fa9bafe64b6da6adb23f0da42b22.png',
  kids_3d_characters: 'https://v3b.fal.media/files/b/0a9290c5/ITX1keaknR0RKAWKO90ES_46be17d7478f48f9865f4aac59de0a7c.png',
  candy_city_3d: 'https://v3b.fal.media/files/b/0a9290c6/KGeampOKE6t3m5OyNCXZj_11b1f5115eaf48d2a220b0ba5e5fc6f0.png',
  family_guy: 'https://v3b.fal.media/files/b/0a929179/dokf9Xg85DdDQ9S5vLxRQ_529313acb6024f88ae80b5387a255bcc.png',
};

// Unified style categories combining Storyboard, Imagineer, and Turnaround presets
// value = Imagineer API key, promptText = descriptive text for Storyboard/Turnaround prompts
export const STYLE_CATEGORIES = [
  { label: 'UGC & Social Media', styles: [
    { value: 'iphone-selfie', label: 'iPhone Selfie', thumb: T.realistic, promptText: 'iPhone selfie, raw authentic photo' },
    { value: 'ugc-testimonial', label: 'UGC Testimonial', thumb: T.realistic, promptText: 'UGC testimonial style, authentic user content' },
    { value: 'tiktok-style', label: 'TikTok/Reels', thumb: T.realistic, promptText: 'TikTok/Reels style photo, trendy social media' },
    { value: 'instagram-candid', label: 'Instagram Candid', thumb: T.golden_hour, promptText: 'Instagram candid photo, natural lighting' },
    { value: 'facetime-screenshot', label: 'FaceTime Screenshot', thumb: T.realistic, promptText: 'FaceTime screenshot, video call aesthetic' },
    { value: 'mirror-selfie', label: 'Mirror Selfie', thumb: T.realistic, promptText: 'mirror selfie, casual authentic' },
    { value: 'car-selfie', label: 'Car Selfie', thumb: T.realistic, promptText: 'car selfie, natural daylight' },
    { value: 'gym-selfie', label: 'Gym Selfie', thumb: T.realistic, promptText: 'gym selfie, fitness aesthetic' },
    { value: 'golden-hour-selfie', label: 'Golden Hour Selfie', thumb: T.golden_hour, promptText: 'golden hour selfie, warm natural light' },
    { value: 'casual-snapshot', label: 'Casual Snapshot', thumb: T.realistic, promptText: 'casual snapshot, everyday photography' },
  ]},
  { label: 'Photography', styles: [
    { value: 'photorealistic', label: 'Photorealistic', thumb: T.realistic, promptText: 'photorealistic' },
    { value: 'hyperrealistic', label: 'Hyperrealistic', thumb: T.realistic, promptText: 'hyper-realistic' },
    { value: 'cinematic', label: 'Cinematic', thumb: T.cinematic, promptText: 'cinematic' },
    { value: 'documentary', label: 'Documentary', thumb: T.realistic, promptText: 'documentary' },
    { value: 'fashion-photography', label: 'Fashion Photography', thumb: T.fashion, promptText: 'fashion editorial' },
    { value: 'portrait-photography', label: 'Portrait Photography', thumb: T.realistic, promptText: 'portrait photography' },
    { value: 'product-photography', label: 'Product Photography', thumb: T.realistic, promptText: 'product photography, studio lighting' },
    { value: 'street-photography', label: 'Street Photography', thumb: T.realistic, promptText: 'street photography' },
    { value: 'macro-photography', label: 'Macro Photography', thumb: T.realistic, promptText: 'macro photography, extreme close-up detail' },
    { value: 'film-grain', label: 'Film Grain/Analog', thumb: T.vintage, promptText: 'film grain, analog photography' },
    { value: 'polaroid', label: 'Polaroid', thumb: T.vintage, promptText: 'polaroid photo, instant film' },
    { value: 'golden-hour', label: 'Golden Hour', thumb: T.golden_hour, promptText: 'golden hour' },
    { value: 'drone-aerial', label: 'Drone Aerial', thumb: T.drone, promptText: 'drone aerial' },
  ]},
  { label: 'Cinematic', styles: [
    { value: 'cinematic-noir', label: 'Cinematic Noir', thumb: T.noir, promptText: 'cinematic noir' },
    { value: 'cinematic-epic', label: 'Cinematic Epic', thumb: T.cinematic, promptText: 'cinematic epic' },
    { value: 'cinematic-intimate', label: 'Cinematic Intimate', thumb: T.lo_fi, promptText: 'cinematic intimate' },
  ]},
  { label: 'Animation', styles: [
    { value: 'anime', label: 'Anime', thumb: T.anime, promptText: 'anime' },
    { value: '3d-render', label: '3D Animation', thumb: T['3d_animation'], promptText: '3D animation' },
    { value: '2d-animation', label: '2D Animation', thumb: T['2d_animation'], promptText: '2D animation' },
    { value: 'stop-motion', label: 'Stop Motion', thumb: T.stop_motion, promptText: 'stop motion' },
    { value: 'claymation', label: 'Claymation', thumb: T.claymation, promptText: 'claymation' },
    { value: 'pixel-art', label: 'Pixel Art', thumb: T.pixel_art, promptText: 'pixel art' },
    { value: 'ghibli', label: 'Studio Ghibli', thumb: T.ghibli, promptText: 'studio ghibli' },
    { value: 'disney', label: 'Disney Pixar', thumb: T['3d_animation'], promptText: 'disney pixar' },
    { value: 'cartoon', label: 'Cartoon', thumb: T['2d_animation'], promptText: 'cartoon' },
    { value: '8-bit', label: '8-bit Retro', thumb: T.pixel_art, promptText: '8-bit retro pixel art' },
    { value: 'manga', label: 'Manga', thumb: T.manga, promptText: 'manga' },
    { value: 'comic-book', label: 'Comic Book', thumb: T.comic, promptText: 'comic book' },
    { value: 'pixar', label: 'Pixar 3D', thumb: T.kids_3d_pixar, promptText: 'Pixar 3D animation' },
  ]},
  { label: 'Painting', styles: [
    { value: 'oil-painting', label: 'Oil Painting', thumb: T.oil_painting, promptText: 'oil painting' },
    { value: 'watercolor', label: 'Watercolor', thumb: T.watercolor, promptText: 'watercolor' },
    { value: 'acrylic', label: 'Acrylic Painting', thumb: T.oil_painting, promptText: 'acrylic painting' },
    { value: 'gouache', label: 'Gouache', thumb: T.watercolor, promptText: 'gouache painting' },
    { value: 'pastel', label: 'Pastel Drawing', thumb: T.watercolor, promptText: 'pastel drawing' },
    { value: 'charcoal', label: 'Charcoal Drawing', thumb: T.charcoal, promptText: 'charcoal sketch' },
    { value: 'pencil-sketch', label: 'Pencil Sketch', thumb: T.pencil, promptText: 'pencil drawing' },
    { value: 'ink-wash', label: 'Ink Wash', thumb: T.charcoal, promptText: 'ink wash painting' },
    { value: 'impasto', label: 'Impasto', thumb: T.oil_painting, promptText: 'impasto thick paint texture' },
  ]},
  { label: 'Art Movements', styles: [
    { value: 'impressionism', label: 'Impressionist', thumb: T.impressionist, promptText: 'impressionist' },
    { value: 'expressionism', label: 'Expressionism', thumb: T.impressionist, promptText: 'expressionism' },
    { value: 'surrealism', label: 'Surrealist', thumb: T.surrealist, promptText: 'surrealist' },
    { value: 'cubism', label: 'Cubism', thumb: T.pop_art, promptText: 'cubism' },
    { value: 'art-nouveau', label: 'Art Nouveau', thumb: T.art_deco, promptText: 'art nouveau' },
    { value: 'art-deco', label: 'Art Deco', thumb: T.art_deco, promptText: 'art deco' },
    { value: 'baroque', label: 'Baroque', thumb: T.oil_painting, promptText: 'baroque' },
    { value: 'renaissance', label: 'Renaissance', thumb: T.oil_painting, promptText: 'renaissance' },
    { value: 'pop-art', label: 'Pop Art', thumb: T.pop_art, promptText: 'pop art' },
    { value: 'abstract', label: 'Abstract', thumb: T.minimalist, promptText: 'abstract' },
    { value: 'minimalist', label: 'Minimalist', thumb: T.minimalist, promptText: 'minimalist' },
    { value: 'brutalist', label: 'Brutalist', thumb: T.minimalist, promptText: 'brutalist' },
    { value: 'ukiyo-e', label: 'Ukiyo-e', thumb: T.ukiyo_e, promptText: 'ukiyo-e' },
    { value: 'stained-glass', label: 'Stained Glass', thumb: T.stained_glass, promptText: 'stained glass' },
  ]},
  { label: 'Digital & Modern', styles: [
    { value: 'digital-art', label: 'Digital Art', thumb: T.cyberpunk, promptText: 'digital art' },
    { value: 'cgi', label: 'CGI/VFX', thumb: T['3d_animation'], promptText: 'CGI VFX' },
    { value: 'concept-art', label: 'Concept Art', thumb: T.fantasy, promptText: 'concept art' },
    { value: 'matte-painting', label: 'Matte Painting', thumb: T.fantasy, promptText: 'matte painting' },
    { value: 'vaporwave', label: 'Vaporwave', thumb: T.vaporwave, promptText: 'vaporwave' },
    { value: 'synthwave', label: 'Synthwave', thumb: T.synthwave, promptText: 'synthwave' },
    { value: 'cyberpunk', label: 'Cyberpunk', thumb: T.cyberpunk, promptText: 'cyberpunk' },
    { value: 'steampunk', label: 'Steampunk', thumb: T.steampunk, promptText: 'steampunk' },
    { value: 'dieselpunk', label: 'Dieselpunk', thumb: T.steampunk, promptText: 'dieselpunk' },
    { value: 'glitch-art', label: 'Glitch Art', thumb: T.glitch, promptText: 'glitch art' },
    { value: 'low-poly', label: 'Low Poly', thumb: T.pixel_art, promptText: 'low poly 3D' },
    { value: 'isometric', label: 'Isometric', thumb: T.pixel_art, promptText: 'isometric' },
    { value: 'neon', label: 'Neon', thumb: T.neon, promptText: 'neon' },
    { value: 'neon-noir', label: 'Neon Noir', thumb: T.neon, promptText: 'neon noir' },
  ]},
  { label: 'Genre', styles: [
    { value: 'noir', label: 'Noir', thumb: T.noir, promptText: 'noir' },
    { value: 'gothic', label: 'Gothic', thumb: T.gothic, promptText: 'gothic' },
    { value: 'solarpunk', label: 'Solarpunk', thumb: T.solarpunk, promptText: 'solarpunk' },
    { value: 'lo-fi', label: 'Lo-Fi', thumb: T.lo_fi, promptText: 'lo-fi' },
    { value: 'fantasy-art', label: 'Fantasy', thumb: T.fantasy, promptText: 'fantasy' },
    { value: 'dark-fantasy', label: 'Dark Fantasy', thumb: T.gothic, promptText: 'dark fantasy' },
    { value: 'fairy-tale', label: 'Fairy Tale', thumb: T.fairy_tale, promptText: 'fairy tale' },
    { value: 'sci-fi-art', label: 'Sci-Fi', thumb: T.sci_fi, promptText: 'sci-fi' },
    { value: 'space-opera', label: 'Space Opera', thumb: T.space_opera, promptText: 'space opera' },
    { value: 'horror', label: 'Horror', thumb: T.horror, promptText: 'horror' },
    { value: 'western', label: 'Western', thumb: T.western, promptText: 'western' },
  ]},
  { label: 'Period / Aesthetic', styles: [
    { value: 'vintage', label: 'Vintage', thumb: T.vintage, promptText: 'vintage' },
    { value: 'vintage-8mm', label: 'Vintage 8mm', thumb: T.vintage, promptText: 'vintage 8mm film' },
    { value: '1980s-vhs', label: '1980s VHS', thumb: T.vhs, promptText: '1980s VHS' },
    { value: 'pastel-dreamcore', label: 'Pastel Dreamcore', thumb: T.dreamcore, promptText: 'pastel dreamcore' },
    { value: 'cottagecore', label: 'Cottagecore', thumb: T.cottagecore, promptText: 'cottagecore' },
    { value: 'dark-academia', label: 'Dark Academia', thumb: T.dark_academia, promptText: 'dark academia' },
    { value: 'vintage-poster', label: 'Vintage Poster', thumb: T.vintage, promptText: 'vintage poster' },
    { value: 'propaganda-poster', label: 'Propaganda Poster', thumb: T.vintage, promptText: 'propaganda poster' },
  ]},
  { label: 'Techniques', styles: [
    { value: 'tilt-shift', label: 'Tilt-Shift', thumb: T.tilt_shift, promptText: 'tilt-shift miniature' },
  ]},
  { label: 'Specialized', styles: [
    { value: 'storybook', label: 'Storybook', thumb: T.storybook, promptText: "children's storybook" },
    { value: 'chinese-ink', label: 'Chinese Ink', thumb: T.ukiyo_e, promptText: 'Chinese ink painting' },
  ]},
  { label: 'Kids & Education', styles: [
    { value: 'kids-educational', label: 'Kids Educational', thumb: T.kids_educational, promptText: 'kids educational cartoon' },
    { value: 'flat-vector-kids', label: 'Flat Vector Kids', thumb: T.flat_vector_kids, promptText: 'flat vector kids illustration' },
    { value: 'preschool-cartoon', label: 'Preschool Cartoon', thumb: T.preschool_cartoon, promptText: 'preschool cartoon' },
    { value: 'bluey-style', label: 'Bluey Style', thumb: T.kids_bluey, promptText: 'soft 2D kids cartoon, thin clean outlines, pastel flat colors, rounded friendly characters, Bluey style animation' },
    { value: 'kids-family', label: 'Family Cartoon', thumb: T.kids_family, promptText: 'warm family cartoon, thin outlines, soft flat colors, rounded characters, gentle 2D animation, suburban setting' },
    { value: 'kids-city', label: 'Kids City', thumb: T.kids_city, promptText: 'friendly 2D cartoon, thin clean outlines, vibrant flat colors, simple shapes, modern kids TV animation' },
    { value: 'kids-school', label: 'Kids School', thumb: T.kids_school, promptText: 'soft educational cartoon, thin outlines, gentle flat colors, rounded shapes, warm 2D animation, Hey Duggee style' },
    { value: 'kids-garden', label: 'Whimsical Garden', thumb: T.kids_garden, promptText: 'whimsical garden cartoon, thin delicate outlines, soft watercolor-like flat colors, dreamy 2D animation, Sarah and Duck style' },
    { value: 'kids-tea-party', label: 'Cozy Cartoon', thumb: T.kids_tea_party, promptText: 'cozy cartoon, soft rounded shapes, thin clean lines, warm gentle colors, Peppa Pig style 2D animation' },
    { value: 'kids-maker', label: 'Edu Maker', thumb: T.kids_maker, promptText: 'educational maker cartoon, clean thin outlines, bright soft flat colors, simple geometric shapes, Numberblocks style' },
    { value: 'kids-space', label: 'Kids Space', thumb: T.kids_space, promptText: 'gentle space cartoon, thin outlines, vibrant soft flat colors, rounded friendly shapes, Puffin Rock style 2D animation' },
    { value: 'puppet-show', label: 'Puppet Show', thumb: T.puppet_show, promptText: 'puppet show' },
    { value: 'whiteboard-animation', label: 'Whiteboard', thumb: T.whiteboard, promptText: 'whiteboard animation' },
    { value: 'paper-craft', label: 'Paper Craft', thumb: T.paper_craft, promptText: 'paper craft collage' },
    { value: 'kawaii', label: 'Kawaii', thumb: T.kawaii, promptText: 'kawaii' },
    { value: 'kids-action', label: 'Kids Action', thumb: T.kids_action, promptText: 'kids action cartoon' },
    { value: 'puffin-rock', label: 'Puffin Rock', thumb: T.puffin_island, promptText: 'soft textured nature illustration, muted warm earthy tones, gentle organic shapes, wildflowers, Puffin Rock animation style, delicate 2D' },
    { value: 'woodland-nature', label: 'Woodland Nature', thumb: T.woodland_nature, promptText: 'woodland nature illustration, soft textured 2D, muted warm colors, gentle brushstroke textures, organic shapes, autumn leaves and mushrooms' },
    { value: 'meadow-gentle', label: 'Gentle Meadow', thumb: T.meadow_gentle, promptText: 'gentle meadow illustration, soft muted watercolor textures, warm golden light, delicate thin lines, nature illustration, calming earthy palette' },
    { value: 'ocean-gentle', label: 'Gentle Ocean', thumb: T.ocean_gentle, promptText: "soft textured underwater illustration, muted pastel ocean colors, gentle organic shapes, coral reef, calming children's nature animation" },
    { value: 'kids-3d-pixar', label: '3D Kids Pixar', thumb: T.kids_3d_pixar, promptText: '3D rendered kids animation, soft warm lighting, cute rounded characters, Pixar Cocomelon style, smooth subsurface shading' },
    { value: 'simpsons-style', label: 'Simpsons Style', thumb: T.simpsons, promptText: 'classic American adult animated sitcom, yellow skin characters, simple flat colors, Simpsons style animation' },
    { value: '3d-character-art', label: '3D Character Art', thumb: T.kids_3d_characters, promptText: 'stylized 3D character design, big expressive eyes, detailed outfits, colorful panel backgrounds, modern 3D kids character art' },
    { value: 'candy-city-3d', label: 'Candy City 3D', thumb: T.candy_city_3d, promptText: 'whimsical 3D candy-colored city, pastel buildings, pink puffy clouds, toylike vibrant world, playful 3D animation' },
    { value: 'family-guy-style', label: 'Adult Sitcom', thumb: T.family_guy, promptText: 'adult animated sitcom style, thin clean outlines, flat simple colors, round soft character design, casual everyday scene, muted warm palette, American cartoon comedy' },
    { value: 'motion-graphics', label: 'Motion Graphics', thumb: T.minimalist, promptText: 'motion graphics, clean geometric shapes' },
  ]},
];

// Helper: find a style object by its value key
export function findStyleByValue(value) {
  for (const cat of STYLE_CATEGORIES) {
    const found = cat.styles.find(s => s.value === value);
    if (found) return found;
  }
  return null;
}

// Helper: get promptText for a value (falls back to value itself)
export function getPromptText(value) {
  const style = findStyleByValue(value);
  return style ? style.promptText : value;
}
