/**
 * Video Style Frameworks — structural templates for Shorts videos.
 * Defines scene count, durations, beats, TTS mode, transitions, overlays,
 * and music config for each content archetype.
 *
 * Coexists with videoStylePresets.js (motion/cinematography) and
 * visualStyles.js (image generation styles). These are separate systems.
 */

export const VIDEO_STYLE_FRAMEWORKS = {
  personal_journey: {
    id: 'personal_journey',
    name: 'Personal Journey',
    category: 'story',
    description: 'First-person narrative arc following a transformative experience with emotional beats.',
    thumb: '/assets/frameworks/personal-journey.jpg',
    hookExamples: [
      'How I went from [A] to [B]',
      'What [experience] taught me about [lesson]',
      'The moment everything changed for me',
    ],
    supportedDurations: [60, 90],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'cinematic',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: true,
    ttsMode: 'single',
    transitionType: 'crossfade',
    transitionDuration: 1.5,
    textOverlays: 'optional',
    overlayStyle: null,
    musicVolume: 0.20,
    musicMood: 'Ambient/emotional',
    ttsPacing: 'Slow, reflective, conversational',
    sceneStructure: {
      60: [
        { label: 'Setup', beat: 'setup', durationRange: [10, 12], overlayText: null },
        { label: 'Inciting moment', beat: 'tension', durationRange: [10, 12], overlayText: null },
        { label: 'Struggle', beat: 'middle', durationRange: [10, 14], overlayText: null },
        { label: 'Turning point', beat: 'breakthrough', durationRange: [10, 12], overlayText: null },
        { label: 'Resolution', beat: 'payoff', durationRange: [10, 12], overlayText: null },
      ],
      90: [
        { label: 'Setup', beat: 'setup', durationRange: [10, 12], overlayText: null },
        { label: 'Inciting moment', beat: 'tension', durationRange: [10, 12], overlayText: null },
        { label: 'Struggle', beat: 'middle', durationRange: [10, 14], overlayText: null },
        { label: 'Turning point', beat: 'breakthrough', durationRange: [10, 12], overlayText: null },
        { label: 'Resolution', beat: 'payoff', durationRange: [10, 12], overlayText: null },
        { label: 'Reflection', beat: 'reflection', durationRange: [10, 12], overlayText: null },
        { label: 'Call to meaning', beat: 'close', durationRange: [8, 10], overlayText: null },
      ],
    },
  },

  origin_story: {
    id: 'origin_story',
    name: 'Origin Story',
    category: 'story',
    description: 'The humble beginnings and rise of a brand, person, or idea — told with building energy.',
    thumb: '/assets/frameworks/origin-story.jpg',
    hookExamples: [
      'How [brand/person/thing] started in a [humble place]',
      'The real story behind [X]',
      'From [nothing] to [something] - the [X] story',
    ],
    supportedDurations: [60, 90],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'documentary',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: true,
    ttsMode: 'single',
    transitionType: 'crossfade',
    transitionDuration: 1.5,
    textOverlays: 'optional',
    overlayStyle: 'labeled',
    musicVolume: 0.22,
    musicMood: 'Inspirational build, starts quiet, peaks at scene 4-5',
    ttsPacing: 'Storytelling tone, builds energy over time',
    sceneStructure: {
      60: [
        { label: 'The humble beginning', beat: 'setup', durationRange: [10, 12], overlayText: null },
        { label: 'The spark', beat: 'catalyst', durationRange: [10, 12], overlayText: null },
        { label: 'Early struggles', beat: 'conflict', durationRange: [10, 14], overlayText: null },
        { label: 'The break', beat: 'breakthrough', durationRange: [10, 12], overlayText: null },
        { label: 'Where they are now', beat: 'payoff', durationRange: [10, 12], overlayText: null },
      ],
      90: [
        { label: 'The humble beginning', beat: 'setup', durationRange: [10, 12], overlayText: null },
        { label: 'The spark', beat: 'catalyst', durationRange: [10, 12], overlayText: null },
        { label: 'Early struggles', beat: 'conflict', durationRange: [10, 14], overlayText: null },
        { label: 'The break', beat: 'breakthrough', durationRange: [10, 12], overlayText: null },
        { label: 'Where they are now', beat: 'payoff', durationRange: [10, 12], overlayText: null },
        { label: 'Behind the scenes', beat: 'depth', durationRange: [10, 12], overlayText: null },
        { label: 'Legacy/future', beat: 'close', durationRange: [8, 10], overlayText: null },
      ],
    },
  },

  mini_documentary: {
    id: 'mini_documentary',
    name: 'Mini Documentary',
    category: 'story',
    description: 'Authoritative deep-dive into a subject with cold open hook and measured narrative pacing.',
    thumb: '/assets/frameworks/mini-documentary.jpg',
    hookExamples: [
      'The untold story of [X]',
      'Inside [X]: what really happens',
      'The hidden world of [X]',
    ],
    supportedDurations: [60, 90],
    defaults: {
      visualStyle: 'documentary',
      videoStylePreset: 'documentary',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: true,
    ttsMode: 'single',
    transitionType: 'crossfade',
    transitionDuration: 1.0,
    textOverlays: 'optional',
    overlayStyle: 'labeled',
    musicVolume: 0.17,
    musicMood: 'Cinematic underscore',
    ttsPacing: 'Authoritative, measured, documentary narrator',
    sceneStructure: {
      60: [
        { label: 'Cold open', beat: 'hook', durationRange: [8, 10], overlayText: null },
        { label: 'Context', beat: 'setup', durationRange: [10, 12], overlayText: null },
        { label: 'Deep dive', beat: 'core', durationRange: [12, 14], overlayText: null },
        { label: 'Complication', beat: 'tension', durationRange: [10, 12], overlayText: null },
        { label: 'Resolution/insight', beat: 'payoff', durationRange: [10, 12], overlayText: null },
      ],
      90: [
        { label: 'Cold open', beat: 'hook', durationRange: [8, 10], overlayText: null },
        { label: 'Context', beat: 'setup', durationRange: [10, 12], overlayText: null },
        { label: 'Deep dive', beat: 'core', durationRange: [12, 14], overlayText: null },
        { label: 'Complication', beat: 'tension', durationRange: [10, 12], overlayText: null },
        { label: 'Resolution/insight', beat: 'payoff', durationRange: [10, 12], overlayText: null },
        { label: 'Wider implications', beat: 'expansion', durationRange: [10, 12], overlayText: null },
        { label: 'Closing thought', beat: 'close', durationRange: [8, 10], overlayText: null },
      ],
    },
  },

  day_in_the_life: {
    id: 'day_in_the_life',
    name: 'Day in the Life',
    category: 'story',
    description: 'Casual first-person walkthrough of a typical day with timestamp anchors and vlog energy.',
    thumb: '/assets/frameworks/day-in-the-life.jpg',
    hookExamples: [
      'A day in the life of a [profession]',
      '24 hours as a [role] in [place]',
      "What it's actually like to [do X]",
    ],
    supportedDurations: [45, 60],
    defaults: {
      visualStyle: 'photorealistic',
      videoStylePreset: 'vlog_bts',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: true,
    ttsMode: 'single',
    transitionType: 'crossfade',
    transitionDuration: 1.0,
    textOverlays: 'required',
    overlayStyle: 'timestamps',
    musicVolume: 0.20,
    musicMood: 'Lo-fi/chill, continuous',
    ttsPacing: 'Casual, warm, first-person feel',
    sceneStructure: {
      45: [
        { label: 'Morning', beat: 'setup', durationRange: [10, 12], overlayText: '6:00 AM' },
        { label: 'Core work', beat: 'core', durationRange: [10, 12], overlayText: '10:30 AM' },
        { label: 'Unexpected moment', beat: 'surprise', durationRange: [10, 12], overlayText: '2:30 PM' },
        { label: 'Wind down', beat: 'close', durationRange: [10, 12], overlayText: '7:00 PM' },
      ],
      60: [
        { label: 'Morning', beat: 'setup', durationRange: [10, 12], overlayText: '6:00 AM' },
        { label: 'Core work', beat: 'core', durationRange: [10, 12], overlayText: '10:30 AM' },
        { label: 'Unexpected moment', beat: 'surprise', durationRange: [10, 12], overlayText: '2:30 PM' },
        { label: 'Wind down', beat: 'close', durationRange: [10, 12], overlayText: '7:00 PM' },
        { label: 'Why they love it', beat: 'reflection', durationRange: [8, 10], overlayText: null },
      ],
    },
  },

  before_after: {
    id: 'before_after',
    name: 'Before & After',
    category: 'story',
    description: 'Transformation reveal with building tension and a satisfying visual payoff.',
    thumb: '/assets/frameworks/before-after.jpg',
    hookExamples: [
      'Watch [X] transform from [A] to [B]',
      'The [X] transformation nobody expected',
      '[X] makeover: the full process',
    ],
    supportedDurations: [30, 45],
    defaults: {
      visualStyle: 'photorealistic',
      videoStylePreset: 'commercial',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: true,
    ttsMode: 'single',
    transitionType: 'crossfade',
    transitionDuration: 1.0,
    textOverlays: 'required',
    overlayStyle: 'before_after',
    musicVolume: 0.20,
    musicMood: 'Building tension, release at reveal',
    ttsPacing: 'Building excitement, peak energy at reveal',
    sceneStructure: {
      30: [
        { label: 'The before', beat: 'setup', durationRange: [10, 12], overlayText: 'BEFORE' },
        { label: 'The process', beat: 'middle', durationRange: [10, 12], overlayText: null },
        { label: 'The reveal', beat: 'payoff', durationRange: [8, 10], overlayText: 'AFTER' },
      ],
      45: [
        { label: 'The before', beat: 'setup', durationRange: [10, 12], overlayText: 'BEFORE' },
        { label: 'The process', beat: 'middle', durationRange: [10, 12], overlayText: null },
        { label: 'The reveal', beat: 'payoff', durationRange: [8, 10], overlayText: 'AFTER' },
        { label: 'The detail', beat: 'detail', durationRange: [8, 10], overlayText: null },
      ],
    },
  },

  explainer_story: {
    id: 'explainer_story',
    name: 'Explainer Story',
    category: 'story',
    description: 'Curiosity-driven explanation that subverts common assumptions with a satisfying reveal.',
    thumb: '/assets/frameworks/explainer-story.jpg',
    hookExamples: [
      'Why [X] is the way it is',
      'The reason [X] does [Y] will surprise you',
      "How [X] actually works (it's not what you think)",
    ],
    supportedDurations: [45, 60],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'cinematic',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: true,
    ttsMode: 'single',
    transitionType: 'crossfade',
    transitionDuration: 1.0,
    textOverlays: 'optional',
    overlayStyle: null,
    musicVolume: 0.15,
    musicMood: 'Light, curious',
    ttsPacing: 'Curious, slightly energetic, like explaining to a friend',
    sceneStructure: {
      45: [
        { label: 'The question', beat: 'hook', durationRange: [8, 10], overlayText: null },
        { label: 'Common assumption', beat: 'setup', durationRange: [10, 12], overlayText: null },
        { label: 'The real answer', beat: 'core', durationRange: [12, 14], overlayText: null },
        { label: 'Proof/example', beat: 'evidence', durationRange: [10, 12], overlayText: null },
      ],
      60: [
        { label: 'The question', beat: 'hook', durationRange: [8, 10], overlayText: null },
        { label: 'Common assumption', beat: 'setup', durationRange: [10, 12], overlayText: null },
        { label: 'The real answer', beat: 'core', durationRange: [12, 14], overlayText: null },
        { label: 'Proof/example', beat: 'evidence', durationRange: [10, 12], overlayText: null },
        { label: 'So what?', beat: 'payoff', durationRange: [8, 10], overlayText: null },
      ],
    },
  },

  emotional_tribute: {
    id: 'emotional_tribute',
    name: 'Emotional Tribute',
    category: 'story',
    description: 'Slow, warm tribute to a person, place, or era — heavy on feeling and visual beauty.',
    thumb: '/assets/frameworks/emotional-tribute.jpg',
    hookExamples: [
      'A tribute to [X]',
      'In memory of [X]',
      'Why [X] meant so much to so many',
      'The beauty of [X]',
    ],
    supportedDurations: [45, 60],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'cinematic',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: true,
    ttsMode: 'single',
    transitionType: 'crossfade',
    transitionDuration: 2.0,
    textOverlays: 'optional',
    overlayStyle: 'labeled',
    musicVolume: 0.25,
    musicMood: 'Emotional/piano/strings',
    ttsPacing: 'Slow, warm, emotional weight',
    sceneStructure: {
      45: [
        { label: 'Opening image', beat: 'setup', durationRange: [10, 12], overlayText: null },
        { label: 'The significance', beat: 'core', durationRange: [10, 14], overlayText: null },
        { label: 'The moments', beat: 'detail', durationRange: [10, 14], overlayText: null },
        { label: 'The feeling', beat: 'emotion', durationRange: [10, 12], overlayText: null },
      ],
      60: [
        { label: 'Opening image', beat: 'setup', durationRange: [10, 12], overlayText: null },
        { label: 'The significance', beat: 'core', durationRange: [10, 14], overlayText: null },
        { label: 'The moments', beat: 'detail', durationRange: [10, 14], overlayText: null },
        { label: 'The feeling', beat: 'emotion', durationRange: [10, 12], overlayText: null },
        { label: 'Closing reflection', beat: 'close', durationRange: [8, 10], overlayText: null },
      ],
    },
  },

  top_x_countdown: {
    id: 'top_x_countdown',
    name: 'Top X Countdown',
    category: 'fast_paced',
    description: 'Ranked list with energetic pacing — each item gets its own punchy scene.',
    thumb: '/assets/frameworks/top-x-countdown.jpg',
    hookExamples: [
      "Top 5 [X] you've never heard of",
      '3 [X] that will change how you [Y]',
      'Ranking every [X] from worst to best',
    ],
    supportedDurations: [30, 45, 60],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'tiktok_reels',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: false,
    ttsMode: 'per_scene',
    transitionType: 'hard_cut',
    transitionDuration: 0,
    textOverlays: 'required',
    overlayStyle: 'numbered',
    musicVolume: 0.20,
    musicMood: 'Upbeat/energetic',
    ttsPacing: 'Fast, punchy, energetic',
    sceneStructure: {
      30: [
        { label: 'Hook', beat: 'hook', durationRange: [4, 5], overlayText: '{title}' },
        { label: 'Item #2', beat: 'item', durationRange: [8, 10], overlayText: '#2' },
        { label: 'Item #1', beat: 'item', durationRange: [10, 12], overlayText: '#1' },
      ],
      45: [
        { label: 'Hook', beat: 'hook', durationRange: [4, 5], overlayText: '{title}' },
        { label: 'Item #4', beat: 'item', durationRange: [8, 10], overlayText: '#4' },
        { label: 'Item #3', beat: 'item', durationRange: [8, 10], overlayText: '#3' },
        { label: 'Item #2', beat: 'item', durationRange: [8, 10], overlayText: '#2' },
        { label: 'Item #1', beat: 'item', durationRange: [10, 12], overlayText: '#1' },
      ],
      60: [
        { label: 'Hook', beat: 'hook', durationRange: [4, 5], overlayText: '{title}' },
        { label: 'Item #5', beat: 'item', durationRange: [8, 10], overlayText: '#5' },
        { label: 'Item #4', beat: 'item', durationRange: [8, 10], overlayText: '#4' },
        { label: 'Item #3', beat: 'item', durationRange: [8, 10], overlayText: '#3' },
        { label: 'Item #2', beat: 'item', durationRange: [8, 10], overlayText: '#2' },
        { label: 'Item #1', beat: 'item', durationRange: [10, 12], overlayText: '#1' },
      ],
    },
  },

  everything_you_need_to_know: {
    id: 'everything_you_need_to_know',
    name: 'Everything You Need to Know',
    category: 'fast_paced',
    description: 'Dense information delivery — explain a topic completely in under a minute.',
    thumb: '/assets/frameworks/everything-you-need-to-know.jpg',
    hookExamples: [
      'Everything you need to know about [X] in 60 seconds',
      '[X] explained in under a minute',
      '30 seconds to understand [X]',
    ],
    supportedDurations: [30, 60],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'tiktok_reels',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: false,
    ttsMode: 'per_scene',
    transitionType: 'hard_cut',
    transitionDuration: 0,
    textOverlays: 'required',
    overlayStyle: 'labeled',
    musicVolume: 0.15,
    musicMood: 'Ticking/urgent',
    ttsPacing: 'Fast but clear, no pauses, information-dense',
    sceneStructure: {
      30: [
        { label: 'What is it?', beat: 'definition', durationRange: [8, 10], overlayText: '{topic}' },
        { label: 'Why does it matter?', beat: 'relevance', durationRange: [10, 12], overlayText: '{keyword}' },
        { label: 'Bottom line', beat: 'takeaway', durationRange: [6, 8], overlayText: '{takeaway}' },
      ],
      60: [
        { label: 'What is it?', beat: 'definition', durationRange: [8, 10], overlayText: '{topic}' },
        { label: 'Why does it matter?', beat: 'relevance', durationRange: [10, 12], overlayText: '{keyword}' },
        { label: 'How does it work?', beat: 'mechanics', durationRange: [12, 14], overlayText: '{keyword}' },
        { label: 'Key fact/stat', beat: 'evidence', durationRange: [10, 12], overlayText: '{stat}' },
        { label: 'Bottom line', beat: 'takeaway', durationRange: [6, 8], overlayText: '{takeaway}' },
      ],
    },
  },

  myth_busting: {
    id: 'myth_busting',
    name: 'Myth Busting',
    category: 'fast_paced',
    description: 'Debunk popular misconceptions with confident energy and a clear alternative.',
    thumb: '/assets/frameworks/myth-busting.jpg',
    hookExamples: [
      '3 myths about [X] that are completely wrong',
      "You've been doing [X] wrong your whole life",
      'The truth about [X] nobody talks about',
    ],
    supportedDurations: [30, 45, 60],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'commercial',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: false,
    ttsMode: 'per_scene',
    transitionType: 'hard_cut',
    transitionDuration: 0,
    textOverlays: 'required',
    overlayStyle: 'myth_truth',
    musicVolume: 0.15,
    musicMood: 'Dramatic/revelatory',
    ttsPacing: 'Confident, slightly provocative, debunking energy',
    sceneStructure: {
      30: [
        { label: 'Hook', beat: 'hook', durationRange: [5, 6], overlayText: '{title}' },
        { label: 'Myth 1 + Truth', beat: 'myth_truth', durationRange: [12, 14], overlayText: 'MYTH / TRUTH' },
        { label: 'What to do instead', beat: 'takeaway', durationRange: [8, 10], overlayText: '{takeaway}' },
      ],
      45: [
        { label: 'Hook', beat: 'hook', durationRange: [5, 6], overlayText: '{title}' },
        { label: 'Myth 1 + Truth', beat: 'myth_truth', durationRange: [12, 14], overlayText: 'MYTH / TRUTH' },
        { label: 'Myth 2 + Truth', beat: 'myth_truth', durationRange: [12, 14], overlayText: 'MYTH / TRUTH' },
        { label: 'What to do instead', beat: 'takeaway', durationRange: [8, 10], overlayText: '{takeaway}' },
      ],
      60: [
        { label: 'Hook', beat: 'hook', durationRange: [5, 6], overlayText: '{title}' },
        { label: 'Myth 1 + Truth', beat: 'myth_truth', durationRange: [12, 14], overlayText: 'MYTH / TRUTH' },
        { label: 'Myth 2 + Truth', beat: 'myth_truth', durationRange: [12, 14], overlayText: 'MYTH / TRUTH' },
        { label: 'Myth 3 + Truth', beat: 'myth_truth', durationRange: [12, 14], overlayText: 'MYTH / TRUTH' },
        { label: 'What to do instead', beat: 'takeaway', durationRange: [8, 10], overlayText: '{takeaway}' },
      ],
    },
  },

  comparison_versus: {
    id: 'comparison_versus',
    name: 'Comparison / Versus',
    category: 'fast_paced',
    description: 'Head-to-head matchup between two options, ending with a decisive verdict.',
    thumb: '/assets/frameworks/comparison-versus.jpg',
    hookExamples: [
      '[X] vs [Y] - which one actually wins?',
      'Cheap vs expensive [X] - is it worth it?',
      'How [X] looked in [year] vs now',
    ],
    supportedDurations: [30, 45],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'commercial',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: false,
    ttsMode: 'per_scene',
    transitionType: 'hard_cut',
    transitionDuration: 0,
    textOverlays: 'required',
    overlayStyle: 'labeled',
    musicVolume: 0.15,
    musicMood: 'Competitive/sporty',
    ttsPacing: 'Analytical, fair, then decisive at the verdict',
    sceneStructure: {
      30: [
        { label: 'The matchup', beat: 'hook', durationRange: [5, 6], overlayText: '{X} vs {Y}' },
        { label: 'Contender A', beat: 'analysis', durationRange: [10, 12], overlayText: '{name}' },
        { label: 'The verdict', beat: 'verdict', durationRange: [8, 10], overlayText: 'WINNER: {X}' },
      ],
      45: [
        { label: 'The matchup', beat: 'hook', durationRange: [5, 6], overlayText: '{X} vs {Y}' },
        { label: 'Contender A', beat: 'analysis', durationRange: [10, 12], overlayText: '{name}' },
        { label: 'Contender B', beat: 'analysis', durationRange: [10, 12], overlayText: '{name}' },
        { label: 'The verdict', beat: 'verdict', durationRange: [8, 10], overlayText: 'WINNER: {X}' },
      ],
    },
  },

  did_you_know: {
    id: 'did_you_know',
    name: 'Did You Know',
    category: 'fast_paced',
    description: 'Surprising facts delivered with conspiratorial energy — each one lands with weight.',
    thumb: '/assets/frameworks/did-you-know.jpg',
    hookExamples: [
      "What you didn't know about [X]",
      '5 things nobody tells you about [X]',
      'Secrets of [X] revealed',
    ],
    supportedDurations: [30, 60],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'tiktok_reels',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: false,
    ttsMode: 'per_scene',
    transitionType: 'hard_cut',
    transitionDuration: 0,
    textOverlays: 'required',
    overlayStyle: 'numbered',
    musicVolume: 0.15,
    musicMood: 'Mystery/curious',
    ttsPacing: 'Conspiratorial, surprising, each fact lands with weight',
    sceneStructure: {
      30: [
        { label: 'Hook', beat: 'hook', durationRange: [5, 6], overlayText: '{title}' },
        { label: 'Fact 1', beat: 'fact', durationRange: [10, 12], overlayText: '#1 {phrase}' },
        { label: 'Mind-blower', beat: 'climax', durationRange: [8, 10], overlayText: '{phrase}' },
      ],
      60: [
        { label: 'Hook', beat: 'hook', durationRange: [5, 6], overlayText: '{title}' },
        { label: 'Fact 1', beat: 'fact', durationRange: [10, 12], overlayText: '#1 {phrase}' },
        { label: 'Fact 2', beat: 'fact', durationRange: [10, 12], overlayText: '#2 {phrase}' },
        { label: 'Fact 3', beat: 'fact', durationRange: [10, 12], overlayText: '#3 {phrase}' },
        { label: 'Mind-blower', beat: 'climax', durationRange: [8, 10], overlayText: '{phrase}' },
      ],
    },
  },

  challenge_experiment: {
    id: 'challenge_experiment',
    name: 'Challenge / Experiment',
    category: 'story',
    description: 'First-person challenge or experiment with timestamp anchors and personal outcome reveal.',
    thumb: '/assets/frameworks/challenge-experiment.jpg',
    hookExamples: [
      "I tried [X] for 30 days - here's what happened",
      "I tested every [X] so you don't have to",
      'What happens when you [X]?',
    ],
    supportedDurations: [45, 60],
    defaults: {
      visualStyle: 'photorealistic',
      videoStylePreset: 'vlog_bts',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: true,
    ttsMode: 'single',
    transitionType: 'crossfade',
    transitionDuration: 1.0,
    textOverlays: 'required',
    overlayStyle: 'timestamps',
    musicVolume: 0.20,
    musicMood: 'Upbeat/motivational',
    ttsPacing: 'Excited, personal, vlog energy',
    sceneStructure: {
      45: [
        { label: 'The premise', beat: 'hook', durationRange: [8, 10], overlayText: '{title}' },
        { label: 'Early days', beat: 'start', durationRange: [10, 12], overlayText: 'DAY 1-7' },
        { label: 'The middle', beat: 'struggle', durationRange: [12, 14], overlayText: 'DAY 15' },
        { label: 'The results', beat: 'outcome', durationRange: [10, 12], overlayText: 'DAY 30' },
      ],
      60: [
        { label: 'The premise', beat: 'hook', durationRange: [8, 10], overlayText: '{title}' },
        { label: 'Early days', beat: 'start', durationRange: [10, 12], overlayText: 'DAY 1-7' },
        { label: 'The middle', beat: 'struggle', durationRange: [12, 14], overlayText: 'DAY 15' },
        { label: 'The results', beat: 'outcome', durationRange: [10, 12], overlayText: 'DAY 30' },
        { label: 'Verdict', beat: 'verdict', durationRange: [8, 10], overlayText: '{verdict}' },
      ],
    },
  },

  history_timeline: {
    id: 'history_timeline',
    name: 'History / Timeline',
    category: 'fast_paced',
    description: 'Fast chronological sweep through an era or evolution with year-stamped scenes.',
    thumb: '/assets/frameworks/history-timeline.jpg',
    hookExamples: [
      'The entire history of [X] in 60 seconds',
      'How [X] evolved from [year] to now',
      '[X] through the decades',
    ],
    supportedDurations: [60, 90],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'documentary',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: false,
    ttsMode: 'per_scene',
    transitionType: 'hard_cut',
    transitionDuration: 0,
    textOverlays: 'required',
    overlayStyle: 'labeled',
    musicVolume: 0.15,
    musicMood: 'Era-appropriate or building',
    ttsPacing: 'Fast, factual, each era gets equal energy',
    sceneStructure: {
      60: [
        { label: 'Origin', beat: 'origin', durationRange: [8, 10], overlayText: '{year}' },
        { label: 'Early growth', beat: 'growth', durationRange: [10, 12], overlayText: '{year}' },
        { label: 'Golden era', beat: 'peak', durationRange: [10, 12], overlayText: '{year}' },
        { label: 'Modern shift', beat: 'shift', durationRange: [10, 12], overlayText: '{year}' },
        { label: 'Today + future', beat: 'present', durationRange: [8, 10], overlayText: 'NOW' },
      ],
      90: [
        { label: 'Origin', beat: 'origin', durationRange: [8, 10], overlayText: '{year}' },
        { label: 'Early growth', beat: 'growth', durationRange: [10, 12], overlayText: '{year}' },
        { label: 'Golden era', beat: 'peak', durationRange: [10, 12], overlayText: '{year}' },
        { label: 'Modern shift', beat: 'shift', durationRange: [10, 12], overlayText: '{year}' },
        { label: 'Today + future', beat: 'present', durationRange: [8, 10], overlayText: 'NOW' },
        { label: 'Forgotten chapter', beat: 'depth', durationRange: [10, 12], overlayText: '{year}' },
        { label: 'What comes next', beat: 'future', durationRange: [8, 10], overlayText: 'FUTURE' },
      ],
    },
  },

  hot_take: {
    id: 'hot_take',
    name: 'Hot Take',
    category: 'fast_paced',
    description: 'Bold opinion delivered with confidence — makes viewers react and share.',
    thumb: '/assets/frameworks/hot-take.jpg',
    hookExamples: [
      'The most overrated [X] and what to use instead',
      'Why everyone is wrong about [X]',
      'Unpopular opinion: [X] is better than [Y]',
    ],
    supportedDurations: [30, 45],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'tiktok_reels',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: false,
    ttsMode: 'per_scene',
    transitionType: 'hard_cut',
    transitionDuration: 0,
    textOverlays: 'required',
    overlayStyle: 'labeled',
    musicVolume: 0.15,
    musicMood: 'Confident/dramatic',
    ttsPacing: 'Bold, opinionated, slightly provocative',
    sceneStructure: {
      30: [
        { label: 'The take', beat: 'hook', durationRange: [5, 6], overlayText: '{opinion}' },
        { label: 'Why most people get it wrong', beat: 'argument', durationRange: [10, 12], overlayText: '{keyword}' },
        { label: 'The alternative', beat: 'recommendation', durationRange: [8, 10], overlayText: '{recommendation}' },
      ],
      45: [
        { label: 'The take', beat: 'hook', durationRange: [5, 6], overlayText: '{opinion}' },
        { label: 'Why most people get it wrong', beat: 'argument', durationRange: [10, 12], overlayText: '{keyword}' },
        { label: 'The evidence', beat: 'evidence', durationRange: [12, 14], overlayText: '{stat}' },
        { label: 'The alternative', beat: 'recommendation', durationRange: [8, 10], overlayText: '{recommendation}' },
      ],
    },
  },

  how_it_works: {
    id: 'how_it_works',
    name: 'How It Works',
    category: 'story',
    description: 'Clear, teacher-like walkthrough of a mechanism or process with visual anchors.',
    thumb: '/assets/frameworks/how-it-works.jpg',
    hookExamples: [
      'How [X] actually works',
      "[X] explained like you're 5",
      'The science behind [X]',
    ],
    supportedDurations: [45, 60],
    defaults: {
      visualStyle: 'cinematic',
      videoStylePreset: 'corporate',
      imageModel: 'fal_nano_banana',
      videoModel: 'fal_veo3',
    },
    frameChain: true,
    ttsMode: 'single',
    transitionType: 'crossfade',
    transitionDuration: 1.0,
    textOverlays: 'optional',
    overlayStyle: 'labeled',
    musicVolume: 0.12,
    musicMood: 'Light/curious',
    ttsPacing: 'Clear, teacher-like, slightly enthusiastic',
    sceneStructure: {
      45: [
        { label: 'The question', beat: 'hook', durationRange: [8, 10], overlayText: '{title}' },
        { label: 'The basics', beat: 'foundation', durationRange: [10, 12], overlayText: '{term}' },
        { label: 'The mechanism', beat: 'core', durationRange: [12, 14], overlayText: '{term}' },
        { label: 'The cool part', beat: 'highlight', durationRange: [10, 12], overlayText: '{phrase}' },
      ],
      60: [
        { label: 'The question', beat: 'hook', durationRange: [8, 10], overlayText: '{title}' },
        { label: 'The basics', beat: 'foundation', durationRange: [10, 12], overlayText: '{term}' },
        { label: 'The mechanism', beat: 'core', durationRange: [12, 14], overlayText: '{term}' },
        { label: 'The cool part', beat: 'highlight', durationRange: [10, 12], overlayText: '{phrase}' },
        { label: 'Why it matters', beat: 'payoff', durationRange: [8, 10], overlayText: '{takeaway}' },
      ],
    },
  },
};

export function getFramework(id) {
  return VIDEO_STYLE_FRAMEWORKS[id] || null;
}

export function listFrameworks() {
  return Object.values(VIDEO_STYLE_FRAMEWORKS);
}

export function getFrameworksByCategory(category) {
  return Object.values(VIDEO_STYLE_FRAMEWORKS).filter(f => f.category === category);
}

export function getSceneStructure(frameworkId, duration) {
  const fw = VIDEO_STYLE_FRAMEWORKS[frameworkId];
  if (!fw) return null;
  return fw.sceneStructure[duration] || fw.sceneStructure[fw.supportedDurations[0]];
}
