/**
 * Video Style Presets — controls animation/motion feel.
 * Appended to the motion prompt when generating image-to-video clips.
 */

export const VIDEO_STYLE_PRESETS = {
  iphone_selfie: {
    label: 'Smartphone Selfie (Raw)',
    category: 'realistic',
    description: 'Handheld smartphone footage, natural room lighting, raw unfiltered look',
    thumb: 'https://v3b.fal.media/files/b/0a931548/4aPyLtiRJ_nJXIB4BOIBW.jpg',
    prompt: 'raw smartphone front-facing camera footage, handheld grip with subtle persistent micro-shake and finger tremor, natural ambient room lighting with soft diffused window light falling on face, visible skin pores and natural texture without retouching, slight wide-angle lens distortion at frame edges, authentic unfiltered color profile with slightly cool shadow tones, relaxed genuine expression with natural micro-movements, casual everyday clothing with real fabric wrinkles, background slightly out of focus from close subject distance, spontaneous unperformed energy',
  },
  iphone_selfie_walking: {
    label: 'Walking Selfie',
    category: 'realistic',
    description: 'Vlogging while walking through streets, natural handheld bounce, urban background blur',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/Ab_posBJa4jAD1o3HtGOq.jpg',
    prompt: 'person walking through busy city street filming selfie on smartphone, rhythmic handheld bounce from walking gait, urban storefronts and pedestrians blurring in background, natural daylight with overhead sun, authentic vlog-style framing with chin slightly cut off, wind affecting hair and audio, genuine conversational energy while moving, real street ambient sounds implied, slight lens flare from sun angle, raw unprocessed smartphone color profile',
  },
  iphone_selfie_car: {
    label: 'Car Selfie',
    category: 'realistic',
    description: 'Dashboard-mounted or handheld in car, natural window light, casual driving vlog feel',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/kzkBlqMfJ-kM5duDKVSX0.jpg',
    prompt: 'person filming selfie video inside car, dashboard or hand-held smartphone angle, natural window light casting soft directional shadows across face, car interior visible with seatbelt and steering wheel in frame, slight micro-vibration from engine or road transmitted through camera, trees buildings and passing traffic blurring in window behind, authentic casual driving vlog aesthetic, warm filtered sunlight through windshield creating golden skin tone, relaxed conversational posture, front-facing camera slight wide-angle distortion, genuine unscripted energy and casual tone',
  },
  iphone_selfie_outdoor: {
    label: 'Outdoor Selfie',
    category: 'realistic',
    description: 'Park, beach or nature setting, bright natural sunlight, wind and open-air energy',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/DniBqRCgfjiTt3ajISksI.jpg',
    prompt: 'person filming outdoor selfie video at park or beach, bright natural sunlight with blue sky, green trees or ocean visible in background, wind blowing through hair, authentic smartphone front-camera quality with slight wide-angle distortion, genuine smile and relaxed outdoor energy, natural skin tones under direct sun, squinting slightly from brightness, birds or nature sounds implied, casual activewear or summer clothing',
  },
  ugc_testimonial: {
    label: 'UGC Testimonial',
    category: 'realistic',
    description: 'Person speaking to camera, soft ambient indoor lighting, authentic conversational feel',
    thumb: 'https://v3b.fal.media/files/b/0a931548/vwn7n5_DYC-SSyUw1VgJh.jpg',
    prompt: 'authentic user-generated testimonial video, real person speaking with natural speech cadence and genuine breath pauses mid-sentence, subtle lip movements matching natural talking rhythm without over-articulation, genuine micro-expressions shifting from uncertain to convinced, real skin with natural imperfections and visible pores without retouching, soft diffused ambient indoor lighting from overhead with slight side shadow, believable casual home or office setting with lived-in background depth, warm to cool neutral color temperature, direct conversational eye contact implying trust and sincerity',
  },
  ugc_unboxing: {
    label: 'Unboxing',
    category: 'realistic',
    description: 'Hands opening product packaging, table-top angle, genuine first reactions and excitement',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/F25D1GQZyFeVDwBFyvaFG.jpg',
    prompt: 'authentic unboxing video, hands carefully opening product packaging on table, overhead or angled table-top shot, tissue paper and branded box visible, genuine first-reaction expressions captured mid-moment, warm directional indoor lighting from desk lamp casting soft shadows, real skin texture on hands with natural imperfections, product gradually revealed layer by layer with building anticipation, casual home desk or wooden kitchen counter setting, filler materials and packing peanuts spilling out, natural ambient room sounds implied, authentic creator enthusiasm and spontaneous delight',
  },
  ugc_before_after: {
    label: 'Before & After',
    category: 'realistic',
    description: 'Transformation reveal, dramatic lighting shift, authentic results comparison',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/A2WBoSVPaF41PLzBgTvqh.jpg',
    prompt: 'before and after transformation video, dramatic visual comparison showing real results, intentional lighting shift between states — cooler and flatter before, warmer and more flattering after, authentic person showing genuine surprise or satisfaction at the change, split-moment transition between before and after states, natural soft indoor lighting with window fill, real skin texture and imperfections visible without retouching, honest unfiltered presentation style, subtle emotional arc building from skepticism to confidence, relatable setting with lived-in background, UGC testimonial authenticity throughout',
  },
  ugc_storytime: {
    label: 'Storytime',
    category: 'realistic',
    description: 'Cozy sit-down confessional, warm lamp lighting, intimate personal narrative style',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/WiLh4SL32Hb0t9INyLOe3.jpg',
    prompt: 'intimate storytime sit-down video, person on couch or bed speaking directly to camera, warm tungsten lamp or twinkling fairy-light strings creating cozy amber glow, soft textured blankets and plush cushions visible in frame, confessional personal narrative energy with leaning-in posture, genuine emotional micro-expressions shifting as story unfolds, natural pauses and thoughtful off-camera glances, close framing on face and upper body with shallow depth of field, evening at-home ambiance with dim background, authentic vulnerability and deep audience connection',
  },
  tiktok_style: {
    label: 'TikTok/Reels Style',
    category: 'realistic',
    description: 'Energetic creator content, ring light, expressive and vibrant social media aesthetic',
    thumb: 'https://v3b.fal.media/files/b/0a931548/r_c0kdMzJCSQRI77cgy90.jpg',
    prompt: 'vertical social media content creator video, direct-to-camera engagement with expressive natural facial movements and raised eyebrows, quick authentic reactions with genuine surprise or delight, real visible skin texture under ring light or diffused natural window light, slightly warm 4000K color temperature flattering skin tones, genuine personality radiating through micro-expressions and lip movements, natural hand gestures and pointing entering frame from sides, energetic but believable body language without over-performance, tight upper-body framing with breathing room above head',
  },
  tiktok_grwm: {
    label: 'GRWM (Get Ready With Me)',
    category: 'realistic',
    description: 'Vanity mirror setup, beauty ring light, makeup and styling routine, intimate creator content',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/qpQN97YgVEfe1CTslN-J8.jpg',
    prompt: 'get ready with me video at vanity mirror, circular beauty ring light creating even flattering catchlights and eliminating harsh shadows, cosmetics brushes and skincare products scattered across counter, bathroom or bedroom setting with personal touches visible, person applying makeup or styling hair with practiced movements, close-up detail shots of product application on skin, warm 4500K intimate creator energy, mirror reflections adding background depth, natural skin texture under diffused beauty lighting, relaxed morning routine pace with genuine personality',
  },
  tiktok_pov: {
    label: 'POV Storytelling',
    category: 'realistic',
    description: 'First-person perspective, dramatic reveals, immersive point-of-view narrative',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/uwK0TWRR0EEUtwHW4y9Ca.jpg',
    prompt: 'first-person POV perspective video, camera positioned at natural eye height becoming the viewer, hand reaching naturally into lower frame toward subject with visible forearm and fingers, dramatic reveal moments with carefully timed suspenseful pauses, deeply immersive storytelling where environment reacts to unseen protagonist, dynamic walking movement through environment with natural head-bob, short-form social media narrative structure with sharp emotional beats, cinematic practical lighting shifting with mood, natural handheld breathing motion, audience-as-character framing pulling viewer into the scene viscerally',
  },
  tiktok_tutorial: {
    label: 'Quick Tutorial',
    category: 'realistic',
    description: 'Step-by-step how-to, clean overhead or eye-level, clear instructional framing',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/jQEuHX9E31vm4FCYZJFWA.jpg',
    prompt: 'quick tutorial how-to video, clean overhead or eye-level shot of hands demonstrating steps on neutral surface, bright even diffused lighting eliminating shadows on workspace, clear visual focus maintained on the process at each stage, numbered or sequential step progression with deliberate pauses, minimal clutter with only relevant tools in frame, instructional pacing with purposeful slow movements, social media content creator framing style, accessible easy-to-follow composition, warm 5000K color-accurate lighting showing true material colors',
  },
  facetime_call: {
    label: 'FaceTime/Video Call',
    category: 'realistic',
    description: 'Webcam angle from above, screen glow on face, casual at-home video call look',
    thumb: 'https://v3b.fal.media/files/b/0a931548/7wBSi1OSB8-PnQTpnEkqp.jpg',
    prompt: 'video call aesthetic shot from laptop webcam angle positioned slightly above eye level, natural indoor ambient lighting mixing with blue-tinted screen glow illuminating face from below, casual at-home setting with bookshelf or plain wall visible behind, real skin texture with slight webcam compression softness, authentic conversational micro-expressions and natural lip sync movements, relaxed slightly slouched posture, genuine unperformed body language, subtle compression artifacts and mild noise grain, cool ambient room temperature feeling, spontaneous unpolished communication energy',
  },
  cinematic: {
    label: 'Cinematic',
    category: 'professional',
    description: 'Film-quality look with anamorphic lens, teal-orange grade, and shallow depth of field',
    thumb: 'https://v3b.fal.media/files/b/0a931548/822Q5nGf3Q2dCmwNQzE_b.jpg',
    prompt: 'cinematic film quality shot on large-format sensor, anamorphic framing feel with slight horizontal stretch, professional three-point lighting with large soft key light creating gentle shadow fall-off across face, shallow depth of field with creamy smooth bokeh separation, natural skin tones with subtle teal-orange color grading, film-like motion cadence at 24fps with natural motion blur, atmospheric haze catching shafts of practical light, precise rule-of-thirds composition with deliberate leading lines, rich deep blacks with lifted shadow detail, intentional negative space',
  },
  cinematic_golden_hour: {
    label: 'Golden Hour Cinematic',
    category: 'professional',
    description: 'Warm backlit magic hour, sun flares through trees, amber and honey tones, romantic epic feel',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/FMotizIqxUBhXu_iUmoMw.jpg',
    prompt: 'golden hour cinematic photography, warm backlit magic hour with sun low on horizon, amber and honey color palette, lens flares bursting through tree silhouettes, long dramatic shadows stretching across ground, soft diffused light wrapping around subjects, romantic epic atmosphere, shallow depth of field with golden bokeh, film-quality skin tones glowing in warm light, slow deliberate camera movement savoring the light',
  },
  cinematic_night: {
    label: 'Night Cinematic',
    category: 'professional',
    description: 'Neon-lit urban nightscape, moody blue tones, wet street reflections, atmospheric and brooding',
    thumb: 'https://v3b.fal.media/files/b/0a937f40/etLNjB9r-tmO1H5hvlptt.jpg',
    prompt: 'night cinematic urban photography, neon-lit streets with wet pavement reflecting colored light in elongated streaks, dominant deep blue and teal palette contrasted with warm amber and neon pink accents, moody atmospheric fog drifting through streetlight cones, puddle mirror reflections doubling the cityscape, slow tracking shots through nighttime urban landscape, high ISO film grain adding gritty texture in shadows, practical light sources creating isolated pools of illumination, brooding contemplative atmosphere, rain-slicked surfaces glistening under every passing headlight',
  },
  cinematic_anamorphic: {
    label: 'Anamorphic Widescreen',
    category: 'professional',
    description: 'Ultra-wide letterbox framing, horizontal lens flares, epic scale, Hollywood blockbuster feel',
    thumb: 'https://v3b.fal.media/files/b/0a937f40/aY-KpXiCIWXQfW60_B5rO.jpg',
    prompt: 'anamorphic widescreen cinematography, extreme 2.39:1 letterbox framing with hard black bars, horizontal electric blue lens flares stretching dramatically across the full width of frame, epic landscape establishing shots revealing breathtaking vast scale, characteristic oval stretched bokeh balls from anamorphic optics, subtle barrel distortion and breathing at frame edges, precise symmetrical or rule-of-thirds composition, sweeping slow dolly or crane camera movements, rich saturated color grading with deep crushed blacks and boosted midtone contrast, premium large-format visual grandeur and gravitas',
  },
  documentary: {
    label: 'Documentary',
    category: 'professional',
    description: 'Handheld observational style, natural available light, muted journalistic tones',
    thumb: 'https://v3b.fal.media/files/b/0a931548/WOFDTOKaHt0L9UxR6wlkN.jpg',
    prompt: 'observational documentary style, handheld camera with natural stabilization and occasional micro-shake, available light used authentically without artificial augmentation, candid unposed moments captured with patient timing, real environments with lived-in worn detail and character, natural desaturated skin tones with no color grading, muted neutral palette emphasizing truth over beauty, genuine emotional micro-expressions, shallow depth of field from real lenses, ambient sound atmosphere implied, journalistic truthful aesthetic with no artifice',
  },
  documentary_interview: {
    label: 'Sit-Down Interview',
    category: 'professional',
    description: 'Single camera, shallow depth of field, dark background, intimate talking-head format',
    thumb: 'https://v3b.fal.media/files/b/0a937f40/DWGpV2iox9uKBAVxBFwaz.jpg',
    prompt: 'sit-down documentary interview, single subject positioned against dark or softly blurred environmental background, shallow depth of field isolating speaker with gentle bokeh behind, professional soft box key light with subtle fill reducing harsh shadows, warm 5500K color temperature on skin, thoughtful serious expression with occasional looking-away moments of reflection, intimate tight talking-head framing showing face and shoulders, slight over-the-shoulder composition suggesting unseen off-camera interviewer, natural documentary-grade skin tones, quiet contemplative atmosphere, genuine emotional micro-expressions conveying authenticity',
  },
  documentary_nature: {
    label: 'Nature Documentary',
    category: 'professional',
    description: 'Planet Earth quality, macro wildlife details, aerial vistas, lush and pristine natural world',
    thumb: 'https://v3b.fal.media/files/b/0a937f40/XHaQ25QrhG8YrksRl-l8r.jpg',
    prompt: 'premium nature documentary quality, breathtaking macro close-ups of wildlife with visible feather and fur texture catching raking sidelight, aerial drone shots over pristine untouched landscapes, golden hour warm backlighting on wilderness silhouettes, slow-motion animal movement capturing grace and raw power, rich saturated natural color palette of emerald green amber and sky blue, intimate undisturbed animal behavior moments, lush dew-covered vegetation sparkling in early morning light, reverent patient awe-inspiring approach treating every creature as extraordinary',
  },
  documentary_street: {
    label: 'Street / Urban Doc',
    category: 'professional',
    description: 'Gritty handheld, real urban locations, available light, raw journalistic authenticity',
    thumb: 'https://v3b.fal.media/files/b/0a937f40/U9uLqzF3XiMC8GGZcHc6A.jpg',
    prompt: 'street documentary urban cinematography, gritty handheld camera with natural instability and occasional sharp reframe, real lived-in urban locations with layered character and history, available light only — harsh midday sun casting hard shadows, tungsten shopfronts glowing warm at dusk, graffiti walls and crowded market scenes full of texture, raw journalistic approach capturing genuine unguarded moments, slightly desaturated muted color palette draining glamour, candid unposed subjects moving through natural environment, ambient city noise and traffic implied, honest photojournalistic truth-telling aesthetic',
  },
  commercial: {
    label: 'Commercial/Ad',
    category: 'professional',
    description: 'Polished studio production, warm aspirational palette, premium clean composition',
    thumb: 'https://v3b.fal.media/files/b/0a931548/l-kPVFH0nkYpT7v2yZAah.jpg',
    prompt: 'high-end commercial production quality, precisely controlled studio lighting with large soft box diffusion eliminating harsh shadows, product and subject both held in crisp sharp focus simultaneously, polished but natural-looking skin with tasteful retouching, aspirational warm 5000K color palette with boosted vibrancy, smooth controlled gimbal or dolly camera movement with purposeful direction, clean balanced composition with generous visual breathing room, professional wardrobe with deliberate styling choices, premium production value conveying aspiration and quality without pretension',
  },
  commercial_luxury: {
    label: 'Luxury Brand Ad',
    category: 'professional',
    description: 'Slow-motion reveals, dark backgrounds, gold accents, ultra-premium high-end advertising',
    thumb: 'https://v3b.fal.media/files/b/0a937f41/XCCeQbcJLI157o6bqoPoa.jpg',
    prompt: 'luxury brand commercial cinematography, slow-motion product reveal against dark polished marble or deep velvet background, golden and champagne rim lighting wrapping edges in a premium glow, extreme attention to surface detail revealing material quality — brushed metal grain, stitched leather, engraved glass, deliberate unhurried pacing communicating exclusivity, rich deep blacks with warm 2700K metallic accent lighting, aspirational minimalist composition with generous breathing space, macro shots of premium craftsmanship, silk and leather textures catching directional light, ultra-high-end advertising production value',
  },
  commercial_lifestyle: {
    label: 'Lifestyle Ad',
    category: 'professional',
    description: 'Aspirational family/friends, warm sunny energy, natural and inviting, feel-good brand content',
    thumb: 'https://v3b.fal.media/files/b/0a937f41/3DqUws5gfjE59Yt8Sq9gG.jpg',
    prompt: 'lifestyle brand commercial, happy people in sunlit aspirational settings bathed in warm golden-hour light, genuine laughter and human connection between subjects, bright airy home or outdoor environments with clean sight lines, soft shallow depth of field creating dreamy separation, warm 5500K palette with boosted vibrancy and lifted midtones, smooth gimbal tracking following natural spontaneous movement, feel-good positive energy with no over-acting, inclusive diverse casting with real chemistry, premium but approachable visual tone',
  },
  commercial_fast_paced: {
    label: 'Fast-Paced / Dynamic Ad',
    category: 'professional',
    description: 'Quick cuts, energetic motion blur, bold colors, high-energy action-packed advertising',
    thumb: 'https://v3b.fal.media/files/b/0a937f41/HQVC1UvYBKHlhby8Bv4WC.jpg',
    prompt: 'fast-paced dynamic commercial, rapid quick-cut editing rhythm implying sub-second shots, energetic motion blur smearing on peak action moments, bold saturated neon and primary colors, athletic high-energy subject matter with kinetic physicality, dramatic speed ramp transitions from slow-motion to full speed, pumping bass-driven visual energy, graphic text overlays and bold impact typography feel, vibrant hard directional lighting with colored gel rim edges, adrenaline-fueled visual pacing that never lets the eye settle, extreme low angles and whip pan transitions',
  },
  product_demo: {
    label: 'Product Demo',
    category: 'professional',
    description: 'Clean product on neutral background, even studio lighting, sharp detail-focused framing',
    thumb: 'https://v3b.fal.media/files/b/0a931549/b_nvyKFhMTJekyrAo5yK1.jpg',
    prompt: 'clean professional product demonstration, seamless neutral white or light grey background with subtle gradient falloff, even wrap-around studio lighting revealing surface texture and material quality without harsh reflections, smooth deliberate product handling with natural relaxed hand movements, clear visual focus maintained on key product features and details, slight soft reflection on glossy surface below adding dimensionality, precise centered framing with product as undisputed hero, neutral 5500K color-accurate lighting, minimal props keeping attention on the object, premium e-commerce visual quality',
  },
  product_demo_hands_on: {
    label: 'Hands-On Demo',
    category: 'professional',
    description: 'Human hands interacting with product, close-up tactile engagement, real usage demonstration',
    thumb: 'https://v3b.fal.media/files/b/0a937f41/kBGv7rKaNMVSurK4MED-R.jpg',
    prompt: 'hands-on product demonstration video, real human hands interacting naturally with product, close-up shots of fingers pressing buttons and sliding controls with authentic tactile engagement, hands conveying weight and material texture through natural grip, warm overhead studio lighting at 5000K creating soft consistent illumination, clean workspace with product as undisputed visual hero, deliberate unhurried demonstrative movements clearly showing each function, authentic real-world usage scenario with natural hand skin texture, slight depth of field softening background while keeping product features sharp',
  },
  product_demo_macro: {
    label: 'Macro Detail Shot',
    category: 'professional',
    description: 'Extreme close-up of product surface, shallow DOF, premium material textures, meticulous detail',
    thumb: 'https://v3b.fal.media/files/b/0a937f41/gySc5cUdgeGewxnFU8b0i.jpg',
    prompt: 'extreme macro close-up product detail, razor-thin depth of field revealing surface texture and material quality, brushed metal grain or glass reflections or fabric weave visible, precision studio lighting with soft gradients across surface, slow rack focus between product details, premium material craftsmanship highlighted, color-accurate neutral lighting, every scratch and reflection intentional, meticulous attention to manufacturing detail, luxury product photography at maximum magnification',
  },
  product_demo_360: {
    label: '360 Product Spin',
    category: 'professional',
    description: 'Rotating turntable, clean backdrop, even lighting, complete product overview from all angles',
    thumb: 'https://v3b.fal.media/files/b/0a937f42/2SRZ5p0I9g7QHSauEvsoe.jpg',
    prompt: 'product 360-degree spin on motorized turntable, clean seamless white or soft grey gradient backdrop, perfectly even wrap-around studio lighting from multiple soft boxes eliminating harsh reflections, smooth continuous rotation at consistent speed revealing all angles, subtle glossy reflection on polished surface below adding dimensionality, professional e-commerce style with color-accurate 5500K neutral lighting, crisp sharp focus maintained throughout full rotation, product centered as floating hero with generous negative space, premium quality conveyed through every frame',
  },
  dreamy: {
    label: 'Dreamy/Ethereal',
    category: 'artistic',
    description: 'Soft diffusion glow, pastel palette, golden bokeh, and romantic overexposed highlights',
    thumb: 'https://v3b.fal.media/files/b/0a931549/rO3udTKiuzVwD_CO3DCBc.jpg',
    prompt: 'ethereal dreamlike quality with heavy soft diffusion filter effect and pro-mist haze, gentle overexposed highlights bleeding and wrapping softly around subject edges, pastel and heavily desaturated lavender rose and mint color palette, slow ultra-graceful flowing movement as if underwater, subtle lens glow haloing all light sources with star-burst flares, delicate large bokeh orbs drifting slowly in background, romantic soft golden or cool blue-hour natural light, flowing sheer fabric and loose hair moving in imperceptible gentle breeze, weightless suspended atmosphere',
  },
  dreamy_fairy_tale: {
    label: 'Fairy Tale',
    category: 'artistic',
    description: 'Enchanted forest, magical golden particles, soft dappled sunlight, mystical storybook wonder',
    thumb: 'https://v3b.fal.media/files/b/0a937f42/M9P27cNjJeYY8uOyWlXWo.jpg',
    prompt: 'enchanted fairy tale forest cinematography, magical golden particles and fireflies floating through air, soft dappled sunlight filtering through ancient moss-covered trees, mystical atmosphere with gentle fog at ground level, storybook illustration quality brought to life, warm golden and emerald green color palette, slow ethereal camera movement gliding through enchanted woodland, delicate flower petals drifting on breeze, fantasy world made tangible, childlike wonder and magic in every frame',
  },
  dreamy_golden_haze: {
    label: 'Golden Haze',
    category: 'artistic',
    description: 'Warm backlit haze, sun flare through hair, romantic soft focus, amber honey tones',
    thumb: 'https://v3b.fal.media/files/b/0a937f42/GcJeqSpntU1j2GlGOWfvj.jpg',
    prompt: 'golden haze romantic cinematography, warm backlit diffusion creating glowing halo around subject, sun flare bursting through hair and fabric, amber and honey color tones dominating palette, romantic soft focus with pro-mist filter quality, gentle overexposed highlights bleeding into shadows, slow graceful movement, wheat fields or meadow setting bathed in warm light, lens glow on every light source, intimate love-story visual language',
  },
  dreamy_underwater: {
    label: 'Underwater Dream',
    category: 'artistic',
    description: 'Slow-motion submerged look, light caustics dancing, flowing fabric, serene aquatic weightlessness',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/8oN9W1pFUtQkV8YgpUh49.jpg',
    prompt: 'underwater dream sequence cinematography, slow-motion movement through crystal-clear turquoise water, shimmering light caustics dancing across skin surfaces and sandy floor, flowing silk fabric and hair suspended in weightless swirl, tiny silver bubbles rising and catching refracted sunlight, serene submerged atmosphere, deep aquamarine and teal color palette with warm gold highlights from above, ethereal weightlessness in every gesture, shafts of sunlight piercing down in volumetric rays, graceful ballet-like movement suggesting dreaming rather than swimming',
  },
  vintage: {
    label: 'Vintage/Retro',
    category: 'artistic',
    description: '16mm film grain, warm amber tones, vignette edges, and lifted nostalgic blacks',
    thumb: 'https://v3b.fal.media/files/b/0a931549/yl-LFzXU8X1B4tPokgQB0.jpg',
    prompt: 'authentic vintage 16mm film aesthetic, warm amber and sepia color shift with faded blacks lifted to milky grey, organic dancing film grain texture visible across skin and textured surfaces, pronounced vignette darkening at frame corners, period-appropriate soft focus quality from older lens coatings, gentle gate weave causing subtle horizontal frame instability, nostalgic halation blooming around bright windows and highlights, slightly desaturated warm tones, occasional light flicker suggesting projector inconsistency, deeply nostalgic analog memory quality',
  },
  vintage_70s: {
    label: '70s Film',
    category: 'artistic',
    description: 'Warm orange-brown palette, soft film grain, retro decor, golden nostalgic warmth',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/26yE3PKUr0oePyeF10KR9.jpg',
    prompt: '1970s film aesthetic cinematography, warm orange amber and brown color palette with faded saturation, soft organic film grain visible across frame, golden warm tones dominating highlights, period-appropriate soft focus quality from vintage lenses, retro decor and warm wood tones in environment, gentle halation around bright light sources, nostalgic analog warmth, slightly lifted blacks with milky shadow tone, Kodak Ektachrome color science feel',
  },
  vintage_vhs: {
    label: '80s VHS',
    category: 'artistic',
    description: 'Scan lines, tracking artifacts, neon pink-cyan palette, CRT glow, synthwave nostalgia',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/1g7G1Ms36bwUlSucPR5gx.jpg',
    prompt: '1980s VHS tape recording aesthetic, visible horizontal scan lines across the frame, intermittent tracking artifacts and static distortion bands, neon pink cyan and electric blue color palette with washed-out accuracy, CRT television phosphor glow creating warm screen halo, synthwave retro-futuristic vibes with color bleeding at high-contrast edges, analog video noise and color fringing, date-time stamp in corner, soft blurry focus from magnetic tape degradation, fluorescent-lit interiors with heavy single-source shadows, Saturday morning TV nostalgia and lo-fi analog charm',
  },
  vintage_super8: {
    label: 'Super 8mm',
    category: 'artistic',
    description: 'Heavy film grain, gate weave, blown highlights, intimate home-movie nostalgia',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/H7obnR5LWORxjs_U7rwKG.jpg',
    prompt: 'Super 8mm home movie footage aesthetic, heavy visible film grain with dancing texture, gate weave causing subtle frame instability, blown-out overexposed highlights with warm amber tint, narrow depth of field from small format, intimate personal home-movie quality, light leaks and exposure fluctuations, slightly sped-up motion cadence, rounded vignette at frame corners, scratches and dust artifacts, deeply nostalgic personal memory quality',
  },
  noir: {
    label: 'Film Noir',
    category: 'artistic',
    description: 'High contrast chiaroscuro, dramatic shadows, venetian blind patterns, atmospheric smoke',
    thumb: 'https://v3b.fal.media/files/b/0a931549/GNvgxVWjhFc0ZXHtddWii.jpg',
    prompt: 'classic film noir cinematography, extreme high contrast chiaroscuro lighting with crushed deep blacks and hard bright specular highlights, single harsh key light from low angle casting long dramatic shadows across walls and faces, venetian blind stripe shadow patterns cutting across scenes, cigarette smoke and atmospheric haze catching light beams in mid-air, moody near-monochromatic desaturated cool palette with occasional warm amber accent, low-key lighting deliberately concealing most of frame, wet pavement reflections doubling light sources, claustrophobic closed compositions suggesting entrapment',
  },
  noir_neo: {
    label: 'Neo-Noir',
    category: 'artistic',
    description: 'Modern city rain, neon through venetian blinds, teal-magenta accents, contemporary dark thriller',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/K8a8kxUT1gwY9I5CjSt17.jpg',
    prompt: 'neo-noir modern cinematography, contemporary city at night with heavy rain streaking windows, neon signage casting teal and pink-magenta light through venetian blind slats creating hard stripe patterns across faces and walls, deep crushed blacks with vivid color accent pools, wet reflective surfaces everywhere doubling every light source, sleek modern glass architecture, surveillance camera angles and voyeuristic detached framing suggesting unseen observer, oppressive moody atmospheric tension, practical neon and sodium vapor light sources only, rain-soaked urban dystopia visual language',
  },
  noir_detective: {
    label: 'Detective / Mystery',
    category: 'artistic',
    description: 'Evidence and clues in spotlight, smoke wisps, suspenseful reveals, classic mystery atmosphere',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/Shsh4nK3LgYurKAq36-W7.jpg',
    prompt: 'detective mystery noir cinematography, dramatic spotlight illuminating evidence and clues on desk, wisps of cigarette smoke curling through light beams, magnifying glass and case files, suspenseful reveal pacing with slow deliberate camera pushes, dark shadows concealing most of frame, warm amber desk lamp as sole light source, noir thriller tension and intrigue, mysterious atmosphere where every shadow hides secrets, classic whodunit visual storytelling',
  },
  noir_silhouette: {
    label: 'Silhouette / Shadow Play',
    category: 'artistic',
    description: 'Stark backlit figures, long dramatic shadows, minimal detail, high-contrast light and dark',
    thumb: 'https://v3b.fal.media/files/b/0a937f44/3xO_4ggmv4LgujA282C6Y.jpg',
    prompt: 'silhouette shadow play cinematography, stark backlit figures reduced to pure black shapes against bright overexposed background, long dramatic shadows stretching across walls and floors, extreme high-contrast with virtually no midtones — only absolute black and blown white, minimal visible detail deliberately forcing imagination, venetian blind stripe shadow patterns cutting rhythmically across surfaces, single powerful backlight or window as sole illumination source, mysterious anonymous figures, graphic bold composition with strong negative space, visual storytelling through gesture shape and shadow alone',
  },
  anime: {
    label: 'Anime Style',
    category: 'artistic',
    description: 'Vibrant cel-shaded animation, expressive characters, detailed backgrounds, dynamic angles',
    thumb: 'https://v3b.fal.media/files/b/0a931549/gVmrP3xeHjdNrp3T2qOHk.jpg',
    prompt: 'high-quality anime art style animation, vibrant heavily saturated color palette with bold complementary contrasts, expressive character animation with fluid anticipation and follow-through, dynamic speed lines radiating from action points and impact flash frames, detailed hand-painted background art with atmospheric aerial perspective, cel-shaded lighting with crisp hard shadow edges and specular highlight glints on eyes, wind-blown flowing hair and clothing with fabric physics, dramatic low-angle and dutch-tilt camera compositions, emotional close-ups with shimmering eye catchlights, classic animation quality with confident linework',
  },
  faceless_cinematic: {
    label: 'Faceless Cinematic',
    category: 'faceless',
    description: 'No people — dramatic landscapes, objects, and environments with cinematic framing',
    thumb: 'https://v3b.fal.media/files/b/0a937140/wVaaSs_tJKc4rXX0_QfA8.jpg',
    prompt: 'cinematic establishing shots without any people or faces, sweeping landscape cinematography with epic scale, dramatic volumetric rays cutting through dust or fog, slow controlled camera movement on dolly or crane, layered atmospheric depth with foreground middle and background separation, deep atmospheric haze in far distance, professional teal-orange color grading with rich contrast, detailed surface textures on stone bark and terrain catching raking light, no human figures present at any point in frame',
  },
  faceless_tech: {
    label: 'Faceless Tech',
    category: 'faceless',
    description: 'No people — screens, circuits, data visualizations, and futuristic tech imagery',
    thumb: 'https://v3b.fal.media/files/b/0a937140/6-tSIuVwEj7ClNuj-nTnq.jpg',
    prompt: 'technology-focused visuals without any people or faces, glowing monitors and holographic display interfaces floating in air, circuit board macro shots with copper traces catching blue light, server room corridors with blinking indicator lights, flowing cascading code and data visualization streams in electric blue and green, cool blue-tinted ambient lighting with neon accents, pristine modern lab environments with reflective surfaces, extreme macro shots of tech components revealing microscopic detail, sleek futuristic aesthetic with precise geometric composition',
  },
  faceless_nature: {
    label: 'Faceless Nature',
    category: 'faceless',
    description: 'No people — stunning nature footage, macro details, aerial landscapes',
    thumb: 'https://v3b.fal.media/files/b/0a937140/8qIkQ0farGhW2KnxxcdJA.jpg',
    prompt: 'breathtaking nature cinematography without any people or faces, extreme macro close-ups of moss textures and insect wing scales revealing hidden worlds, sweeping aerial drone shots over pristine wilderness, warm golden-hour back-lighting making leaves translucent and dewdrops glow, cool blue-hour mist rising from still water surfaces, time-lapse quality cloud movement suggesting passage of time, rich saturated earthy green amber and terracotta color palette, intimate botanical and geological detail shots catching raking sidelight, serene reverent observation of untouched natural systems',
  },
  faceless_abstract: {
    label: 'Faceless Abstract',
    category: 'faceless',
    description: 'No people — abstract shapes, particles, gradients, and motion graphics feel',
    thumb: 'https://v3b.fal.media/files/b/0a937140/RM6aJ7NLVI5qIP4o6fM9h.jpg',
    prompt: 'abstract visual art without any people or faces, flowing particle systems and swirling geometric shapes in constant motion, smooth gradient color transitions melting from one hue to the next, organic fluid simulations with liquid viscosity and surface tension, delicate light trails and soft bokeh orbs drifting through frame, minimalist composition with generous negative space, ethereal atmospheric glow emanating from within shapes, slow pulsing rhythm, hypnotic repeating mandala-like patterns with subtle variation, deep color saturation against dark voids',
  },
  faceless_dark: {
    label: 'Faceless Dark/Horror',
    category: 'faceless',
    description: 'No people — eerie environments, shadows, abandoned spaces, atmospheric dread',
    thumb: 'https://v3b.fal.media/files/b/0a937140/1Z8T2zploTKhVnPVCQ1KU.jpg',
    prompt: 'dark atmospheric visuals without any people or faces, abandoned crumbling spaces and decaying architecture with peeling paint and broken windows, near-total deep shadows with only isolated minimal light sources like a dying bulb, thick ground-level fog obscuring lower details, heavily desaturated cold blue-grey color palette draining warmth, subtle ominous slow movement in darkness suggesting presence, eerie environmental textures of rust mold and wet concrete, oppressive low-key lighting crushing shadows to near-black, lingering dread in every frame without explicit threat',
  },
  motion_graphics: {
    label: 'Motion Graphics',
    category: 'faceless',
    description: 'No people — infographic-style with bold shapes, icons, and kinetic typography feel',
    thumb: 'https://v3b.fal.media/files/b/0a937141/l592R5nxcNJuLo_U47Og6.jpg',
    prompt: 'clean motion graphics style without any people or faces, bold geometric shapes and flat design elements sliding and morphing with precision easing, smooth kinetic transitions between scenes using wipes and dissolves, infographic-inspired data presentation with animated bar charts and diagrams, vibrant high-contrast color blocks on clean white or dark backgrounds, isometric perspective illustrations with layered depth, minimalist icons and symbols appearing with pop-on bounce, crisp vector-sharp edges throughout, professional broadcast motion graphics quality with cohesive visual system',
  },
  stock_footage: {
    label: 'Stock B-Roll',
    category: 'faceless',
    description: 'No people — generic professional B-roll style, versatile and clean',
    thumb: 'https://v3b.fal.media/files/b/0a937141/tIl66bizkF1F4iebjmOmL.jpg',
    prompt: 'professional stock footage B-roll style without any people or faces, clean well-lit environments with even soft lighting eliminating harsh shadows, versatile neutral scenes ideal for voiceover overlay, smooth stabilized gimbal camera movement with gentle drift, neutral balanced color grading neither warm nor cool, modern office desks and workspaces with clean surfaces, city skylines and traffic from elevated angles, everyday objects photographed with deliberate compositional care, natural textures and materials under flattering light, polished but anonymous commercial visual language',
  },

  // ── Realistic ──

  vlog_bts: {
    label: 'Vlog / Behind-the-Scenes',
    category: 'realistic',
    description: 'Casual creator content, messy creative workspace, authentic unscripted handheld feel',
    thumb: 'https://v3b.fal.media/files/b/0a937239/0uSlA448KlBWXoHgBdA2n.jpg',
    prompt: 'casual vlog behind-the-scenes footage, handheld camera with natural wobble and occasional reframe, authentic messy creative workspace visible with scattered props and half-finished projects, natural ambient window light mixed with warm screen glow creating mixed color temperature, genuine unscripted spontaneous moments caught mid-action, visible camera gear and equipment casually in background, relaxed conversational energy with direct audience address, raw cool color profile without heavy grading, real surface textures and imperfections celebrated, informal off-center framing',
  },
  podcast_interview: {
    label: 'Podcast / Interview',
    category: 'realistic',
    description: 'Studio podcast setup, professional microphones, warm broadcast lighting, conversational framing',
    thumb: 'https://v3b.fal.media/files/b/0a937239/Vf0e669pFRyivxdpm0aCF.jpg',
    prompt: 'professional podcast interview setup, large studio-quality condenser microphones prominently visible on boom arms, acoustic treatment foam panels in softly blurred background, warm diffused studio lighting with subtle rim hair light separating subject from background, conversational two-shot or tight over-shoulder framing, shallow depth of field isolating speakers against warm amber bokeh, clean broadcast-grade color with warm 3200K tone, genuine animated eye contact and natural expressive hand gestures, professional yet relaxed conversational atmosphere suggesting comfortable dialogue',
  },

  // ── Professional ──

  corporate_training: {
    label: 'Corporate / Training',
    category: 'professional',
    description: 'Clean office environment, professional presenter, even lighting, business aesthetic',
    thumb: 'https://v3b.fal.media/files/b/0a937239/D9dEDR4y752Fgzb0cKWxe.jpg',
    prompt: 'corporate training video production, clean modern glass-walled office or conference room, even soft-box lighting without harsh shadows at neutral 5500K, presenter in business attire with confident posture and controlled hand gestures, neutral branded background with subtle company identity, crisp sharp focus on subject, whiteboard diagrams or presentation screen graphics visible over shoulder, steady tripod shot with occasional slow push-in, muted professional color palette with cool blues and clean whites, clear authoritative visual tone conveying competence',
  },
  real_estate: {
    label: 'Real Estate Tour',
    category: 'professional',
    description: 'Architectural walkthroughs, wide-angle interiors, golden hour light, aspirational lifestyle',
    thumb: 'https://v3b.fal.media/files/b/0a937239/u52nlYgQ9vC3i3GvJOYhF.jpg',
    prompt: 'luxury real estate tour cinematography, wide-angle architectural shots revealing full room depth, smooth gimbal walkthrough movement gliding between spaces, warm golden hour sunlight streaming through oversized windows casting long inviting shadows, polished interior design with carefully staged furniture and curated decor, high dynamic range exposure balancing bright windows against dark corners, slow controlled panning sweeps revealing each space, aspirational lifestyle composition with intentional sightlines, warm inviting 4000K color grade, aerial drone exterior shots establishing property scale',
  },

  // ── Artistic ──

  cyberpunk_neon: {
    label: 'Cyberpunk / Neon',
    category: 'artistic',
    description: 'Rain-soaked neon streets, holographic elements, purple-cyan palette, futuristic noir',
    thumb: 'https://v3b.fal.media/files/b/0a937239/pxeHpN8hrepuhn0D-0tPe.jpg',
    prompt: 'cyberpunk neon-drenched cinematography, rain-slicked streets reflecting vibrant neon signage in long puddle streaks, holographic advertisements and floating digital overlays layering the atmosphere, dominant electric purple cyan and hot magenta color palette cutting through darkness, atmospheric fog catching colored light beams volumetrically, dystopian megacity with oppressive urban density, low dramatic angles emphasizing looming architecture overhead, anamorphic lens flares bursting from every neon source, moody futuristic noir atmosphere with surveillance drones and flickering signs, extreme high contrast with crushed deep blacks',
  },
  fantasy_epic: {
    label: 'Fantasy / Epic',
    category: 'artistic',
    description: 'Sweeping mythical landscapes, dramatic storm lighting, majestic scale, cinematic grandeur',
    thumb: 'https://v3b.fal.media/files/b/0a937239/tjx-NcGOHyEIRqyGchrSW.jpg',
    prompt: 'epic fantasy cinematography with sweeping mythical landscape vistas, dramatic volumetric light breaking through storm clouds in cathedral shafts, towering castles and ancient stone architecture rising from mist, majestic mountain ranges receding into atmospheric haze, slow aerial crane shots revealing breathtaking scale, rich earthy terracotta forest green and golden color palette, cinematic lens flares bursting from torches and magical light sources, thick fog rolling through shadowed valleys at dawn, high fantasy grandeur and reverence for nature and ancient power',
  },
  stop_motion: {
    label: 'Stop Motion',
    category: 'artistic',
    description: 'Claymation feel, handcrafted miniature sets, tactile textures, charming frame-by-frame motion',
    thumb: 'https://v3b.fal.media/files/b/0a93723a/dQANWEjZxlvlzX-oHfIFI.jpg',
    prompt: 'stop motion claymation animation style, handcrafted characters with visible fingerprint textures pressed into clay surfaces, miniature practical sets constructed from real fabrics paper and found materials, warm directional tungsten lighting creating soft diffused shadows across small figures, slightly jerky intentional frame-by-frame motion cadence with characteristic stutter, charming handmade imperfections in movement and form, premium studio-quality claymation craftsmanship with careful armature work, shallow depth of field blurring miniature backgrounds on small scale, cozy warm intimate atmosphere with tactile weight and presence',
  },
  watercolor_painterly: {
    label: 'Watercolor / Painterly',
    category: 'artistic',
    description: 'Soft flowing pigments, translucent washes, visible brush textures, dreamy painted aesthetic',
    thumb: 'https://v3b.fal.media/files/b/0a93723a/UoOiRUfcP2fNNxzaZoUq5.jpg',
    prompt: 'watercolor painting animation style, soft flowing pigment washes with translucent layered color glazes, visible cold-press paper texture showing through thin paint, dreamy botanical and natural scenes with loose expressive mark-making, gentle desaturated pastel palette of sage blush lavender and warm ivory, organic wet-into-wet bleeding edges where two colors meet and bloom, delicate fine brushwork visible in foreground details, slow ethereal camera movement suggesting a gentle breeze drifting through painted landscapes, artistic hand-painted quality with intentional brush inconsistencies and happy accidents',
  },

  // ── Faceless ──

  faceless_food: {
    label: 'Faceless Food/Cooking',
    category: 'faceless',
    description: 'No people — overhead food styling, macro ingredient details, warm kitchen lighting',
    thumb: 'https://v3b.fal.media/files/b/0a93723a/P6-2Fm7M3FHFP7AXV-V8Y.jpg',
    prompt: 'professional food cinematography without any people or faces, overhead flat-lay plating shots on clean marble or dark wood surfaces, extreme macro close-ups of fresh ingredients revealing glistening textures and vibrant color, wispy steam rising from hot dishes in backlit dramatic light, warm 3200K kitchen lighting with golden amber tones, smooth slow-motion pours of sauces and drizzles of honey, rich appetizing color saturation boosted to appetite-triggering levels, professional food styling with deliberate garnish placement and crumb details, ASMR-quality visual intimacy',
  },
  faceless_travel: {
    label: 'Faceless Travel',
    category: 'faceless',
    description: 'No people — aerial landscapes, turquoise waters, golden-hour destinations, wanderlust aesthetic',
    thumb: 'https://v3b.fal.media/files/b/0a93723a/LL7O8gqJndCoVjqbDWc2f.jpg',
    prompt: 'stunning travel cinematography without any people or faces, aerial drone shots over turquoise ocean and tropical coastlines, golden-hour landscapes with warm shadows stretching across ancient ruins or empty beaches, wide establishing shots of iconic destinations, smooth hyperlapse through winding scenic routes, richly saturated wanderlust color palette of deep teal sand amber and sky blue, time-lapse sunsets melting through layered orange and magenta clouds, underwater coral reef glimpses in dappled tropical light, sweeping mountain panoramas conveying freedom and scale',
  },
  faceless_luxury: {
    label: 'Faceless Luxury/Lifestyle',
    category: 'faceless',
    description: 'No people — premium products, marble surfaces, golden accents, editorial brand photography',
    thumb: 'https://v3b.fal.media/files/b/0a93723a/6oXKtIVZSQ8NQAJOdexlB.jpg',
    prompt: 'luxury lifestyle product cinematography without any people or faces, premium objects on polished marble and deep lacquered dark surfaces, golden and rose-gold rim lighting wrapping edges with aspirational warmth, soft buttery bokeh background with warm amber tones, editorial brand photography aesthetic with precise placement, slow deliberate reveal of luxury details through creeping camera movement, warm 2700K champagne color palette, aspirational minimalist framing with generous negative space, designer items given commanding presence, immaculate high-end catalog quality',
  },

  // ── Kids & Education ──

  kids_cartoon: {
    label: 'Kids Cartoon',
    category: 'kids',
    description: 'Bright friendly animation, big expressive eyes, vibrant primary colors, cheerful wholesome feel',
    thumb: 'https://v3b.fal.media/files/b/0a93723b/aLF65T33tf8yPztJIM8jF.jpg',
    prompt: 'colorful kids cartoon animation style, bright friendly characters with big sparkling expressive eyes and soft rounded features, vibrant primary color palette with cheerful saturation and candy-bright hues, smooth clean outlines, sunny welcoming environments with cloud-dotted skies and lush rounded trees, playful bouncy movement energy with squash and stretch physicality, modern 2D preschool animation aesthetic with bold graphic shapes and crisp linework, simple readable compositions for young audiences, wholesome positive atmosphere, soft diffused shadows and gentle even lighting',
  },
  kids_3d_animation: {
    label: '3D Kids Animation',
    category: 'kids',
    description: 'Premium 3D animation studio quality with soft lighting, rounded characters, vibrant colorful worlds',
    thumb: 'https://v3b.fal.media/files/b/0a93a83d/VdyZcvJXsIocbiRpR-_Sg.jpg',
    prompt: 'premium 3D animated kids style with studio-quality production value, soft rounded character designs with expressive oversized eyes and smooth plastic-like skin textures, vibrant saturated color palette with candy-bright hues, warm diffused global illumination with soft ambient occlusion, playful bouncy character animation with squash and stretch principles, richly detailed miniature environments with depth of field bokeh, volumetric lighting with gentle god rays, whimsical props and exaggerated proportions, cheerful uplifting atmosphere, clean crisp rendering with subtle subsurface scattering on skin',
  },
  whiteboard_explainer: {
    label: 'Whiteboard / Explainer',
    category: 'kids',
    description: 'Hand-drawn diagrams on white background, marker illustrations, clean educational infographic style',
    thumb: 'https://v3b.fal.media/files/b/0a93723b/xP9F4hMBg7Si8FixHRT4w.jpg',
    prompt: 'whiteboard explainer animation style, real visible hand drawing bold black marker illustrations progressively on clean white background, simple icons diagrams and connecting arrows appearing with confident fluid strokes, educational infographic visual language with labeled diagrams and numbered steps, kinetic hand-drawn presentation pacing timed to explanation, minimal strategic color accents in red blue and yellow highlighting key concepts, smooth continuous drawing motion revealing ideas sequentially, clean bold readable sans-serif typography, warm paper-white background texture, professional knowledge-sharing aesthetic with clear visual hierarchy',
  },
  kids_fairy_tale: {
    label: 'Fairy Tale',
    category: 'kids',
    description: 'Enchanted storybook world with castles, magical creatures, soft golden glow and dreamy sparkle effects',
    thumb: 'https://v3b.fal.media/files/b/0a93aaf8/UuiNtQ9cwUECCYYnlBPT1_KOssr1q4.png',
    prompt: 'enchanted fairy tale animation style, magical storybook kingdom with turreted castles and winding forest paths, soft golden hour glow with sparkling particle effects, gentle pastel color palette with warm pinks purples and golds, friendly magical creatures with big expressive eyes, dreamy atmospheric haze and floating fireflies, lush hand-painted watercolor backgrounds, smooth gentle camera movements through enchanted landscapes, whimsical stardust transitions, safe warm inviting atmosphere for young viewers',
  },
  kids_storybook: {
    label: 'Storybook Illustration',
    category: 'kids',
    description: 'Hand-painted watercolor pages coming to life, soft edges, gentle pastel tones, bedtime story warmth',
    thumb: 'https://v3b.fal.media/files/b/0a93aaf8/49zRUMiLrNKfX-iqWIPx-_cBKEM46z.png',
    prompt: 'children storybook illustration animation, hand-painted watercolor pages gently coming to life, soft feathered edges with visible paper texture, warm pastel color palette of peach mint lavender and buttercup yellow, charming simple character designs with round heads and dot eyes, cozy domestic scenes with patterned quilts and window light, gentle page-turn transitions, slow calming camera pans across illustrated landscapes, bedtime story warmth and comfort, nostalgic picture book quality',
  },
  kids_educational: {
    label: 'Kids Educational',
    category: 'kids',
    description: 'Fun learning animation with labeled diagrams, counting objects, colorful infographic elements',
    thumb: 'https://v3b.fal.media/files/b/0a93aaf8/Ve5WkKaylx6OMD0CVb6O3_JYTXoEQA.png',
    prompt: 'fun educational kids animation style, colorful labeled diagrams and infographic elements appearing playfully, counting objects bouncing into frame, bright primary color backgrounds with clean graphic design, friendly presenter character with simple rounded features, text and numbers animating with pop and bounce effects, clear visual hierarchy for learning concepts, interactive quiz-show energy, curriculum-friendly presentation with engaging visual mnemonics, engaging children educational TV entertainment quality',
  },
  kids_preschool: {
    label: 'Preschool',
    category: 'kids',
    description: 'Ultra-simple shapes and bold primary colors, gentle slow pacing, toddler-friendly animation style',
    thumb: 'https://v3b.fal.media/files/b/0a93aaf8/H0mwWr2os4Yxw_urkUUJn_WbLpaAte.png',
    prompt: 'preschool toddler animation style, ultra-simplified geometric character shapes with minimal detail, bold saturated primary colors red blue yellow green on clean backgrounds, gentle slow-paced movement with predictable rhythms, thick rounded outlines, large friendly faces with simple dot eyes and curved smiles, repetitive soothing visual patterns, toddler-focused simplicity with clean flat shapes, safe enclosed environments like playrooms and gardens, soft edges with no sharp corners, warm nurturing atmosphere for ages 2-5',
  },
  kids_flat_vector: {
    label: 'Flat Vector Kids',
    category: 'kids',
    description: 'Clean flat-design vector art, crisp geometric shapes, modern minimal illustration with bright fills',
    thumb: 'https://v3b.fal.media/files/b/0a93aafa/NNzR4lAtt_yU5JCLyusOc_2ec5clsS.png',
    prompt: 'flat vector kids animation style, clean crisp geometric shapes with no outlines, modern minimal illustration with solid bright color fills, smooth vector art characters with simplified proportions, trendy digital illustration aesthetic, neat organized compositions with generous white space, subtle shadow layers for depth, contemporary app-illustration quality, bright coral teal and sunshine yellow palette, satisfying smooth motion with clean easing curves, modern infographic-quality educational clarity',
  },
  kids_space: {
    label: 'Kids Space Adventure',
    category: 'kids',
    description: 'Cartoon outer space with friendly aliens, colorful planets, rocket ships, and twinkling star fields',
    thumb: 'https://v3b.fal.media/files/b/0a93aafa/JrJIm4ZFbeHDY-TcIDObZ_xpy2iVYn.png',
    prompt: 'kids space adventure animation, cartoon outer space with friendly round alien characters and cute robot sidekicks, colorful candy-bright planets with rings and craters, chunky retro-style rocket ships with porthole windows, dense twinkling star fields against deep purple-blue nebula backgrounds, floating asteroids and comets with sparkle trails, zero-gravity bouncy movement, warm cockpit interior lighting, exciting but safe exploration atmosphere, bold saturated cosmic color palette of purple teal orange and gold',
  },
  kids_action: {
    label: 'Kids Action',
    category: 'kids',
    description: 'Dynamic superhero energy with bold colors, speed lines, comic-panel transitions, and heroic poses',
    thumb: 'https://v3b.fal.media/files/b/0a93aafa/Pl565NJDVzjDYZxCyD7nX_OUwxFAGi.png',
    prompt: 'kids action adventure animation style, dynamic superhero energy with bold primary colors, exciting speed lines and motion blur on fast movements, comic-panel inspired transitions with POW and ZOOM effects, heroic power poses with dramatic low camera angles, bright saturated palette with strong contrast, cel-shaded lighting with clean bold shadows, energetic camera swoops and quick cuts, urban rooftop and secret base environments, confident young hero characters with expressive determined faces, exciting but age-appropriate action sequences',
  },
  kids_garden: {
    label: 'Whimsical Garden',
    category: 'kids',
    description: 'Miniature garden world with talking flowers, friendly bugs, dewdrop sparkles, and lush green magic',
    thumb: 'https://v3b.fal.media/files/b/0a93aafb/0PgaNlM4pcxBQvASyxbiH_sSNbI1f8.png',
    prompt: 'whimsical miniature garden animation, tiny characters exploring a lush oversized garden world, friendly smiling flowers and mushrooms with expressive faces, cute ladybug and caterpillar characters, sparkling morning dewdrops on leaves, warm dappled sunlight filtering through giant leaves, rich greens with pops of flower colors pink purple orange, gentle breeze making petals sway, macro-perspective camera angles looking up at towering dandelions, magical fairy-dust particles in warm air, peaceful nurturing nature atmosphere',
  },
  kids_city: {
    label: 'Kids City',
    category: 'kids',
    description: 'Colorful cartoon city with friendly vehicles, busy streets, playful architecture, and community energy',
    thumb: 'https://v3b.fal.media/files/b/0a93aafc/BjYbmLqVsPxg9jq3v4nIB_cZKdwXOz.png',
    prompt: 'colorful kids city animation, cheerful cartoon urban environment with rounded playful architecture in bright candy colors, friendly anthropomorphic vehicles with smiling faces, busy bustling streets with diverse child characters, shops and buildings with fun oversized signage, smooth traffic flow with bouncy vehicle animation, warm sunny day lighting with blue sky and fluffy clouds, fire trucks and buses and bikes in primary colors, community park and playground visible, safe welcoming neighborhood atmosphere, clean simple geometric building designs',
  },
  kids_stop_motion: {
    label: 'Kids Claymation',
    category: 'kids',
    description: 'Handmade clay and felt characters, visible thumbprint textures, warm craft studio lighting',
    thumb: 'https://v3b.fal.media/files/b/0a93aafc/XMAQyZmEce5QW89BaXU8e_aaxPj6BF.png',
    prompt: 'kids claymation stop motion animation, adorable handcrafted clay characters with visible thumbprint and fingermark textures, soft wool felt backgrounds and fabric props, warm practical studio lighting with gentle shadows, slightly wobbly charming frame-by-frame movement, miniature sets built from real craft materials like cardboard and buttons, bright primary-colored plasticine figures, cozy intimate scale, charming handmade claymation quality with expressive character personality, tactile real-world charm with imperfect endearing details',
  },
  kids_watercolor: {
    label: 'Kids Watercolor',
    category: 'kids',
    description: 'Soft watercolor washes with gentle color bleeding, dreamy hand-painted nature scenes, painterly charm',
    thumb: 'https://v3b.fal.media/files/b/0a93aafd/nKJPx3XwKQfHW-nmU57AV_p3Lj7oOb.png',
    prompt: 'soft watercolor kids animation style, gentle transparent color washes bleeding and blending on textured watercolor paper, dreamy hand-painted nature scenes with rolling green hills and puffy clouds, delicate wet-on-wet technique with happy accidents in color mixing, warm pastel palette of soft blue green peach and lavender, simple charming characters with watercolor texture visible in skin and clothing, peaceful flowing movement like paint spreading on wet paper, visible brushstrokes adding handmade warmth, delicate hand-painted picture book artistic quality',
  },
  kids_puppet: {
    label: 'Puppet Show',
    category: 'kids',
    description: 'Felt and fabric puppet characters on a miniature stage, curtain frames, warm theatrical lighting',
    thumb: 'https://v3b.fal.media/files/b/0a93aafd/-ql-jWxoIlPIrkT8hwy6o_epRlPHi4.png',
    prompt: 'puppet show kids animation, charming felt and fabric puppet characters with visible stitching and button eyes, miniature theatre stage with red velvet curtains as frame, warm theatrical spotlighting from above, handcrafted cardboard and painted backdrop scenery, gentle rod-puppet style movement with subtle bounce, soft muted color palette with rich fabric textures in corduroy velvet and burlap, cozy intimate performance atmosphere, classic educational puppet show aesthetic with friendly expressive characters, safe enclosed stage world with playful peek-a-boo entrances',
  },
};

export function getVideoStylePrompt(key) {
  if (!key || !VIDEO_STYLE_PRESETS[key]) return '';
  return VIDEO_STYLE_PRESETS[key].prompt;
}

export function listVideoStyles() {
  return Object.entries(VIDEO_STYLE_PRESETS).map(([key, v]) => ({
    key,
    label: v.label,
    category: v.category,
    thumb: v.thumb || '',
    description: v.description || '',
    prompt: v.prompt || '',
  }));
}
