/**
 * Video Style Presets — controls animation/motion feel.
 * Appended to the motion prompt when generating image-to-video clips.
 */

export const VIDEO_STYLE_PRESETS = {
  iphone_selfie: {
    label: 'Smartphone Selfie (Raw)',
    category: 'realistic',
    description: 'Handheld smartphone footage, natural room lighting, raw unfiltered look',
    thumb: 'https://v3b.fal.media/files/b/0a931548/4aPyLtiRJ_nJXIB4BOIBW.jpg',
    prompt: 'raw smartphone front-facing camera footage, handheld smartphone video with subtle micro-shake, natural ambient room lighting with soft window light on face, visible skin pores and texture, slight lens distortion at edges, authentic unfiltered color profile, relaxed genuine expression, casual everyday clothing with real fabric wrinkles',
  },
  iphone_selfie_walking: {
    label: 'Walking Selfie',
    category: 'realistic',
    description: 'Vlogging while walking through streets, natural handheld bounce, urban background blur',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/Ab_posBJa4jAD1o3HtGOq.jpg',
    prompt: 'person walking through busy city street filming selfie on smartphone, rhythmic handheld bounce from walking gait, urban storefronts and pedestrians blurring in background, natural daylight with overhead sun, authentic vlog-style framing with chin slightly cut off, wind affecting hair and audio, genuine conversational energy while moving, real street ambient sounds implied, slight lens flare from sun angle, raw unprocessed smartphone color profile',
  },
  iphone_selfie_car: {
    label: 'Car Selfie',
    category: 'realistic',
    description: 'Dashboard-mounted or handheld in car, natural window light, casual driving vlog feel',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/kzkBlqMfJ-kM5duDKVSX0.jpg',
    prompt: 'person filming selfie video inside car, dashboard or hand-held smartphone angle, natural window light casting directional shadows, car interior visible with seatbelt and steering wheel, slight vibration from engine or road, trees and buildings passing in window behind, authentic casual driving vlog aesthetic, warm filtered sunlight through windshield, relaxed conversational posture, genuine unscripted energy',
  },
  iphone_selfie_outdoor: {
    label: 'Outdoor Selfie',
    category: 'realistic',
    description: 'Park, beach or nature setting, bright natural sunlight, wind and open-air energy',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/DniBqRCgfjiTt3ajISksI.jpg',
    prompt: 'person filming outdoor selfie video at park or beach, bright natural sunlight with blue sky, green trees or ocean visible in background, wind blowing through hair, authentic smartphone front-camera quality with slight wide-angle distortion, genuine smile and relaxed outdoor energy, natural skin tones under direct sun, squinting slightly from brightness, birds or nature sounds implied, casual activewear or summer clothing',
  },
  ugc_testimonial: {
    label: 'UGC Testimonial',
    category: 'realistic',
    description: 'Person speaking to camera, soft ambient indoor lighting, authentic conversational feel',
    thumb: 'https://v3b.fal.media/files/b/0a931548/vwn7n5_DYC-SSyUw1VgJh.jpg',
    prompt: 'authentic user-generated testimonial video, real person speaking with natural speech cadence and breath pauses, subtle lip movements matching natural talking rhythm, genuine micro-expressions, real skin with natural imperfections and pores visible, soft ambient indoor lighting from overhead, believable casual setting with slight background depth, conversational eye contact',
  },
  ugc_unboxing: {
    label: 'Unboxing',
    category: 'realistic',
    description: 'Hands opening product packaging, table-top angle, genuine first reactions and excitement',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/F25D1GQZyFeVDwBFyvaFG.jpg',
    prompt: 'authentic unboxing video, hands carefully opening product packaging on table, overhead or angled table-top shot, tissue paper and branded box visible, genuine first-reaction expressions, warm indoor lighting from desk lamp, real skin texture on hands, product gradually revealed with anticipation, casual home desk or kitchen counter setting, natural ambient room sounds, authentic creator enthusiasm',
  },
  ugc_before_after: {
    label: 'Before & After',
    category: 'realistic',
    description: 'Transformation reveal, dramatic lighting shift, authentic results comparison',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/A2WBoSVPaF41PLzBgTvqh.jpg',
    prompt: 'before and after transformation video, dramatic visual comparison showing real results, slight lighting shift between states, authentic person showing genuine surprise or satisfaction, split-moment transition between before and after, natural indoor lighting, real skin texture and imperfections visible, honest unfiltered presentation, subtle emotional build from doubt to confidence, UGC testimonial authenticity',
  },
  ugc_storytime: {
    label: 'Storytime',
    category: 'realistic',
    description: 'Cozy sit-down confessional, warm lamp lighting, intimate personal narrative style',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/WiLh4SL32Hb0t9INyLOe3.jpg',
    prompt: 'intimate storytime sit-down video, person on couch or bed speaking directly to camera, warm lamp or fairy-light lighting creating cozy atmosphere, soft blankets and cushions visible, confessional personal narrative energy, genuine emotional micro-expressions, natural pauses and thoughtful looks, close framing on face and upper body, evening at-home ambiance, authentic vulnerability and connection with audience',
  },
  tiktok_style: {
    label: 'TikTok/Reels Style',
    category: 'realistic',
    description: 'Energetic creator content, ring light, expressive and vibrant social media aesthetic',
    thumb: 'https://v3b.fal.media/files/b/0a931548/r_c0kdMzJCSQRI77cgy90.jpg',
    prompt: 'vertical social media content creator video, direct-to-camera engagement with expressive natural facial movements, quick authentic reactions, real skin texture under ring light or natural window light, slightly warm color temperature, genuine personality showing through micro-expressions, natural hand gestures entering frame, energetic but believable body language',
  },
  tiktok_grwm: {
    label: 'GRWM (Get Ready With Me)',
    category: 'realistic',
    description: 'Vanity mirror setup, beauty ring light, makeup and styling routine, intimate creator content',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/qpQN97YgVEfe1CTslN-J8.jpg',
    prompt: 'get ready with me video at vanity mirror, beauty ring light creating even flattering illumination, cosmetics brushes and products scattered on counter, bathroom or bedroom setting, person applying makeup or styling hair, close-up detail shots of product application, warm intimate creator energy, mirror reflections adding depth, natural skin texture under beauty lighting, relaxed morning routine pace',
  },
  tiktok_pov: {
    label: 'POV Storytelling',
    category: 'realistic',
    description: 'First-person perspective, dramatic reveals, immersive point-of-view narrative',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/uwK0TWRR0EEUtwHW4y9Ca.jpg',
    prompt: 'first-person POV perspective video, camera as the viewer eyes, hand reaching into frame toward subject, dramatic reveal moments with suspenseful timing, immersive storytelling through perspective, dynamic movement through environment, short-form social media narrative style with emotional beats, cinematic lighting enhancing mood shifts, natural handheld motion, audience-as-character framing technique',
  },
  tiktok_tutorial: {
    label: 'Quick Tutorial',
    category: 'realistic',
    description: 'Step-by-step how-to, clean overhead or eye-level, clear instructional framing',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/jQEuHX9E31vm4FCYZJFWA.jpg',
    prompt: 'quick tutorial how-to video, clean overhead or eye-level shot of hands demonstrating steps, bright even lighting on workspace, clear visual focus on the process, numbered or sequential step progression, minimal clutter around demonstration area, instructional pacing with deliberate movements, social media content creator style, accessible and easy to follow framing, tools and materials neatly arranged',
  },
  facetime_call: {
    label: 'FaceTime/Video Call',
    category: 'realistic',
    description: 'Webcam angle from above, screen glow on face, casual at-home video call look',
    thumb: 'https://v3b.fal.media/files/b/0a931548/7wBSi1OSB8-PnQTpnEkqp.jpg',
    prompt: 'video call aesthetic shot from laptop webcam angle, slightly above eye level, natural indoor ambient lighting mixing with screen glow on face, casual at-home appearance, real skin texture with slight webcam softness, authentic conversational micro-expressions, relaxed posture, genuine unperformed body language, slight compression artifacts for realism',
  },
  cinematic: {
    label: 'Cinematic',
    category: 'professional',
    description: 'Film-quality look with anamorphic lens, teal-orange grade, and shallow depth of field',
    thumb: 'https://v3b.fal.media/files/b/0a931548/822Q5nGf3Q2dCmwNQzE_b.jpg',
    prompt: 'cinematic film quality shot on Arri Alexa, anamorphic framing feel, professional three-point lighting with soft key light creating gentle shadow fall-off, shallow depth of field with creamy bokeh separation, natural skin tones with subtle color grading, film-like motion cadence at 24fps, atmospheric haze catching light, precise composition with leading lines',
  },
  cinematic_golden_hour: {
    label: 'Golden Hour Cinematic',
    category: 'professional',
    description: 'Warm backlit magic hour, sun flares through trees, amber and honey tones, romantic epic feel',
    thumb: 'https://v3b.fal.media/files/b/0a937f3f/FMotizIqxUBhXu_iUmoMw.jpg',
    prompt: 'golden hour cinematic photography, warm backlit magic hour with sun low on horizon, amber and honey color palette, lens flares bursting through tree silhouettes, long dramatic shadows stretching across ground, soft diffused light wrapping around subjects, romantic epic atmosphere, shallow depth of field with golden bokeh, film-quality skin tones glowing in warm light, slow deliberate camera movement savoring the light',
  },
  cinematic_night: {
    label: 'Night Cinematic',
    category: 'professional',
    description: 'Neon-lit urban nightscape, moody blue tones, wet street reflections, atmospheric and brooding',
    thumb: 'https://v3b.fal.media/files/b/0a937f40/etLNjB9r-tmO1H5hvlptt.jpg',
    prompt: 'night cinematic urban photography, neon-lit city streets with wet pavement reflections, dominant blue and teal color palette with warm neon accents, moody atmospheric fog catching streetlight, puddle reflections creating mirror world, slow tracking shots through nighttime urban landscape, high ISO film grain adding texture, practical light sources creating pools of illumination, brooding contemplative atmosphere, rain-slicked surfaces glistening',
  },
  cinematic_anamorphic: {
    label: 'Anamorphic Widescreen',
    category: 'professional',
    description: 'Ultra-wide letterbox framing, horizontal lens flares, epic scale, Hollywood blockbuster feel',
    thumb: 'https://v3b.fal.media/files/b/0a937f40/aY-KpXiCIWXQfW60_B5rO.jpg',
    prompt: 'anamorphic widescreen cinematography, extreme 2.39:1 letterbox framing, horizontal blue lens flares stretching across frame, epic landscape establishing shots revealing vast scale, oval bokeh from anamorphic optics, subtle barrel distortion at frame edges, precise symmetrical composition, Hollywood blockbuster production value, sweeping slow camera movements, rich saturated color grading with crushed blacks, premium large-format visual grandeur',
  },
  documentary: {
    label: 'Documentary',
    category: 'professional',
    description: 'Handheld observational style, natural available light, muted journalistic tones',
    thumb: 'https://v3b.fal.media/files/b/0a931548/WOFDTOKaHt0L9UxR6wlkN.jpg',
    prompt: 'observational documentary style, handheld camera with natural stabilization, available light used authentically, candid unposed moments captured naturally, real environments with lived-in detail, natural skin tones without color grading, genuine emotional moments, ambient sound atmosphere, journalistic truthful aesthetic',
  },
  documentary_interview: {
    label: 'Sit-Down Interview',
    category: 'professional',
    description: 'Single camera, shallow depth of field, dark background, intimate talking-head format',
    thumb: 'https://v3b.fal.media/files/b/0a937f40/DWGpV2iox9uKBAVxBFwaz.jpg',
    prompt: 'sit-down documentary interview, single subject against dark or blurred background, shallow depth of field isolating the speaker, professional key light with subtle fill, thoughtful serious expression, intimate talking-head framing, slight over-the-shoulder angle suggesting off-camera interviewer, natural skin tones with documentary realism, quiet contemplative atmosphere, genuine emotional authenticity',
  },
  documentary_nature: {
    label: 'Nature Documentary',
    category: 'professional',
    description: 'Planet Earth quality, macro wildlife details, aerial vistas, lush and pristine natural world',
    thumb: 'https://v3b.fal.media/files/b/0a937f40/XHaQ25QrhG8YrksRl-l8r.jpg',
    prompt: 'premium nature documentary quality, breathtaking macro close-ups of wildlife with visible feather and fur texture, aerial drone shots over pristine landscapes, golden hour lighting on untouched wilderness, slow-motion animal movement capturing grace and power, rich saturated natural color palette, ambient natural sound atmosphere, intimate animal behavior moments, lush vegetation with morning dew, reverent awe-inspiring approach to the natural world',
  },
  documentary_street: {
    label: 'Street / Urban Doc',
    category: 'professional',
    description: 'Gritty handheld, real urban locations, available light, raw journalistic authenticity',
    thumb: 'https://v3b.fal.media/files/b/0a937f40/U9uLqzF3XiMC8GGZcHc6A.jpg',
    prompt: 'street documentary urban cinematography, gritty handheld camera with natural instability, real lived-in urban locations with character, available light only creating authentic atmosphere, graffiti walls and busy market scenes, raw journalistic approach capturing genuine moments, slightly desaturated muted color palette, candid unposed subjects in natural environment, ambient city soundscape implied, photojournalistic truth-telling aesthetic',
  },
  commercial: {
    label: 'Commercial/Ad',
    category: 'professional',
    description: 'Polished studio production, warm aspirational palette, premium clean composition',
    thumb: 'https://v3b.fal.media/files/b/0a931548/l-kPVFH0nkYpT7v2yZAah.jpg',
    prompt: 'high-end commercial production quality, precisely controlled studio lighting with soft diffusion, product and subject both in sharp focus, polished but natural-looking skin, aspirational warm color palette, smooth controlled camera movement, clean composition with visual breathing room, professional wardrobe and styling, premium feel',
  },
  commercial_luxury: {
    label: 'Luxury Brand Ad',
    category: 'professional',
    description: 'Slow-motion reveals, dark backgrounds, gold accents, ultra-premium high-end advertising',
    thumb: 'https://v3b.fal.media/files/b/0a937f41/XCCeQbcJLI157o6bqoPoa.jpg',
    prompt: 'luxury brand commercial cinematography, slow-motion product reveal against dark marble or velvet background, golden and champagne rim lighting creating premium glow, extreme attention to surface detail and material quality, deliberate unhurried pacing conveying exclusivity, rich blacks with warm metallic accent lighting, aspirational minimalist composition, macro shots of premium craftsmanship, silk and leather textures catching light, ultra-high-end advertising production value',
  },
  commercial_lifestyle: {
    label: 'Lifestyle Ad',
    category: 'professional',
    description: 'Aspirational family/friends, warm sunny energy, natural and inviting, feel-good brand content',
    thumb: 'https://v3b.fal.media/files/b/0a937f41/3DqUws5gfjE59Yt8Sq9gG.jpg',
    prompt: 'lifestyle brand commercial, happy people in sunlit aspirational settings, warm natural golden-hour lighting, genuine laughter and connection between subjects, bright airy home or outdoor environments, soft shallow depth of field creating dreamy separation, warm color palette with boosted vibrancy, smooth gimbal tracking following natural movement, feel-good positive energy, inclusive diverse casting, premium but approachable visual tone',
  },
  commercial_fast_paced: {
    label: 'Fast-Paced / Dynamic Ad',
    category: 'professional',
    description: 'Quick cuts, energetic motion blur, bold colors, high-energy action-packed advertising',
    thumb: 'https://v3b.fal.media/files/b/0a937f41/HQVC1UvYBKHlhby8Bv4WC.jpg',
    prompt: 'fast-paced dynamic commercial, rapid quick-cut editing rhythm, energetic motion blur on action moments, bold saturated neon and primary colors, athletic or high-energy subject matter, dramatic speed ramping from slow to fast, pumping bass-driven energy, graphic text overlays and bold typography feel, vibrant lighting with colored gels, adrenaline-fueled visual pacing, extreme angles and whip pans',
  },
  product_demo: {
    label: 'Product Demo',
    category: 'professional',
    description: 'Clean product on neutral background, even studio lighting, sharp detail-focused framing',
    thumb: 'https://v3b.fal.media/files/b/0a931549/b_nvyKFhMTJekyrAo5yK1.jpg',
    prompt: 'clean professional product demonstration, neutral background with soft gradient, even studio lighting revealing surface texture and material quality, smooth deliberate product handling with natural hand movements, clear visual focus on product features, slight reflection on surface below, precise framing with product as hero',
  },
  product_demo_hands_on: {
    label: 'Hands-On Demo',
    category: 'professional',
    description: 'Human hands interacting with product, close-up tactile engagement, real usage demonstration',
    thumb: 'https://v3b.fal.media/files/b/0a937f41/kBGv7rKaNMVSurK4MED-R.jpg',
    prompt: 'hands-on product demonstration video, real human hands interacting naturally with product, close-up shots of fingers pressing buttons and sliding controls, tactile engagement showing weight and texture, warm studio lighting from above, clean workspace with product as hero, deliberate demonstrative movements showing functionality, authentic usage scenario, natural hand skin with real texture, practical real-world interaction feel',
  },
  product_demo_macro: {
    label: 'Macro Detail Shot',
    category: 'professional',
    description: 'Extreme close-up of product surface, shallow DOF, premium material textures, meticulous detail',
    thumb: 'https://v3b.fal.media/files/b/0a937f41/gySc5cUdgeGewxnFU8b0i.jpg',
    prompt: 'extreme macro close-up product detail, razor-thin depth of field revealing surface texture and material quality, brushed metal grain or glass reflections or fabric weave visible, precision studio lighting with soft gradients across surface, slow rack focus between product details, premium material craftsmanship highlighted, color-accurate neutral lighting, every scratch and reflection intentional, meticulous attention to manufacturing detail, luxury product photography at maximum magnification',
  },
  product_demo_360: {
    label: '360 Product Spin',
    category: 'professional',
    description: 'Rotating turntable, clean backdrop, even lighting, complete product overview from all angles',
    thumb: 'https://v3b.fal.media/files/b/0a937f42/2SRZ5p0I9g7QHSauEvsoe.jpg',
    prompt: 'product 360-degree spin on turntable, clean white or gradient backdrop, perfectly even studio lighting eliminating harsh shadows, smooth continuous rotation revealing all angles, slight reflection on glossy surface below, professional e-commerce photography style, crisp sharp focus maintained throughout rotation, neutral color-accurate lighting, product floating hero composition, every angle and detail systematically revealed',
  },
  dreamy: {
    label: 'Dreamy/Ethereal',
    category: 'artistic',
    description: 'Soft diffusion glow, pastel palette, golden bokeh, and romantic overexposed highlights',
    thumb: 'https://v3b.fal.media/files/b/0a931549/rO3udTKiuzVwD_CO3DCBc.jpg',
    prompt: 'ethereal dreamlike quality with soft diffusion filter effect, gentle overexposed highlights wrapping around subject, pastel and desaturated color palette, slow graceful movement, subtle lens glow on light sources, delicate bokeh orbs in background, romantic golden or blue hour natural light, flowing fabric or hair movement suggesting gentle breeze',
  },
  dreamy_fairy_tale: {
    label: 'Fairy Tale',
    category: 'artistic',
    description: 'Enchanted forest, magical golden particles, soft dappled sunlight, mystical storybook wonder',
    thumb: 'https://v3b.fal.media/files/b/0a937f42/M9P27cNjJeYY8uOyWlXWo.jpg',
    prompt: 'enchanted fairy tale forest cinematography, magical golden particles and fireflies floating through air, soft dappled sunlight filtering through ancient moss-covered trees, mystical atmosphere with gentle fog at ground level, storybook illustration quality brought to life, warm golden and emerald green color palette, slow ethereal camera movement gliding through enchanted woodland, delicate flower petals drifting on breeze, fantasy world made tangible, childlike wonder and magic in every frame',
  },
  dreamy_golden_haze: {
    label: 'Golden Haze',
    category: 'artistic',
    description: 'Warm backlit haze, sun flare through hair, romantic soft focus, amber honey tones',
    thumb: 'https://v3b.fal.media/files/b/0a937f42/GcJeqSpntU1j2GlGOWfvj.jpg',
    prompt: 'golden haze romantic cinematography, warm backlit diffusion creating glowing halo around subject, sun flare bursting through hair and fabric, amber and honey color tones dominating palette, romantic soft focus with pro-mist filter quality, gentle overexposed highlights bleeding into shadows, slow graceful movement, wheat fields or meadow setting bathed in warm light, lens glow on every light source, intimate love-story visual language',
  },
  dreamy_underwater: {
    label: 'Underwater Dream',
    category: 'artistic',
    description: 'Slow-motion submerged look, light caustics dancing, flowing fabric, serene aquatic weightlessness',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/8oN9W1pFUtQkV8YgpUh49.jpg',
    prompt: 'underwater dream sequence cinematography, slow-motion movement through turquoise water, light caustics dancing on surfaces and skin, flowing fabric and hair suspended weightlessly, tiny bubbles catching and refracting light, serene peaceful submerged atmosphere, aquamarine and teal color palette, ethereal weightlessness in every motion, shafts of sunlight penetrating from surface above, graceful ballet-like movement, surreal dreamworld beneath the surface',
  },
  vintage: {
    label: 'Vintage/Retro',
    category: 'artistic',
    description: '16mm film grain, warm amber tones, vignette edges, and lifted nostalgic blacks',
    thumb: 'https://v3b.fal.media/files/b/0a931549/yl-LFzXU8X1B4tPokgQB0.jpg',
    prompt: 'authentic vintage 16mm film aesthetic, warm amber color shift with faded blacks lifted to milky grey, organic film grain texture visible on skin and surfaces, slight vignette darkening at frame edges, period-appropriate soft focus quality, gentle gate weave and frame instability, nostalgic halation around bright highlights',
  },
  vintage_70s: {
    label: '70s Film',
    category: 'artistic',
    description: 'Warm orange-brown palette, soft film grain, retro decor, golden nostalgic warmth',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/26yE3PKUr0oePyeF10KR9.jpg',
    prompt: '1970s film aesthetic cinematography, warm orange amber and brown color palette with faded saturation, soft organic film grain visible across frame, golden warm tones dominating highlights, period-appropriate soft focus quality from vintage lenses, retro decor and warm wood tones in environment, gentle halation around bright light sources, nostalgic analog warmth, slightly lifted blacks with milky shadow tone, Kodak Ektachrome color science feel',
  },
  vintage_vhs: {
    label: '80s VHS',
    category: 'artistic',
    description: 'Scan lines, tracking artifacts, neon pink-cyan palette, CRT glow, synthwave nostalgia',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/1g7G1Ms36bwUlSucPR5gx.jpg',
    prompt: '1980s VHS tape recording aesthetic, visible horizontal scan lines across frame, intermittent tracking artifacts and static distortion, neon pink cyan and electric blue color palette, CRT television phosphor glow quality, synthwave retro-futuristic vibes, analog video noise and color bleeding, date-time stamp in corner, slightly blurry soft focus from magnetic tape degradation, Saturday morning TV nostalgia, deliberate lo-fi analog charm',
  },
  vintage_super8: {
    label: 'Super 8mm',
    category: 'artistic',
    description: 'Heavy film grain, gate weave, blown highlights, intimate home-movie nostalgia',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/H7obnR5LWORxjs_U7rwKG.jpg',
    prompt: 'Super 8mm home movie footage aesthetic, heavy visible film grain with dancing texture, gate weave causing subtle frame instability, blown-out overexposed highlights with warm amber tint, narrow depth of field from small format, intimate personal home-movie quality, light leaks and exposure fluctuations, slightly sped-up motion cadence, rounded vignette at frame corners, scratches and dust artifacts, deeply nostalgic personal memory quality',
  },
  noir: {
    label: 'Film Noir',
    category: 'artistic',
    description: 'High contrast chiaroscuro, dramatic shadows, venetian blind patterns, atmospheric smoke',
    thumb: 'https://v3b.fal.media/files/b/0a931549/GNvgxVWjhFc0ZXHtddWii.jpg',
    prompt: 'classic film noir cinematography, high contrast chiaroscuro lighting with deep blacks and bright specular highlights, dramatic single key light source creating long shadows, venetian blind shadow patterns, smoke or atmospheric haze catching light beams, moody monochromatic or desaturated cool palette, low-key lighting revealing only essential details',
  },
  noir_neo: {
    label: 'Neo-Noir',
    category: 'artistic',
    description: 'Modern city rain, neon through venetian blinds, teal-magenta accents, contemporary dark thriller',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/K8a8kxUT1gwY9I5CjSt17.jpg',
    prompt: 'neo-noir modern cinematography, contemporary city at night with rain on windows, neon signage casting colored light through venetian blinds creating stripe patterns, teal and magenta color accents against deep blacks, wet reflective surfaces everywhere, updated noir aesthetic with modern architecture, surveillance camera angles and voyeuristic framing, moody atmospheric tension, practical neon light sources, rain-soaked urban dystopia visual language',
  },
  noir_detective: {
    label: 'Detective / Mystery',
    category: 'artistic',
    description: 'Evidence and clues in spotlight, smoke wisps, suspenseful reveals, classic mystery atmosphere',
    thumb: 'https://v3b.fal.media/files/b/0a937f43/Shsh4nK3LgYurKAq36-W7.jpg',
    prompt: 'detective mystery noir cinematography, dramatic spotlight illuminating evidence and clues on desk, wisps of cigarette smoke curling through light beams, magnifying glass and case files, suspenseful reveal pacing with slow deliberate camera pushes, dark shadows concealing most of frame, warm amber desk lamp as sole light source, noir thriller tension and intrigue, mysterious atmosphere where every shadow hides secrets, classic whodunit visual storytelling',
  },
  noir_silhouette: {
    label: 'Silhouette / Shadow Play',
    category: 'artistic',
    description: 'Stark backlit figures, long dramatic shadows, minimal detail, high-contrast light and dark',
    thumb: 'https://v3b.fal.media/files/b/0a937f44/3xO_4ggmv4LgujA282C6Y.jpg',
    prompt: 'silhouette shadow play cinematography, stark backlit figures reduced to pure black shapes against bright background, long dramatic shadows stretching across walls and floors, extreme high-contrast with virtually no midtones, minimal visible detail forcing imagination, venetian blind stripe shadows across surfaces, single powerful backlight as sole source, mysterious anonymous figures, graphic bold composition, visual storytelling through shape and shadow alone',
  },
  anime: {
    label: 'Anime Style',
    category: 'artistic',
    description: 'Vibrant cel-shaded animation, expressive characters, detailed backgrounds, dynamic angles',
    thumb: 'https://v3b.fal.media/files/b/0a931549/gVmrP3xeHjdNrp3T2qOHk.jpg',
    prompt: 'high-quality anime art style animation, vibrant saturated color palette, expressive character animation with fluid motion, dynamic speed lines and impact frames, detailed background art with atmospheric perspective, cel-shaded lighting with crisp shadow edges, wind-blown hair and clothing movement, dramatic camera angles',
  },
  faceless_cinematic: {
    label: 'Faceless Cinematic',
    category: 'faceless',
    description: 'No people — dramatic landscapes, objects, and environments with cinematic framing',
    thumb: 'https://v3b.fal.media/files/b/0a937140/wVaaSs_tJKc4rXX0_QfA8.jpg',
    prompt: 'cinematic establishing shots without any people or faces, sweeping landscape and environment cinematography, dramatic lighting with volumetric rays, slow controlled camera movement, atmospheric depth and haze, professional color grading with rich contrast, detailed textures on surfaces and materials, no human figures visible',
  },
  faceless_tech: {
    label: 'Faceless Tech',
    category: 'faceless',
    description: 'No people — screens, circuits, data visualizations, and futuristic tech imagery',
    thumb: 'https://v3b.fal.media/files/b/0a937140/6-tSIuVwEj7ClNuj-nTnq.jpg',
    prompt: 'technology-focused visuals without any people or faces, glowing screens and holographic displays, circuit boards and server rooms, data visualization and flowing code, cool blue and neon accent lighting, clean modern environments, close-up macro shots of tech components, futuristic laboratory aesthetic',
  },
  faceless_nature: {
    label: 'Faceless Nature',
    category: 'faceless',
    description: 'No people — stunning nature footage, macro details, aerial landscapes',
    thumb: 'https://v3b.fal.media/files/b/0a937140/8qIkQ0farGhW2KnxxcdJA.jpg',
    prompt: 'breathtaking nature cinematography without any people or faces, macro close-ups of natural textures and organisms, aerial drone establishing shots, golden hour and blue hour lighting, time-lapse quality cloud and water movement, rich saturated earthy color palette, intimate botanical and geological details',
  },
  faceless_abstract: {
    label: 'Faceless Abstract',
    category: 'faceless',
    description: 'No people — abstract shapes, particles, gradients, and motion graphics feel',
    thumb: 'https://v3b.fal.media/files/b/0a937140/RM6aJ7NLVI5qIP4o6fM9h.jpg',
    prompt: 'abstract visual art without any people or faces, flowing particle systems and geometric shapes, smooth gradient color transitions, organic fluid simulations, light trails and bokeh orbs, minimalist composition with negative space, ethereal atmospheric glow effects, hypnotic repeating patterns',
  },
  faceless_dark: {
    label: 'Faceless Dark/Horror',
    category: 'faceless',
    description: 'No people — eerie environments, shadows, abandoned spaces, atmospheric dread',
    thumb: 'https://v3b.fal.media/files/b/0a937140/1Z8T2zploTKhVnPVCQ1KU.jpg',
    prompt: 'dark atmospheric visuals without any people or faces, abandoned spaces and decaying architecture, deep shadows with minimal light sources, fog and mist obscuring details, desaturated cold color palette, subtle movement in darkness, eerie environmental textures, oppressive low-key lighting creating sense of dread',
  },
  motion_graphics: {
    label: 'Motion Graphics',
    category: 'faceless',
    description: 'No people — infographic-style with bold shapes, icons, and kinetic typography feel',
    thumb: 'https://v3b.fal.media/files/b/0a937141/l592R5nxcNJuLo_U47Og6.jpg',
    prompt: 'clean motion graphics style without any people or faces, bold geometric shapes and flat design elements, smooth kinetic transitions between scenes, infographic-inspired data presentation, vibrant contrasting color blocks, isometric perspective illustrations, minimalist icons and symbols, professional broadcast quality',
  },
  stock_footage: {
    label: 'Stock B-Roll',
    category: 'faceless',
    description: 'No people — generic professional B-roll style, versatile and clean',
    thumb: 'https://v3b.fal.media/files/b/0a937141/tIl66bizkF1F4iebjmOmL.jpg',
    prompt: 'professional stock footage style without any people or faces, clean well-lit environments, versatile generic scenes suitable for voiceover, smooth stabilized camera movement, neutral color grading, offices desks and workspaces, city skylines and traffic, everyday objects and environments shot professionally',
  },

  // ── Realistic ──

  vlog_bts: {
    label: 'Vlog / Behind-the-Scenes',
    category: 'realistic',
    description: 'Casual creator content, messy creative workspace, authentic unscripted handheld feel',
    thumb: 'https://v3b.fal.media/files/b/0a937239/0uSlA448KlBWXoHgBdA2n.jpg',
    prompt: 'casual vlog behind-the-scenes footage, handheld camera with natural wobble, authentic messy creative workspace visible, natural ambient lighting mixed with screen glow, genuine unscripted moments, visible camera gear and equipment in background, relaxed conversational energy, raw color profile without heavy grading, real textures and imperfections, informal framing with subject slightly off-center',
  },
  podcast_interview: {
    label: 'Podcast / Interview',
    category: 'realistic',
    description: 'Studio podcast setup, professional microphones, warm broadcast lighting, conversational framing',
    thumb: 'https://v3b.fal.media/files/b/0a937239/Vf0e669pFRyivxdpm0aCF.jpg',
    prompt: 'professional podcast interview setup, studio-quality condenser microphones visible, acoustic treatment panels in background, warm diffused studio lighting with subtle hair light, conversational two-shot or over-shoulder framing, shallow depth of field isolating speakers, clean broadcast color grade, genuine eye contact and natural speech gestures, professional but intimate atmosphere',
  },

  // ── Professional ──

  corporate_training: {
    label: 'Corporate / Training',
    category: 'professional',
    description: 'Clean office environment, professional presenter, even lighting, business aesthetic',
    thumb: 'https://v3b.fal.media/files/b/0a937239/D9dEDR4y752Fgzb0cKWxe.jpg',
    prompt: 'corporate training video production, clean modern office or meeting room environment, even professional lighting without harsh shadows, presenter in business attire with confident posture, neutral background with subtle branding, sharp focus on subject, whiteboard or screen graphics visible, steady tripod shot with occasional slow zoom, muted professional color palette, clear and authoritative visual tone',
  },
  real_estate: {
    label: 'Real Estate Tour',
    category: 'professional',
    description: 'Architectural walkthroughs, wide-angle interiors, golden hour light, aspirational lifestyle',
    thumb: 'https://v3b.fal.media/files/b/0a937239/u52nlYgQ9vC3i3GvJOYhF.jpg',
    prompt: 'luxury real estate tour cinematography, wide-angle architectural shots revealing full room depth, smooth gimbal walkthrough movement, golden hour light streaming through large windows, polished interior design with staged furniture, high dynamic range capturing bright windows and dark corners, slow controlled panning to reveal spaces, aspirational lifestyle composition, warm inviting color grade, drone exterior establishing shots',
  },

  // ── Artistic ──

  cyberpunk_neon: {
    label: 'Cyberpunk / Neon',
    category: 'artistic',
    description: 'Rain-soaked neon streets, holographic elements, purple-cyan palette, futuristic noir',
    thumb: 'https://v3b.fal.media/files/b/0a937239/pxeHpN8hrepuhn0D-0tPe.jpg',
    prompt: 'cyberpunk neon-drenched cinematography, rain-slicked streets reflecting vibrant neon signage, holographic advertisements and digital overlays, dominant purple cyan and magenta color palette, atmospheric fog catching colored light beams, dystopian megacity urban density, low-angle shots emphasizing towering architecture, lens flares from neon sources, moody futuristic noir atmosphere, high contrast with deep blacks',
  },
  fantasy_epic: {
    label: 'Fantasy / Epic',
    category: 'artistic',
    description: 'Sweeping mythical landscapes, dramatic storm lighting, majestic scale, cinematic grandeur',
    thumb: 'https://v3b.fal.media/files/b/0a937239/tjx-NcGOHyEIRqyGchrSW.jpg',
    prompt: 'epic fantasy cinematography with sweeping landscape vistas, dramatic volumetric light breaking through storm clouds, towering castles and mythical architecture, majestic mountain ranges with atmospheric perspective, slow aerial establishing shots revealing vast scale, rich saturated earthy and golden color palette, cinematic lens flares on practical light sources, fog rolling through valleys, high fantasy grandeur and reverence for nature',
  },
  stop_motion: {
    label: 'Stop Motion',
    category: 'artistic',
    description: 'Claymation feel, handcrafted miniature sets, tactile textures, charming frame-by-frame motion',
    thumb: 'https://v3b.fal.media/files/b/0a93723a/dQANWEjZxlvlzX-oHfIFI.jpg',
    prompt: 'stop motion claymation animation style, handcrafted characters with visible fingerprint textures in clay, miniature practical sets with real materials, warm directional lighting creating soft shadows on figures, slightly jerky frame-by-frame motion cadence, charming imperfections in movement, premium studio-quality claymation craftsmanship, shallow depth of field on miniature scale, cozy intimate atmosphere',
  },
  watercolor_painterly: {
    label: 'Watercolor / Painterly',
    category: 'artistic',
    description: 'Soft flowing pigments, translucent washes, visible brush textures, dreamy painted aesthetic',
    thumb: 'https://v3b.fal.media/files/b/0a93723a/UoOiRUfcP2fNNxzaZoUq5.jpg',
    prompt: 'watercolor painting animation style, soft flowing pigment washes with translucent color layers, visible paper texture beneath paint, dreamy botanical and natural scenes, gentle pastel and muted color palette, organic bleeding edges where colors meet, delicate brushwork visible in details, slow ethereal movement suggesting wind through painted landscapes, artistic hand-painted quality with intentional imperfections',
  },

  // ── Faceless ──

  faceless_food: {
    label: 'Faceless Food/Cooking',
    category: 'faceless',
    description: 'No people — overhead food styling, macro ingredient details, warm kitchen lighting',
    thumb: 'https://v3b.fal.media/files/b/0a93723a/P6-2Fm7M3FHFP7AXV-V8Y.jpg',
    prompt: 'professional food cinematography without any people or faces, overhead flat-lay plating shots, macro close-ups of fresh ingredients with visible texture, steam rising from hot dishes, warm kitchen lighting with golden tones, smooth slow-motion pours and drizzles, clean marble or wood surfaces, vibrant appetizing color saturation, professional food styling with garnish details, ASMR-quality visual intimacy',
  },
  faceless_travel: {
    label: 'Faceless Travel',
    category: 'faceless',
    description: 'No people — aerial landscapes, turquoise waters, golden-hour destinations, wanderlust aesthetic',
    thumb: 'https://v3b.fal.media/files/b/0a93723a/LL7O8gqJndCoVjqbDWc2f.jpg',
    prompt: 'stunning travel cinematography without any people or faces, aerial drone shots over turquoise ocean and tropical islands, golden-hour landscapes with long shadows, establishing shots of iconic destinations, smooth hyperlapse through scenic routes, vibrant saturated wanderlust color palette, time-lapse sunsets and cloud formations, underwater coral reef glimpses, sweeping mountain and valley panoramas, aspirational bucket-list visual quality',
  },
  faceless_luxury: {
    label: 'Faceless Luxury/Lifestyle',
    category: 'faceless',
    description: 'No people — premium products, marble surfaces, golden accents, editorial brand photography',
    thumb: 'https://v3b.fal.media/files/b/0a93723a/6oXKtIVZSQ8NQAJOdexlB.jpg',
    prompt: 'luxury lifestyle product cinematography without any people or faces, premium objects on marble and dark surfaces, golden and rose-gold accent lighting, soft bokeh background with warm tones, editorial brand photography aesthetic, slow deliberate reveal of luxury details, designer items with precise composition, warm amber and champagne color palette, aspirational minimalist framing with generous negative space, high-end catalog quality',
  },

  // ── Kids & Education ──

  kids_cartoon: {
    label: 'Kids Cartoon',
    category: 'kids',
    description: 'Bright friendly animation, big expressive eyes, vibrant primary colors, cheerful wholesome feel',
    thumb: 'https://v3b.fal.media/files/b/0a93723b/aLF65T33tf8yPztJIM8jF.jpg',
    prompt: 'colorful kids cartoon animation style, bright friendly characters with big expressive eyes and rounded features, vibrant primary color palette with cheerful saturation, smooth clean outlines, sunny welcoming environments, playful bouncy movement energy, modern 2D preschool animation aesthetic with bold shapes and clean linework, simple readable compositions for young audiences, wholesome positive atmosphere, soft shadows and gentle lighting',
  },
  kids_3d_animation: {
    label: '3D Kids Animation',
    category: 'kids',
    description: 'Premium 3D animation studio quality with soft lighting, rounded characters, vibrant colorful worlds',
    thumb: 'https://v3b.fal.media/files/b/0a93a83d/VdyZcvJXsIocbiRpR-_Sg.jpg',
    prompt: 'premium 3D animated kids style with studio-quality production value, soft rounded character designs with expressive oversized eyes and smooth plastic-like skin textures, vibrant saturated color palette with candy-bright hues, warm diffused global illumination with soft ambient occlusion, playful bouncy character animation with squash and stretch principles, richly detailed miniature environments with depth of field bokeh, volumetric lighting with gentle god rays, whimsical props and exaggerated proportions, cheerful uplifting atmosphere, clean crisp rendering with subtle subsurface scattering on skin',
  },
  whiteboard_explainer: {
    label: 'Whiteboard / Explainer',
    category: 'kids',
    description: 'Hand-drawn diagrams on white background, marker illustrations, clean educational infographic style',
    thumb: 'https://v3b.fal.media/files/b/0a93723b/xP9F4hMBg7Si8FixHRT4w.jpg',
    prompt: 'whiteboard explainer animation style, hand drawing black marker illustrations on clean white background, simple icons diagrams and arrows appearing progressively, educational infographic visual language, kinetic hand-drawn presentation style, minimal color accents highlighting key concepts, smooth drawing motion revealing ideas step by step, clean readable typography, professional knowledge-sharing aesthetic',
  },
  kids_fairy_tale: {
    label: 'Fairy Tale',
    category: 'kids',
    description: 'Enchanted storybook world with castles, magical creatures, soft golden glow and dreamy sparkle effects',
    thumb: 'https://v3b.fal.media/files/b/0a93aaf8/UuiNtQ9cwUECCYYnlBPT1_KOssr1q4.png',
    prompt: 'enchanted fairy tale animation style, magical storybook kingdom with turreted castles and winding forest paths, soft golden hour glow with sparkling particle effects, gentle pastel color palette with warm pinks purples and golds, friendly magical creatures with big expressive eyes, dreamy atmospheric haze and floating fireflies, lush hand-painted watercolor backgrounds, smooth gentle camera movements through enchanted landscapes, whimsical stardust transitions, safe warm inviting atmosphere for young viewers',
  },
  kids_storybook: {
    label: 'Storybook Illustration',
    category: 'kids',
    description: 'Hand-painted watercolor pages coming to life, soft edges, gentle pastel tones, bedtime story warmth',
    thumb: 'https://v3b.fal.media/files/b/0a93aaf8/49zRUMiLrNKfX-iqWIPx-_cBKEM46z.png',
    prompt: 'children storybook illustration animation, hand-painted watercolor pages gently coming to life, soft feathered edges with visible paper texture, warm pastel color palette of peach mint lavender and buttercup yellow, charming simple character designs with round heads and dot eyes, cozy domestic scenes with patterned quilts and window light, gentle page-turn transitions, slow calming camera pans across illustrated landscapes, bedtime story warmth and comfort, nostalgic picture book quality',
  },
  kids_educational: {
    label: 'Kids Educational',
    category: 'kids',
    description: 'Fun learning animation with labeled diagrams, counting objects, colorful infographic elements',
    thumb: 'https://v3b.fal.media/files/b/0a93aaf8/Ve5WkKaylx6OMD0CVb6O3_JYTXoEQA.png',
    prompt: 'fun educational kids animation style, colorful labeled diagrams and infographic elements appearing playfully, counting objects bouncing into frame, bright primary color backgrounds with clean graphic design, friendly presenter character with simple rounded features, text and numbers animating with pop and bounce effects, clear visual hierarchy for learning concepts, interactive quiz-show energy, curriculum-friendly presentation with engaging visual mnemonics, engaging children educational TV entertainment quality',
  },
  kids_preschool: {
    label: 'Preschool',
    category: 'kids',
    description: 'Ultra-simple shapes and bold primary colors, gentle slow pacing, toddler-friendly animation style',
    thumb: 'https://v3b.fal.media/files/b/0a93aaf8/H0mwWr2os4Yxw_urkUUJn_WbLpaAte.png',
    prompt: 'preschool toddler animation style, ultra-simplified geometric character shapes with minimal detail, bold saturated primary colors red blue yellow green on clean backgrounds, gentle slow-paced movement with predictable rhythms, thick rounded outlines, large friendly faces with simple dot eyes and curved smiles, repetitive soothing visual patterns, toddler-focused simplicity with clean flat shapes, safe enclosed environments like playrooms and gardens, soft edges with no sharp corners, warm nurturing atmosphere for ages 2-5',
  },
  kids_flat_vector: {
    label: 'Flat Vector Kids',
    category: 'kids',
    description: 'Clean flat-design vector art, crisp geometric shapes, modern minimal illustration with bright fills',
    thumb: 'https://v3b.fal.media/files/b/0a93aafa/NNzR4lAtt_yU5JCLyusOc_2ec5clsS.png',
    prompt: 'flat vector kids animation style, clean crisp geometric shapes with no outlines, modern minimal illustration with solid bright color fills, smooth vector art characters with simplified proportions, trendy digital illustration aesthetic, neat organized compositions with generous white space, subtle shadow layers for depth, contemporary app-illustration quality, bright coral teal and sunshine yellow palette, satisfying smooth motion with clean easing curves, modern infographic-quality educational clarity',
  },
  kids_space: {
    label: 'Kids Space Adventure',
    category: 'kids',
    description: 'Cartoon outer space with friendly aliens, colorful planets, rocket ships, and twinkling star fields',
    thumb: 'https://v3b.fal.media/files/b/0a93aafa/JrJIm4ZFbeHDY-TcIDObZ_xpy2iVYn.png',
    prompt: 'kids space adventure animation, cartoon outer space with friendly round alien characters and cute robot sidekicks, colorful candy-bright planets with rings and craters, chunky retro-style rocket ships with porthole windows, dense twinkling star fields against deep purple-blue nebula backgrounds, floating asteroids and comets with sparkle trails, zero-gravity bouncy movement, warm cockpit interior lighting, exciting but safe exploration atmosphere, bold saturated cosmic color palette of purple teal orange and gold',
  },
  kids_action: {
    label: 'Kids Action',
    category: 'kids',
    description: 'Dynamic superhero energy with bold colors, speed lines, comic-panel transitions, and heroic poses',
    thumb: 'https://v3b.fal.media/files/b/0a93aafa/Pl565NJDVzjDYZxCyD7nX_OUwxFAGi.png',
    prompt: 'kids action adventure animation style, dynamic superhero energy with bold primary colors, exciting speed lines and motion blur on fast movements, comic-panel inspired transitions with POW and ZOOM effects, heroic power poses with dramatic low camera angles, bright saturated palette with strong contrast, cel-shaded lighting with clean bold shadows, energetic camera swoops and quick cuts, urban rooftop and secret base environments, confident young hero characters with expressive determined faces, exciting but age-appropriate action sequences',
  },
  kids_garden: {
    label: 'Whimsical Garden',
    category: 'kids',
    description: 'Miniature garden world with talking flowers, friendly bugs, dewdrop sparkles, and lush green magic',
    thumb: 'https://v3b.fal.media/files/b/0a93aafb/0PgaNlM4pcxBQvASyxbiH_sSNbI1f8.png',
    prompt: 'whimsical miniature garden animation, tiny characters exploring a lush oversized garden world, friendly smiling flowers and mushrooms with expressive faces, cute ladybug and caterpillar characters, sparkling morning dewdrops on leaves, warm dappled sunlight filtering through giant leaves, rich greens with pops of flower colors pink purple orange, gentle breeze making petals sway, macro-perspective camera angles looking up at towering dandelions, magical fairy-dust particles in warm air, peaceful nurturing nature atmosphere',
  },
  kids_city: {
    label: 'Kids City',
    category: 'kids',
    description: 'Colorful cartoon city with friendly vehicles, busy streets, playful architecture, and community energy',
    thumb: 'https://v3b.fal.media/files/b/0a93aafc/BjYbmLqVsPxg9jq3v4nIB_cZKdwXOz.png',
    prompt: 'colorful kids city animation, cheerful cartoon urban environment with rounded playful architecture in bright candy colors, friendly anthropomorphic vehicles with smiling faces, busy bustling streets with diverse child characters, shops and buildings with fun oversized signage, smooth traffic flow with bouncy vehicle animation, warm sunny day lighting with blue sky and fluffy clouds, fire trucks and buses and bikes in primary colors, community park and playground visible, safe welcoming neighborhood atmosphere, clean simple geometric building designs',
  },
  kids_stop_motion: {
    label: 'Kids Claymation',
    category: 'kids',
    description: 'Handmade clay and felt characters, visible thumbprint textures, warm craft studio lighting',
    thumb: 'https://v3b.fal.media/files/b/0a93aafc/XMAQyZmEce5QW89BaXU8e_aaxPj6BF.png',
    prompt: 'kids claymation stop motion animation, adorable handcrafted clay characters with visible thumbprint and fingermark textures, soft wool felt backgrounds and fabric props, warm practical studio lighting with gentle shadows, slightly wobbly charming frame-by-frame movement, miniature sets built from real craft materials like cardboard and buttons, bright primary-colored plasticine figures, cozy intimate scale, charming handmade claymation quality with expressive character personality, tactile real-world charm with imperfect endearing details',
  },
  kids_watercolor: {
    label: 'Kids Watercolor',
    category: 'kids',
    description: 'Soft watercolor washes with gentle color bleeding, dreamy hand-painted nature scenes, painterly charm',
    thumb: 'https://v3b.fal.media/files/b/0a93aafd/nKJPx3XwKQfHW-nmU57AV_p3Lj7oOb.png',
    prompt: 'soft watercolor kids animation style, gentle transparent color washes bleeding and blending on textured watercolor paper, dreamy hand-painted nature scenes with rolling green hills and puffy clouds, delicate wet-on-wet technique with happy accidents in color mixing, warm pastel palette of soft blue green peach and lavender, simple charming characters with watercolor texture visible in skin and clothing, peaceful flowing movement like paint spreading on wet paper, visible brushstrokes adding handmade warmth, delicate hand-painted picture book artistic quality',
  },
  kids_puppet: {
    label: 'Puppet Show',
    category: 'kids',
    description: 'Felt and fabric puppet characters on a miniature stage, curtain frames, warm theatrical lighting',
    thumb: 'https://v3b.fal.media/files/b/0a93aafd/-ql-jWxoIlPIrkT8hwy6o_epRlPHi4.png',
    prompt: 'puppet show kids animation, charming felt and fabric puppet characters with visible stitching and button eyes, miniature theatre stage with red velvet curtains as frame, warm theatrical spotlighting from above, handcrafted cardboard and painted backdrop scenery, gentle rod-puppet style movement with subtle bounce, soft muted color palette with rich fabric textures in corduroy velvet and burlap, cozy intimate performance atmosphere, classic educational puppet show aesthetic with friendly expressive characters, safe enclosed stage world with playful peek-a-boo entrances',
  },
};

export function getVideoStylePrompt(key) {
  if (!key || !VIDEO_STYLE_PRESETS[key]) return '';
  return VIDEO_STYLE_PRESETS[key].prompt;
}

export function listVideoStyles() {
  return Object.entries(VIDEO_STYLE_PRESETS).map(([key, v]) => ({
    key,
    label: v.label,
    category: v.category,
    thumb: v.thumb || '',
    description: v.description || '',
    prompt: v.prompt || '',
  }));
}
