import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useParams, useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Loader2, Sparkles, Check, X, RefreshCw, Lock, Copy, FlaskConical, Download, Send } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { apiFetch } from '@/lib/api';
import { toast } from 'sonner';
import LinkedInAdEditor from '@/components/ads/LinkedInAdEditor';
import LinkedInAdPreview from '@/components/ads/LinkedInAdPreview';
import GoogleRSAEditor from '@/components/ads/GoogleRSAEditor';
import GoogleAdPreview from '@/components/ads/GoogleAdPreview';
import MetaAdEditor from '@/components/ads/MetaAdEditor';
import MetaAdPreview from '@/components/ads/MetaAdPreview';

const PLATFORM_TABS = [
  { key: 'linkedin', label: 'LinkedIn', enabled: true },
  { key: 'google', label: 'Google Ads', enabled: true },
  { key: 'meta', label: 'Meta / Facebook', enabled: true },
];

const STATUS_COLORS = {
  draft: 'text-gray-500',
  approved: 'text-green-600',
  rejected: 'text-red-500',
  published: 'text-blue-600',
};

export default function AdCampaignEditor() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const autoGeneratedRef = useRef(false);
  const [campaign, setCampaign] = useState(null);
  const [variations, setVariations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [regeneratingId, setRegeneratingId] = useState(null);
  const [activePlatform, setActivePlatform] = useState('linkedin');
  const [selectedVariationIdx, setSelectedVariationIdx] = useState(0);
  const [saving, setSaving] = useState(false);
  const [brand, setBrand] = useState(null);
  const [showStylePicker, setShowStylePicker] = useState(null); // variation id when open
  const [selectedStyle, setSelectedStyle] = useState('');
  const [exporting, setExporting] = useState(false);

  const brandName = brand?.brand_name || '';

  const loadCampaign = useCallback(async () => {
    try {
      const res = await apiFetch(`/api/ads/campaigns/${id}`);
      const data = await res.json();
      if (data.campaign) {
        setCampaign(data.campaign);
        setVariations(data.campaign.ad_variations || []);
        const platforms = data.campaign.platforms || ['linkedin'];
        setActivePlatform(platforms[0] || 'linkedin');
      }
    } catch (err) {
      toast.error('Failed to load campaign');
    } finally {
      setLoading(false);
    }
  }, [id]);

  // Load brand kit for preview (logo, name, etc.)
  // Re-runs when campaign loads so we can select the matching brand kit by ID
  useEffect(() => {
    apiFetch('/api/brand/kit').then(r => r.json()).then(d => {
      const kits = d.brands || [];
      if (campaign?.brand_kit_id) {
        const matched = kits.find(k => k.id === campaign.brand_kit_id);
        setBrand(matched || d.brandKit || kits[0] || null);
      } else {
        setBrand(d.brandKit || kits[0] || null);
      }
    }).catch(() => {});
  }, [campaign?.brand_kit_id]);

  useEffect(() => { loadCampaign(); }, [loadCampaign]);

  // Auto-generate ads when navigating from the "Create Campaign" form
  useEffect(() => {
    if (!campaign || loading || autoGeneratedRef.current) return;
    if (searchParams.get('generate') === '1' && variations.length === 0) {
      autoGeneratedRef.current = true;
      handleGenerate();
    }
  }, [campaign, loading, variations.length]); // eslint-disable-line react-hooks/exhaustive-deps

  const platformVariations = variations.filter(v => v.platform === activePlatform);
  const selectedVariation = platformVariations[selectedVariationIdx] || null;

  const handleExport = async () => {
    setExporting(true);
    try {
      const res = await apiFetch(`/api/ads/campaigns/${id}/export`);
      if (!res.ok) throw new Error('Export failed');
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(campaign.name || 'campaign').replace(/\s+/g, '-').toLowerCase()}-creatives.zip`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      toast.error('Failed to export creatives');
    } finally {
      setExporting(false);
    }
  };

  const handleGenerate = async (extraPlatform = null) => {
    if (!campaign) return;
    setGenerating(true);
    try {
      const basePlatforms = campaign.platforms || ['linkedin'];
      const isNewPlatform = extraPlatform && !basePlatforms.includes(extraPlatform);
      // When adding a new platform from the empty state, only generate that platform
      // so existing variations on other platforms are not regenerated unnecessarily.
      // When clicking top "Regenerate All", generate all campaign platforms.
      const platforms = isNewPlatform ? [extraPlatform] : basePlatforms;
      const res = await apiFetch(`/api/ads/campaigns/${id}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ platforms }),
      });
      const data = await res.json();
      if (data.success) {
        const newVars = data.variations || [];
        const affectedPlatforms = [...new Set(newVars.map(v => v.platform))];
        // Merge: keep untouched platforms, replace only regenerated ones
        setVariations(prev => [
          ...prev.filter(v => !affectedPlatforms.includes(v.platform)),
          ...newVars,
        ]);
        if (isNewPlatform) {
          // Persist the new platform to the campaign record so future
          // "Regenerate All" clicks also include it
          const updatedPlatforms = [...basePlatforms, extraPlatform];
          setCampaign(prev => ({ ...prev, status: 'review', platforms: updatedPlatforms }));
          apiFetch(`/api/ads/campaigns/${id}`, {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ platforms: updatedPlatforms }),
          }).catch(() => {});
        } else {
          setCampaign(prev => ({ ...prev, status: 'review' }));
        }
        setSelectedVariationIdx(0);
      } else {
        toast.error(data.error || 'Generation failed');
      }
    } catch (err) {
      toast.error('Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const handleRegenerate = async (variationId, imageOnly = false, stylePreset = null) => {
    setRegeneratingId(variationId);
    setShowStylePicker(null);
    try {
      // Send the current local image_prompt so user edits are used directly
      const currentVariation = variations.find(v => v.id === variationId);
      const res = await apiFetch(`/api/ads/variations/${variationId}/regenerate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          regenerate_copy: !imageOnly,
          regenerate_image: imageOnly,
          style_preset: stylePreset || undefined,
          custom_prompt: imageOnly ? currentVariation?.image_prompt : undefined,
        }),
      });
      const data = await res.json();
      if (data.variation) {
        setVariations(prev => prev.map(v => {
          if (v.id !== variationId) return v;
          // Preserve unsaved copy edits if this was image-only regen
          if (imageOnly) {
            return { ...data.variation, copy_data: v.copy_data };
          }
          return data.variation;
        }));
      }
    } catch (err) {
      toast.error('Regeneration failed');
    } finally {
      setRegeneratingId(null);
    }
  };

  const handleEnhancePrompt = async (variationId, currentPrompt) => {
    try {
      const res = await apiFetch('/api/ads/enhance-prompt', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ variation_id: variationId, custom_prompt: currentPrompt }),
      });
      const data = await res.json();
      if (data.enhanced_prompt) {
        setVariations(prev => prev.map(v =>
          v.id === variationId ? { ...v, image_prompt: data.enhanced_prompt } : v
        ));
        return data.enhanced_prompt;
      }
    } catch (err) {
      toast.error('Prompt enhancement failed');
    }
    return null;
  };

  const handleUpdateVariation = (updated) => {
    setVariations(prev => {
      const old = prev.find(v => v.id === updated.id);
      const next = prev.map(v => v.id === updated.id ? updated : v);

      // If UTM params changed on the first variation of a platform,
      // propagate to other same-platform variations that have no UTM params set
      const newUtm = updated.copy_data?.utm_params;
      const oldUtm = old?.copy_data?.utm_params;
      const utmChanged = JSON.stringify(newUtm) !== JSON.stringify(oldUtm);
      if (utmChanged && newUtm) {
        const sameplatform = next.filter(v => v.platform === updated.platform);
        const isFirst = sameplatform[0]?.id === updated.id;
        if (isFirst) {
          return next.map(v => {
            if (v.platform !== updated.platform || v.id === updated.id) return v;
            const existingUtm = v.copy_data?.utm_params || {};
            const hasCustom = Object.values(existingUtm).some(val => val?.trim());
            if (hasCustom) return v; // don't overwrite manually set params
            return { ...v, copy_data: { ...v.copy_data, utm_params: { ...newUtm } } };
          });
        }
      }
      return next;
    });
  };

  const handleSave = async (variation) => {
    setSaving(true);
    try {
      await apiFetch(`/api/ads/variations/${variation.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          copy_data: variation.copy_data,
          image_urls: variation.image_urls,
          image_prompt: variation.image_prompt,
        }),
      });
    } catch {
      toast.error('Failed to save');
    } finally {
      setSaving(false);
    }
  };

  const handleStatusChange = async (variationId, status) => {
    try {
      const res = await apiFetch(`/api/ads/variations/${variationId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status }),
      });
      const data = await res.json();
      if (data.variation) {
        setVariations(prev => prev.map(v => v.id === variationId ? data.variation : v));
      }
    } catch {
      toast.error('Failed to update status');
    }
  };

  const handleDeleteVariation = async (variationId) => {
    try {
      await apiFetch(`/api/ads/variations/${variationId}`, { method: 'DELETE' });
      setVariations(prev => prev.filter(v => v.id !== variationId));
      setSelectedVariationIdx(0);
    } catch {
      toast.error('Failed to delete');
    }
  };

  const [splittingId, setSplittingId] = useState(null);
  const [publishingId, setPublishingId] = useState(null);

  const handlePublishLinkedIn = async (variationId) => {
    setPublishingId(variationId);
    try {
      const res = await apiFetch(`/api/ads/variations/${variationId}/publish-linkedin`, {
        method: 'POST',
      });
      const data = await res.json();
      if (data.success && data.variation) {
        setVariations(prev => prev.map(v => v.id === variationId ? data.variation : v));
      } else {
        toast.error(data.error || 'Failed to publish to LinkedIn');
      }
    } catch {
      toast.error('Failed to publish to LinkedIn');
    } finally {
      setPublishingId(null);
    }
  };

  const handleSplitTest = async (variationId, mode) => {
    setSplittingId(variationId);
    try {
      const res = await apiFetch(`/api/ads/variations/${variationId}/split-test`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mode }),
      });
      const data = await res.json();
      if (data.variation) {
        setVariations(prev => [...prev, data.variation]);
        // Select the new variation
        const newPlatformVars = [...platformVariations, data.variation];
        setSelectedVariationIdx(newPlatformVars.length - 1);
      } else {
        toast.error(data.error || 'Failed to create split test');
      }
    } catch {
      toast.error('Failed to create split test');
    } finally {
      setSplittingId(null);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <Loader2 className="w-8 h-8 animate-spin text-[#2C666E]" />
      </div>
    );
  }

  if (!campaign) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <p className="text-gray-500">Campaign not found</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Top bar */}
      <div className="bg-white border-b px-4 py-3 flex items-center justify-between flex-shrink-0">
        <div className="flex items-center gap-3">
          <button onClick={() => navigate('/ads')} className="p-1.5 hover:bg-gray-100 rounded-lg transition-colors">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h1 className="font-semibold text-gray-900">{campaign.name}</h1>
            <p className="text-xs text-gray-500">{campaign.objective} &middot; {campaign.status}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {variations.length > 0 && (
            <Button
              variant="outline"
              size="sm"
              onClick={handleExport}
              disabled={exporting}
            >
              {exporting ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1.5" /> : <Download className="w-3.5 h-3.5 mr-1.5" />}
              Download Creatives
            </Button>
          )}
          {selectedVariation && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => handleSave(selectedVariation)}
              disabled={saving}
            >
              {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1.5" /> : null}
              Save Changes
            </Button>
          )}
          <Button
            onClick={handleGenerate}
            disabled={generating}
            className="bg-[#2C666E] hover:bg-[#1f4f55]"
            size="sm"
          >
            {generating ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Sparkles className="w-4 h-4 mr-2" />}
            {variations.length > 0 ? 'Regenerate All' : 'Generate Ads'}
          </Button>
        </div>
      </div>

      {/* Platform tabs */}
      <div className="bg-white border-b px-4 flex-shrink-0">
        <div className="flex gap-1">
          {PLATFORM_TABS.map(tab => {
            const count = variations.filter(v => v.platform === tab.key).length;
            const isActive = activePlatform === tab.key;
            return (
              <button
                key={tab.key}
                onClick={() => {
                  if (tab.enabled) {
                    setActivePlatform(tab.key);
                    setSelectedVariationIdx(0);
                  }
                }}
                disabled={!tab.enabled}
                className={`px-4 py-2.5 text-sm font-medium border-b-2 transition-colors flex items-center gap-2 ${
                  isActive
                    ? 'border-[#2C666E] text-[#2C666E]'
                    : tab.enabled
                      ? 'border-transparent text-gray-500 hover:text-gray-700'
                      : 'border-transparent text-gray-300 cursor-not-allowed'
                }`}
              >
                {!tab.enabled && <Lock className="w-3 h-3" />}
                {tab.label}
                {count > 0 && (
                  <span className="bg-gray-100 text-gray-600 text-xs px-1.5 py-0.5 rounded-full">{count}</span>
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* Main content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left: Variation list + editor */}
        <div className="w-[480px] flex-shrink-0 border-r bg-white overflow-y-auto">
          {platformVariations.length === 0 ? (
            <div className="p-8 text-center">
              <Sparkles className="w-10 h-10 text-gray-300 mx-auto mb-3" />
              <p className="text-gray-500 text-sm mb-2">No {activePlatform} ad variations yet</p>
              <p className="text-gray-400 text-xs mb-4">Click Generate below to create AI-powered {activePlatform} ad variations</p>
              <Button onClick={() => handleGenerate(activePlatform)} disabled={generating} size="sm" className="bg-[#2C666E] hover:bg-[#1f4f55]">
                {generating ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Sparkles className="w-4 h-4 mr-2" />}
                Generate
              </Button>
            </div>
          ) : (
            <div>
              {/* Variation selector tabs */}
              <div className="flex border-b">
                {platformVariations.map((v, idx) => (
                  <button
                    key={v.id}
                    onClick={() => setSelectedVariationIdx(idx)}
                    className={`flex-1 px-3 py-2.5 text-xs font-medium border-b-2 transition-colors ${
                      selectedVariationIdx === idx
                        ? 'border-[#2C666E] text-[#2C666E]'
                        : 'border-transparent text-gray-500 hover:text-gray-700'
                    }`}
                  >
                    <span>{String.fromCharCode(65 + idx)}</span>
                    <span className={`ml-1.5 ${STATUS_COLORS[v.status] || ''}`}>
                      {v.status === 'approved' && <Check className="w-3 h-3 inline" />}
                      {v.status === 'rejected' && <X className="w-3 h-3 inline" />}
                    </span>
                  </button>
                ))}
              </div>

              {/* Editor */}
              {selectedVariation && (
                <div className="p-4">
                  {/* Approve/Reject + actions bar */}
                  <div className="flex items-center gap-2 mb-2">
                    <Button
                      variant={selectedVariation.status === 'approved' ? 'default' : 'outline'}
                      size="sm"
                      onClick={() => handleStatusChange(selectedVariation.id, selectedVariation.status === 'approved' ? 'draft' : 'approved')}
                      className={selectedVariation.status === 'approved' ? 'bg-green-600 hover:bg-green-700' : ''}
                    >
                      <Check className="w-3.5 h-3.5 mr-1" />
                      {selectedVariation.status === 'approved' ? 'Approved' : 'Approve'}
                    </Button>
                    <Button
                      variant={selectedVariation.status === 'rejected' ? 'default' : 'outline'}
                      size="sm"
                      onClick={() => handleStatusChange(selectedVariation.id, selectedVariation.status === 'rejected' ? 'draft' : 'rejected')}
                      className={selectedVariation.status === 'rejected' ? 'bg-red-500 hover:bg-red-600' : ''}
                    >
                      <X className="w-3.5 h-3.5 mr-1" />
                      {selectedVariation.status === 'rejected' ? 'Rejected' : 'Reject'}
                    </Button>
                    <div className="flex-1" />
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleSplitTest(selectedVariation.id, 'duplicate')}
                      disabled={splittingId === selectedVariation.id}
                      title="Duplicate for manual A/B editing"
                    >
                      <Copy className="w-3 h-3 mr-1" />
                      Duplicate
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleSplitTest(selectedVariation.id, 'ai')}
                      disabled={splittingId === selectedVariation.id}
                      title="AI generates a different angle for split testing"
                    >
                      {splittingId === selectedVariation.id
                        ? <Loader2 className="w-3 h-3 animate-spin mr-1" />
                        : <FlaskConical className="w-3 h-3 mr-1" />
                      }
                      Split Test
                    </Button>
                    <button
                      onClick={() => handleDeleteVariation(selectedVariation.id)}
                      className="text-xs text-gray-400 hover:text-red-500 transition-colors"
                    >
                      Delete
                    </button>
                  </div>

                  {/* Publish to LinkedIn */}
                  {selectedVariation.platform === 'linkedin' && selectedVariation.status === 'approved' && (
                    <div className="flex items-center gap-2 mb-4">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handlePublishLinkedIn(selectedVariation.id)}
                        disabled={publishingId === selectedVariation.id}
                        className="border-blue-300 text-blue-700 hover:bg-blue-50"
                      >
                        {publishingId === selectedVariation.id
                          ? <Loader2 className="w-3 h-3 animate-spin mr-1" />
                          : <Send className="w-3 h-3 mr-1" />
                        }
                        Publish to LinkedIn
                      </Button>
                      {selectedVariation.platform_ad_id && (
                        <span className="text-xs text-blue-600 font-mono truncate max-w-[200px]" title={selectedVariation.platform_ad_id}>
                          {selectedVariation.platform_ad_id}
                        </span>
                      )}
                    </div>
                  )}
                  {selectedVariation.platform_ad_id && selectedVariation.status === 'published' && (
                    <div className="flex items-center gap-2 mb-4 px-2 py-1.5 bg-blue-50 rounded-md">
                      <Send className="w-3 h-3 text-blue-600 flex-shrink-0" />
                      <span className="text-xs text-blue-700">Published:</span>
                      <span className="text-xs text-blue-600 font-mono truncate" title={selectedVariation.platform_ad_id}>
                        {selectedVariation.platform_ad_id}
                      </span>
                    </div>
                  )}

                  {activePlatform === 'linkedin' && (
                    <LinkedInAdEditor
                      variation={selectedVariation}
                      onUpdate={handleUpdateVariation}
                      onRegenerate={handleRegenerate}
                      onEnhancePrompt={handleEnhancePrompt}
                      regenerating={regeneratingId === selectedVariation.id}
                      landingUrl={campaign?.landing_url}
                    />
                  )}
                  {activePlatform === 'google' && (
                    <GoogleRSAEditor
                      variation={selectedVariation}
                      onUpdate={handleUpdateVariation}
                      onRegenerate={handleRegenerate}
                      onEnhancePrompt={handleEnhancePrompt}
                      regenerating={regeneratingId === selectedVariation.id}
                      campaignName={campaign?.name}
                      landingUrl={campaign?.landing_url}
                    />
                  )}
                  {activePlatform === 'meta' && (
                    <MetaAdEditor
                      variation={selectedVariation}
                      onUpdate={handleUpdateVariation}
                      onRegenerate={handleRegenerate}
                      onEnhancePrompt={handleEnhancePrompt}
                      regenerating={regeneratingId === selectedVariation.id}
                      landingUrl={campaign?.landing_url}
                    />
                  )}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Right: Preview */}
        <div className="flex-1 overflow-y-auto bg-gray-100 p-8 flex items-start justify-center">
          {selectedVariation ? (
            <div>
              <p className="text-xs text-gray-500 text-center mb-4 font-medium uppercase tracking-wide">
                {activePlatform === 'linkedin' ? 'LinkedIn Feed Preview' : activePlatform === 'google' ? 'Google Search Preview' : activePlatform === 'meta' ? 'Facebook / Instagram Preview' : `${activePlatform} Preview`}
              </p>
              {activePlatform === 'linkedin' && (
                <LinkedInAdPreview variation={selectedVariation} brandName={brandName} brandLogoUrl={brand?.logo_url} />
              )}
              {activePlatform === 'google' && (
                <GoogleAdPreview variation={selectedVariation} landingUrl={campaign?.landing_url} />
              )}
              {activePlatform === 'meta' && (
                <MetaAdPreview variation={selectedVariation} brandName={brandName} brandLogoUrl={brand?.logo_url} />
              )}
            </div>
          ) : (
            <div className="text-center text-gray-400 mt-20">
              <p className="text-sm">Select or generate a variation to preview</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
