/**
 * Frontend mirror of api/lib/videoStyleFrameworks.js.
 * Display data only — no pipeline config. Keep in sync with backend when adding frameworks.
 *
 * Badges are derived from pipeline properties:
 *   frameChain    → 'Frame Chain'
 *   ttsMode       → 'Single TTS' | 'Per-Scene TTS'
 *   transitionType → 'Crossfade' | 'Hard Cut'
 */

function deriveBadges({ frameChain, ttsMode, transitionType }) {
  const badges = [];
  if (frameChain) badges.push('Frame Chain');
  badges.push(ttsMode === 'single' ? 'Single TTS' : 'Per-Scene TTS');
  badges.push(transitionType === 'crossfade' ? 'Crossfade' : 'Hard Cut');
  return badges;
}

export const FRAMEWORK_CARDS = [
  // ─── Universal frameworks (original 16) ───────────────────────────────────────
  {
    id: 'personal_journey',
    name: 'Personal Journey',
    category: 'story',
    applicableNiches: null,
    description: 'First-person narrative arc following a transformative experience with emotional beats.',
    thumb: '/assets/frameworks/personal-journey.jpg',
    hook: 'How I went from [A] to [B]',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'origin_story',
    name: 'Origin Story',
    category: 'story',
    applicableNiches: null,
    description: 'The humble beginnings and rise of a brand, person, or idea — told with building energy.',
    thumb: '/assets/frameworks/origin-story.jpg',
    hook: 'How [brand/person/thing] started in a [humble place]',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'mini_documentary',
    name: 'Mini Documentary',
    category: 'story',
    applicableNiches: null,
    description: 'Authoritative deep-dive into a subject with cold open hook and measured narrative pacing.',
    thumb: '/assets/frameworks/mini-documentary.jpg',
    hook: 'The untold story of [X]',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'documentary', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'day_in_the_life',
    name: 'Day in the Life',
    category: 'story',
    applicableNiches: null,
    description: 'Casual first-person walkthrough of a typical day with timestamp anchors and vlog energy.',
    thumb: '/assets/frameworks/day-in-the-life.jpg',
    hook: 'A day in the life of a [profession]',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'photorealistic', videoStylePreset: 'vlog_bts', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'before_after',
    name: 'Before & After',
    category: 'story',
    applicableNiches: null,
    description: 'Transformation reveal with building tension and a satisfying visual payoff.',
    thumb: '/assets/frameworks/before-after.jpg',
    hook: 'Watch [X] transform from [A] to [B]',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'photorealistic', videoStylePreset: 'commercial', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'explainer_story',
    name: 'Explainer Story',
    category: 'story',
    applicableNiches: null,
    description: 'Curiosity-driven explanation that subverts common assumptions with a satisfying reveal.',
    thumb: '/assets/frameworks/explainer-story.jpg',
    hook: 'Why [X] is the way it is',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'emotional_tribute',
    name: 'Emotional Tribute',
    category: 'story',
    applicableNiches: null,
    description: 'Slow, warm tribute to a person, place, or era — heavy on feeling and visual beauty.',
    thumb: '/assets/frameworks/emotional-tribute.jpg',
    hook: 'A tribute to [X]',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'top_x_countdown',
    name: 'Top X Countdown',
    category: 'fast_paced',
    applicableNiches: null,
    description: 'Ranked list with energetic pacing — each item gets its own punchy scene.',
    thumb: '/assets/frameworks/top-x-countdown.jpg',
    hook: "Top 5 [X] you've never heard of",
    supportedDurations: [30, 45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'everything_you_need_to_know',
    name: 'Everything You Need to Know',
    category: 'fast_paced',
    applicableNiches: null,
    description: 'Dense information delivery — explain a topic completely in under a minute.',
    thumb: '/assets/frameworks/everything-you-need-to-know.jpg',
    hook: 'Everything you need to know about [X] in 60 seconds',
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'myth_busting',
    name: 'Myth Busting',
    category: 'fast_paced',
    applicableNiches: null,
    description: 'Debunk popular misconceptions with confident energy and a clear alternative.',
    thumb: '/assets/frameworks/myth-busting.jpg',
    hook: '3 myths about [X] that are completely wrong',
    supportedDurations: [30, 45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'commercial', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'comparison_versus',
    name: 'Comparison / Versus',
    category: 'fast_paced',
    applicableNiches: null,
    description: 'Head-to-head matchup between two options, ending with a decisive verdict.',
    thumb: '/assets/frameworks/comparison-versus.jpg',
    hook: '[X] vs [Y] - which one actually wins?',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'commercial', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'did_you_know',
    name: 'Did You Know',
    category: 'fast_paced',
    applicableNiches: null,
    description: 'Surprising facts delivered with conspiratorial energy — each one lands with weight.',
    thumb: '/assets/frameworks/did-you-know.jpg',
    hook: "What you didn't know about [X]",
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'challenge_experiment',
    name: 'Challenge / Experiment',
    category: 'story',
    applicableNiches: null,
    description: 'First-person challenge or experiment with timestamp anchors and personal outcome reveal.',
    thumb: '/assets/frameworks/challenge-experiment.jpg',
    hook: "I tried [X] for 30 days - here's what happened",
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'photorealistic', videoStylePreset: 'vlog_bts', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'history_timeline',
    name: 'History / Timeline',
    category: 'fast_paced',
    applicableNiches: null,
    description: 'Fast chronological sweep through an era or evolution with year-stamped scenes.',
    thumb: '/assets/frameworks/history-timeline.jpg',
    hook: 'The entire history of [X] in 60 seconds',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'hot_take',
    name: 'Hot Take',
    category: 'fast_paced',
    applicableNiches: null,
    description: 'Bold opinion delivered with confidence — makes viewers react and share.',
    thumb: '/assets/frameworks/hot-take.jpg',
    hook: 'The most overrated [X] and what to use instead',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'how_it_works',
    name: 'How It Works',
    category: 'story',
    applicableNiches: null,
    description: 'Clear, teacher-like walkthrough of a mechanism or process with visual anchors.',
    thumb: '/assets/frameworks/how-it-works.jpg',
    hook: 'How [X] actually works',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'corporate', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // ─── Niche-specific frameworks (60) ────────────────────────────────────────────

  // ai_tech_news (3)
  {
    id: 'ai_tech_demo',
    name: 'Tech Demo Walkthrough',
    category: 'story',
    applicableNiches: ['ai_tech_news'],
    description: 'Step-by-step walkthrough of a tech product or AI tool with clear visual anchors.',
    thumb: '/assets/frameworks/ai-tech-demo.jpg',
    hook: 'Watch how [tool] actually works',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'commercial', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'ai_breaking_news',
    name: 'Breaking Tech News',
    category: 'fast_paced',
    applicableNiches: ['ai_tech_news'],
    description: 'Urgent-paced tech news delivery with rapid information density.',
    thumb: '/assets/frameworks/ai-breaking-news.jpg',
    hook: 'Breaking: [X] just changed everything',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'ai_tool_review',
    name: 'AI Tool Review',
    category: 'fast_paced',
    applicableNiches: ['ai_tech_news'],
    description: 'Quick-fire AI tool evaluation with pros, cons, and verdict.',
    thumb: '/assets/frameworks/ai-tool-review.jpg',
    hook: "I tested [tool] so you don't have to",
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'commercial', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },

  // finance_money (3)
  {
    id: 'finance_blueprint',
    name: 'Wealth Blueprint',
    category: 'story',
    applicableNiches: ['finance_money'],
    description: 'Step-by-step financial strategy with building momentum toward a clear outcome.',
    thumb: '/assets/frameworks/finance-blueprint.jpg',
    hook: 'The wealth-building strategy nobody teaches you',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'corporate', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'finance_market_pulse',
    name: 'Market Pulse',
    category: 'fast_paced',
    applicableNiches: ['finance_money'],
    description: 'Rapid market analysis with urgent energy and key data points.',
    thumb: '/assets/frameworks/finance-market-pulse.jpg',
    hook: 'Markets just did something insane',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'finance_money_mistakes',
    name: 'Money Mistakes',
    category: 'fast_paced',
    applicableNiches: ['finance_money'],
    description: 'Common financial errors revealed with actionable alternatives.',
    thumb: '/assets/frameworks/finance-money-mistakes.jpg',
    hook: '5 money mistakes keeping you broke',
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'commercial', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },

  // motivation_self_help (3)
  {
    id: 'motivation_rise_grind',
    name: 'Rise & Grind',
    category: 'story',
    applicableNiches: ['motivation_self_help'],
    description: 'Discipline-focused daily routine narrative with building energy.',
    thumb: '/assets/frameworks/motivation-rise-grind.jpg',
    hook: 'The 5am routine that changed my life',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'motivation_mindset_shift',
    name: 'Mindset Shift',
    category: 'story',
    applicableNiches: ['motivation_self_help'],
    description: 'Internal transformation story — old belief vs new perspective with emotional payoff.',
    thumb: '/assets/frameworks/motivation-mindset-shift.jpg',
    hook: 'The mindset that separates winners from everyone else',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'motivation_life_lesson',
    name: 'Life Lessons',
    category: 'story',
    applicableNiches: ['motivation_self_help'],
    description: 'Single powerful life lesson with setup, struggle, and clarity.',
    thumb: '/assets/frameworks/motivation-life-lesson.jpg',
    hook: 'The lesson that took me 10 years to learn',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // scary_horror (3)
  {
    id: 'horror_campfire',
    name: 'Campfire Story',
    category: 'story',
    applicableNiches: ['scary_horror'],
    description: 'Classic horror narration with slow atmospheric dread building to a terrifying climax.',
    thumb: '/assets/frameworks/horror-campfire.jpg',
    hook: 'Let me tell you about the night everything changed',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'dark_horror', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'horror_creepy_countdown',
    name: 'Creepy Countdown',
    category: 'fast_paced',
    applicableNiches: ['scary_horror'],
    description: 'Ranked list of terrifying things with escalating dread.',
    thumb: '/assets/frameworks/horror-creepy-countdown.jpg',
    hook: 'Top 5 most disturbing [X] ever found',
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'dark_horror', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'horror_urban_legend',
    name: 'Urban Legend',
    category: 'story',
    applicableNiches: ['scary_horror'],
    description: 'Investigate a specific urban legend — origins, evidence, and chilling truth.',
    thumb: '/assets/frameworks/horror-urban-legend.jpg',
    hook: 'The urban legend that turned out to be real',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'dark_horror', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // history_did_you_know (3)
  {
    id: 'history_lost_civilization',
    name: 'Lost Civilization',
    category: 'story',
    applicableNiches: ['history_did_you_know'],
    description: 'Deep dive into a disappeared culture — rise, peak, mysterious end.',
    thumb: '/assets/frameworks/history-lost-civilization.jpg',
    hook: 'The civilization that vanished without a trace',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'history_what_if',
    name: 'Historical What-If',
    category: 'story',
    applicableNiches: ['history_did_you_know'],
    description: 'Counterfactual history exploration — premise, ripple effects, alternate timeline.',
    thumb: '/assets/frameworks/history-what-if.jpg',
    hook: 'What if [historical event] never happened?',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'history_forgotten_heroes',
    name: 'Forgotten Heroes',
    category: 'story',
    applicableNiches: ['history_did_you_know'],
    description: 'Spotlight on overlooked historical figures — their deeds and why they were forgotten.',
    thumb: '/assets/frameworks/history-forgotten-heroes.jpg',
    hook: "The person history forgot but shouldn't have",
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // true_crime (3)
  {
    id: 'crime_case_file',
    name: 'Case File',
    category: 'story',
    applicableNiches: ['true_crime'],
    description: 'Structured true crime investigation — crime, suspects, evidence, verdict.',
    thumb: '/assets/frameworks/crime-case-file.jpg',
    hook: 'Case #[X]: the crime that baffled detectives',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'noir', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'crime_evidence_trail',
    name: 'Evidence Trail',
    category: 'story',
    applicableNiches: ['true_crime'],
    description: 'Follow the evidence piece by piece toward a surprising revelation.',
    thumb: '/assets/frameworks/crime-evidence-trail.jpg',
    hook: 'One clue led to another, and another...',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'noir', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'crime_cold_case',
    name: 'Cold Case Reopened',
    category: 'story',
    applicableNiches: ['true_crime'],
    description: 'Revisiting unsolved cases with new evidence or perspectives.',
    thumb: '/assets/frameworks/crime-cold-case.jpg',
    hook: 'This case went cold for 20 years — until now',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'noir', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // science_nature (3)
  {
    id: 'science_discovery',
    name: 'Lab Discovery',
    category: 'story',
    applicableNiches: ['science_nature'],
    description: 'Scientific breakthrough revealed — hypothesis, experiment, mind-blowing result.',
    thumb: '/assets/frameworks/science-discovery.jpg',
    hook: 'Scientists just discovered something that changes everything',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'science_nature_secrets',
    name: "Nature's Secrets",
    category: 'fast_paced',
    applicableNiches: ['science_nature'],
    description: 'Rapid-fire natural phenomena that defy expectations.',
    thumb: '/assets/frameworks/science-nature-secrets.jpg',
    hook: "5 things nature does that science can't explain",
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'nature', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'science_thought_experiment',
    name: 'Thought Experiment',
    category: 'story',
    applicableNiches: ['science_nature'],
    description: 'Scientific what-if scenario explored step by step with escalating consequences.',
    thumb: '/assets/frameworks/science-thought-experiment.jpg',
    hook: 'What would happen if [impossible scenario]?',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // relationships_dating (3)
  {
    id: 'dating_love_story',
    name: 'Love Story',
    category: 'story',
    applicableNiches: ['relationships_dating'],
    description: 'Relationship narrative arc — meeting, connection, challenge, resolution.',
    thumb: '/assets/frameworks/dating-love-story.jpg',
    hook: 'A love story that changed how I see relationships',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'dating_red_flags',
    name: 'Red Flag Rundown',
    category: 'fast_paced',
    applicableNiches: ['relationships_dating'],
    description: 'Rapid-fire relationship warning signs with clear examples.',
    thumb: '/assets/frameworks/dating-red-flags.jpg',
    hook: '5 red flags you keep ignoring',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'dating_attachment',
    name: 'Attachment Decoded',
    category: 'story',
    applicableNiches: ['relationships_dating'],
    description: 'Psychology-driven relationship deep-dive — pattern recognition and breakthrough.',
    thumb: '/assets/frameworks/dating-attachment.jpg',
    hook: 'Your attachment style is ruining your relationships',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // health_fitness (3)
  {
    id: 'fitness_transformation',
    name: 'Body Transformation',
    category: 'story',
    applicableNiches: ['health_fitness'],
    description: 'Before-and-after fitness journey with milestones and payoff reveal.',
    thumb: '/assets/frameworks/fitness-transformation.jpg',
    hook: 'How I completely transformed my body in [X] days',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'photorealistic', videoStylePreset: 'commercial', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'fitness_health_hack',
    name: 'Health Hack',
    category: 'fast_paced',
    applicableNiches: ['health_fitness'],
    description: 'Quick actionable health tips with evidence and instant takeaways.',
    thumb: '/assets/frameworks/fitness-health-hack.jpg',
    hook: '3 health hacks backed by science',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'photorealistic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'fitness_myth_buster',
    name: 'Fitness Myth Buster',
    category: 'fast_paced',
    applicableNiches: ['health_fitness'],
    description: 'Debunking exercise and diet myths with the real science.',
    thumb: '/assets/frameworks/fitness-myth-buster.jpg',
    hook: 'Stop believing these fitness lies',
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'photorealistic', videoStylePreset: 'commercial', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },

  // gaming_popculture (3)
  {
    id: 'gaming_lore',
    name: 'Gaming Lore',
    category: 'story',
    applicableNiches: ['gaming_popculture'],
    description: 'Deep dive into game universe lore — origins, secrets, and fan theories.',
    thumb: '/assets/frameworks/gaming-lore.jpg',
    hook: 'The hidden lore behind [game] you missed',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'gaming_easter_eggs',
    name: 'Hidden Easter Eggs',
    category: 'fast_paced',
    applicableNiches: ['gaming_popculture'],
    description: 'Countdown of secret finds and hidden details in games or movies.',
    thumb: '/assets/frameworks/gaming-easter-eggs.jpg',
    hook: 'Easter eggs in [game] you definitely missed',
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'gaming_pop_breakdown',
    name: 'Pop Culture Breakdown',
    category: 'fast_paced',
    applicableNiches: ['gaming_popculture'],
    description: 'Analyzing a trending pop culture moment with rapid takes.',
    thumb: '/assets/frameworks/gaming-pop-breakdown.jpg',
    hook: 'Why everyone is talking about [X] right now',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },

  // conspiracy_mystery (3)
  {
    id: 'conspiracy_rabbit_hole',
    name: 'Rabbit Hole',
    category: 'story',
    applicableNiches: ['conspiracy_mystery'],
    description: 'Progressive descent into deeper layers of a mystery or conspiracy.',
    thumb: '/assets/frameworks/conspiracy-rabbit-hole.jpg',
    hook: "I went down the [X] rabbit hole — here's what I found",
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'dark_horror', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'conspiracy_cover_up',
    name: 'Cover-Up Exposed',
    category: 'story',
    applicableNiches: ['conspiracy_mystery'],
    description: 'Revealing hidden truths — official story vs evidence vs what really happened.',
    thumb: '/assets/frameworks/conspiracy-cover-up.jpg',
    hook: 'They tried to hide this from the public',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'conspiracy_unsolved',
    name: 'Mystery Unsolved',
    category: 'story',
    applicableNiches: ['conspiracy_mystery'],
    description: 'Examining an open mystery — the evidence, the theories, why it remains unsolved.',
    thumb: '/assets/frameworks/conspiracy-unsolved.jpg',
    hook: 'Nobody has ever been able to explain [X]',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // business_entrepreneur (3)
  {
    id: 'business_startup_story',
    name: 'Startup Story',
    category: 'story',
    applicableNiches: ['business_entrepreneur'],
    description: 'Founding narrative of a company — humble start, pivots, and breakthrough.',
    thumb: '/assets/frameworks/business-startup-story.jpg',
    hook: 'How [company] went from garage to billions',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'corporate', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'business_breakdown',
    name: 'Business Breakdown',
    category: 'fast_paced',
    applicableNiches: ['business_entrepreneur'],
    description: 'Rapid analysis of a business model — revenue streams, strategy, moat.',
    thumb: '/assets/frameworks/business-breakdown.jpg',
    hook: 'How [company] actually makes money',
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'corporate', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'business_revenue_playbook',
    name: 'Revenue Playbook',
    category: 'fast_paced',
    applicableNiches: ['business_entrepreneur'],
    description: 'Actionable business strategies delivered with punchy energy.',
    thumb: '/assets/frameworks/business-revenue-playbook.jpg',
    hook: 'The playbook that took me from $0 to $10K/month',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },

  // food_cooking (3)
  {
    id: 'food_recipe_reveal',
    name: 'Recipe Reveal',
    category: 'story',
    applicableNiches: ['food_cooking'],
    description: 'Building a dish step by step — ingredients, technique, satisfying final reveal.',
    thumb: '/assets/frameworks/food-recipe-reveal.jpg',
    hook: 'The secret recipe that went viral',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'photorealistic', videoStylePreset: 'food', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'food_science',
    name: 'Food Science',
    category: 'story',
    applicableNiches: ['food_cooking'],
    description: 'Why food works the way it does — chemistry, technique, and revelation.',
    thumb: '/assets/frameworks/food-science.jpg',
    hook: 'The science behind why [food] tastes so good',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'food_street_tour',
    name: 'Street Food Tour',
    category: 'fast_paced',
    applicableNiches: ['food_cooking'],
    description: 'Rapid tour of street foods — each dish gets its own punchy scene.',
    thumb: '/assets/frameworks/food-street-tour.jpg',
    hook: 'I ate every street food in [city]',
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'photorealistic', videoStylePreset: 'food', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },

  // travel_adventure (3)
  {
    id: 'travel_hidden_gem',
    name: 'Hidden Gem',
    category: 'story',
    applicableNiches: ['travel_adventure'],
    description: 'Discovering an unknown destination — arrival, exploration, wonder.',
    thumb: '/assets/frameworks/travel-hidden-gem.jpg',
    hook: "The place tourists don't know about yet",
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'travel', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'travel_hacks',
    name: 'Travel Hacks',
    category: 'fast_paced',
    applicableNiches: ['travel_adventure'],
    description: 'Rapid money and time saving travel tips.',
    thumb: '/assets/frameworks/travel-hacks.jpg',
    hook: 'Travel hacks that save you hundreds',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'travel_adventure_log',
    name: 'Adventure Log',
    category: 'story',
    applicableNiches: ['travel_adventure'],
    description: 'First-person travel experience with timestamp anchors and vlog energy.',
    thumb: '/assets/frameworks/travel-adventure-log.jpg',
    hook: '48 hours in [destination] — the full experience',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'travel', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // psychology_mindblown (3)
  {
    id: 'psych_mind_trick',
    name: 'Mind Trick',
    category: 'story',
    applicableNiches: ['psychology_mindblown'],
    description: 'Demonstrating a psychological phenomenon — setup, reveal, explanation.',
    thumb: '/assets/frameworks/psych-mind-trick.jpg',
    hook: 'Your brain is lying to you right now',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'psych_social_experiment',
    name: 'Social Experiment',
    category: 'story',
    applicableNiches: ['psychology_mindblown'],
    description: 'Showing human behavior patterns through experiment narrative.',
    thumb: '/assets/frameworks/psych-social-experiment.jpg',
    hook: 'We tested [X] on 100 strangers — the results were shocking',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'psych_facts',
    name: 'Psych Facts',
    category: 'fast_paced',
    applicableNiches: ['psychology_mindblown'],
    description: 'Rapid-fire psychology facts with mind-blowing implications.',
    thumb: '/assets/frameworks/psych-facts.jpg',
    hook: 'Psychology facts that will change how you see people',
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },

  // space_cosmos (3)
  {
    id: 'space_cosmic_journey',
    name: 'Cosmic Journey',
    category: 'story',
    applicableNiches: ['space_cosmos'],
    description: 'Narrative exploration of a cosmic destination — departure, journey, arrival, wonder.',
    thumb: '/assets/frameworks/space-cosmic-journey.jpg',
    hook: "Let's travel to [cosmic destination]",
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'space_mystery',
    name: 'Space Mystery',
    category: 'story',
    applicableNiches: ['space_cosmos'],
    description: 'Investigating a cosmic anomaly — discovery, theories, implications.',
    thumb: '/assets/frameworks/space-mystery.jpg',
    hook: "NASA detected something they can't explain",
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'space_cosmic_scale',
    name: 'Cosmic Scale',
    category: 'fast_paced',
    applicableNiches: ['space_cosmos'],
    description: 'Mind-blowing size and distance comparisons that escalate rapidly.',
    thumb: '/assets/frameworks/space-cosmic-scale.jpg',
    hook: 'The size of the universe will break your brain',
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },

  // animals_wildlife (3)
  {
    id: 'animals_creature_feature',
    name: 'Creature Feature',
    category: 'story',
    applicableNiches: ['animals_wildlife'],
    description: 'Deep dive on one animal — habitat, abilities, why it matters.',
    thumb: '/assets/frameworks/animals-creature-feature.jpg',
    hook: "The most incredible animal you've never heard of",
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'nature', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'animals_superpowers',
    name: 'Animal Superpowers',
    category: 'fast_paced',
    applicableNiches: ['animals_wildlife'],
    description: 'Ranked animal abilities — each more incredible than the last.',
    thumb: '/assets/frameworks/animals-superpowers.jpg',
    hook: "Animals with powers that shouldn't be real",
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'nature', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'animals_nature_hunt',
    name: 'Nature Hunt',
    category: 'story',
    applicableNiches: ['animals_wildlife'],
    description: 'First-person wildlife tracking narrative — preparation, journey, encounter.',
    thumb: '/assets/frameworks/animals-nature-hunt.jpg',
    hook: 'Tracking the rarest [animal] on Earth',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'nature', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // sports_athletes (3)
  {
    id: 'sports_athlete_rise',
    name: 'Athlete Rise',
    category: 'story',
    applicableNiches: ['sports_athletes'],
    description: 'Rise of a sports star — humble start, training, breakthrough moment.',
    thumb: '/assets/frameworks/sports-athlete-rise.jpg',
    hook: 'From nobody to legend — the [athlete] story',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'sports_game_changer',
    name: 'Game Changer',
    category: 'story',
    applicableNiches: ['sports_athletes'],
    description: 'A single game-changing moment — buildup, the play, aftermath.',
    thumb: '/assets/frameworks/sports-game-changer.jpg',
    hook: 'The single moment that changed [sport] forever',
    supportedDurations: [45, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'cinematic', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'sports_stats_showdown',
    name: 'Stats Showdown',
    category: 'fast_paced',
    applicableNiches: ['sports_athletes'],
    description: 'Impressive sports statistics delivered with punchy energy.',
    thumb: '/assets/frameworks/sports-stats-showdown.jpg',
    hook: 'Sports stats that will blow your mind',
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },

  // education_learning (3)
  {
    id: 'edu_quick_lesson',
    name: 'Quick Lesson',
    category: 'fast_paced',
    applicableNiches: ['education_learning'],
    description: 'Teach something completely in under a minute — definition, how, why it matters.',
    thumb: '/assets/frameworks/edu-quick-lesson.jpg',
    hook: 'Learn [X] in 60 seconds',
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'commercial', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'edu_fact_blast',
    name: 'Fact Blast',
    category: 'fast_paced',
    applicableNiches: ['education_learning'],
    description: 'Rapid-fire interesting facts with visual impact.',
    thumb: '/assets/frameworks/edu-fact-blast.jpg',
    hook: "Facts you weren't taught in school",
    supportedDurations: [30, 45],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'tiktok_reels', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'edu_discovery',
    name: 'The Discovery',
    category: 'story',
    applicableNiches: ['education_learning'],
    description: 'Story of a major discovery or invention — the person, the moment, the impact.',
    thumb: '/assets/frameworks/edu-discovery.jpg',
    hook: 'The accidental discovery that changed the world',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },

  // paranormal_ufo (3)
  {
    id: 'paranormal_encounter',
    name: 'Encounter Report',
    category: 'story',
    applicableNiches: ['paranormal_ufo'],
    description: 'First-person encounter narrative — setup, event, aftermath, questions.',
    thumb: '/assets/frameworks/paranormal-encounter.jpg',
    hook: 'Their encounter defied all explanation',
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'dark_horror', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
  {
    id: 'paranormal_evidence',
    name: 'Evidence File',
    category: 'fast_paced',
    applicableNiches: ['paranormal_ufo'],
    description: 'Presenting paranormal evidence piece by piece with escalating weight.',
    thumb: '/assets/frameworks/paranormal-evidence.jpg',
    hook: "The evidence they can't debunk",
    supportedDurations: [30, 60],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'documentary', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: false,
    badges: deriveBadges({ frameChain: false, ttsMode: 'per_scene', transitionType: 'hard_cut' }),
  },
  {
    id: 'paranormal_investigation',
    name: 'Investigation',
    category: 'story',
    applicableNiches: ['paranormal_ufo'],
    description: 'Step-by-step paranormal investigation — arrive, investigate, reveal.',
    thumb: '/assets/frameworks/paranormal-investigation.jpg',
    hook: "We investigated [location] — here's what we found",
    supportedDurations: [60, 90],
    defaults: { visualStyle: 'cinematic', videoStylePreset: 'dark_horror', imageModel: 'fal_nano_banana', videoModel: 'fal_veo3' },
    frameChain: true,
    badges: deriveBadges({ frameChain: true, ttsMode: 'single', transitionType: 'crossfade' }),
  },
];

export function getFrameworkCard(id) {
  return FRAMEWORK_CARDS.find(f => f.id === id) || null;
}

export function getFrameworksByCategory(category) {
  return FRAMEWORK_CARDS.filter(f => f.category === category);
}

export function getFrameworksForNiche(niche) {
  return FRAMEWORK_CARDS.filter(f => !f.applicableNiches || f.applicableNiches.includes(niche));
}
